/******************************************************************************************************************
* Engineer    : automatic generated
* Date        : 9/29/2015
********************************************************************************************************************/

#ifndef __ENUMS_Jaguar_Land_Rover_H__
#define __ENUMS_Jaguar_Land_Rover_H__



    
    typedef enum _enumCommand_Jaguar_Land_Rover{
        ecommand_UNKNOWN_Jaguar_Land_Rover   = 0,
        ecommand_03_____22_____F1_____90_____00_____00_____00_____00_Jaguar_Land_Rover  = 1,
        ecommand_09_Jaguar_Land_Rover  = 2,
        ecommand_06_Jaguar_Land_Rover  = 3,
        ecommand_03_____22_____00_____02_Jaguar_Land_Rover  = 4,
        ecommand_01_____20_Jaguar_Land_Rover  = 5,
        ecommand_3E_Jaguar_Land_Rover  = 6,
        ecommand_82_Jaguar_Land_Rover  = 7,
        ecommand_3E_____00_____00_Jaguar_Land_Rover  = 8,
        ecommand_00_Jaguar_Land_Rover  = 9,
        ecommand_9F_Jaguar_Land_Rover  = 10,
        ecommand_03_____22_____F1_____03_____00_____00_____00_____00_Jaguar_Land_Rover  = 11,
        ecommand_04_____14_____FF_____FF_____FF_____00_____00_____00_Jaguar_Land_Rover  = 12,
        ecommand_03_____19_____02_____AF_____00_____00_____00_____00_Jaguar_Land_Rover  = 13,
        ecommand_05_Jaguar_Land_Rover  = 14,
        ecommand_07_Jaguar_Land_Rover  = 15,
        ecommand_02_____10_____02_Jaguar_Land_Rover  = 16,
        ecommand_01_____04_Jaguar_Land_Rover  = 17,
        ecommand_01_____14_Jaguar_Land_Rover  = 18,
        ecommand_01_____03_Jaguar_Land_Rover  = 19,
        ecommand_03_____13_____02_____00_Jaguar_Land_Rover  = 20,
        ecommand_03_____13_____12_____FE_CURRENT_____TRIP_Jaguar_Land_Rover  = 21,
        ecommand_03_____13_____12_____FE_PREVIOUS_____TRIP_Jaguar_Land_Rover  = 22,
        ecommand_81_Jaguar_Land_Rover  = 23,
        ecommand_14_____FF_____FF_Jaguar_Land_Rover  = 24,
        ecommand_18_____02_____FF_____FF_Jaguar_Land_Rover  = 25,
        ecommand_10_____87_Jaguar_Land_Rover  = 26,
        ecommand_14_____80_____00_Jaguar_Land_Rover  = 27,
        ecommand_18_____00_____80_____00_Jaguar_Land_Rover  = 28,
        ecommand_10_____81_Jaguar_Land_Rover  = 29,
        ecommand_A0_____00_Jaguar_Land_Rover  = 30,
        ecommand_12_____04_____00_Jaguar_Land_Rover  = 31,
        ecommand_12_____04_____05_Jaguar_Land_Rover  = 32,
        ecommand_12_____04_____A0_Jaguar_Land_Rover  = 33,
        ecommand_12_____05_____14_____00_Jaguar_Land_Rover  = 34,
        ecommand_12_____05_____14_____01_Jaguar_Land_Rover  = 35,
        ecommand_19_____04_____00_Jaguar_Land_Rover  = 36,
        ecommand_04_____01_Jaguar_Land_Rover  = 37,
        ecommand_1A_____9A_Jaguar_Land_Rover  = 38,
        ecommand_1A_____9B_Jaguar_Land_Rover  = 39,
        ecommand_1A_____9C_Jaguar_Land_Rover  = 40,
        ecommand_1A_____9D_Jaguar_Land_Rover  = 41,
        ecommand_1A_____87_Jaguar_Land_Rover  = 42,
    
    }enumCommand_Jaguar_Land_Rover;
    
    
    typedef enum _enumReaddtccommandlist_Jaguar_Land_Rover{
        ereaddtccommandlist_UNKNOWN_Jaguar_Land_Rover   = 0,
        ereaddtccommandlist_03_____19_____02_____AF_____00_____00_____00_____00_PERMANENT___1_Jaguar_Land_Rover  = 1,
        ereaddtccommandlist_07_CONFIRMED___2_Jaguar_Land_Rover  = 2,
        ereaddtccommandlist_01_____03_STORED___03_____13_____02_____00_PERMANENT___03_____13_____12_____FE_CURRENT_____TRIP___03_____13_____12_____FE_PREVIOUS_____TRIP___3_Jaguar_Land_Rover  = 3,
        ereaddtccommandlist_18_____02_____FF_____FF___4_Jaguar_Land_Rover  = 4,
        ereaddtccommandlist_18_____00_____80_____00___5_Jaguar_Land_Rover  = 5,
        ereaddtccommandlist_A0_____00___6_Jaguar_Land_Rover  = 6,
        ereaddtccommandlist_12_____05_____14_____00___12_____05_____14_____01___7_Jaguar_Land_Rover  = 7,
        ereaddtccommandlist_12_____05_____14_____00___12_____05_____14_____01___8_Jaguar_Land_Rover  = 8,
        ereaddtccommandlist_04_____01___9_Jaguar_Land_Rover  = 9,
    
    }enumReaddtccommandlist_Jaguar_Land_Rover;
    
    
    typedef enum _enumCommandlist_Jaguar_Land_Rover{
        ecommandlist_UNKNOWN_Jaguar_Land_Rover   = 0,
        ecommandlist_03_____22_____F1_____03_____00_____00_____00_____00_Jaguar_Land_Rover  = 1,
        ecommandlist_04_____14_____FF_____FF_____FF_____00_____00_____00_Jaguar_Land_Rover  = 2,
        ecommandlist_09_Jaguar_Land_Rover  = 3,
        ecommandlist_05_Jaguar_Land_Rover  = 4,
        ecommandlist_02_____10_____02_Jaguar_Land_Rover  = 5,
        ecommandlist_01_____04___01_____14_Jaguar_Land_Rover  = 6,
        ecommandlist_81_Jaguar_Land_Rover  = 7,
        ecommandlist_14_____FF_____FF_Jaguar_Land_Rover  = 8,
        ecommandlist_10_____87_Jaguar_Land_Rover  = 9,
        ecommandlist_14_____80_____00_Jaguar_Land_Rover  = 10,
        ecommandlist_10_____81_Jaguar_Land_Rover  = 11,
        ecommandlist_12_____04_____00_Jaguar_Land_Rover  = 12,
        ecommandlist_12_____04_____05___12_____04_____A0_Jaguar_Land_Rover  = 13,
        ecommandlist_19_____04_____00_Jaguar_Land_Rover  = 14,
        ecommandlist_00_Jaguar_Land_Rover  = 15,
        ecommandlist_1A_____9A___1A_____9B___1A_____9C___1A_____9D___1A_____87_Jaguar_Land_Rover  = 16,
    
    }enumCommandlist_Jaguar_Land_Rover;
    
    
    typedef enum _enumEcuinfotype_Jaguar_Land_Rover{
        eecuinfotype_UNKNOWN_Jaguar_Land_Rover   = 0,
    
    }enumEcuinfotype_Jaguar_Land_Rover;
    
    
    typedef enum _enumDtcreadtype_Jaguar_Land_Rover{
        edtcreadtype_UNKNOWN_Jaguar_Land_Rover   = 0,
        edtcreadtype_READDTCTYPE_ID0001_Jaguar_Land_Rover  = 1,
    
    }enumDtcreadtype_Jaguar_Land_Rover;
    
    
    typedef enum _enumLookuptable_Jaguar_Land_Rover{
        elookuptable_UNKNOWN_Jaguar_Land_Rover   = 0,
    
    }enumLookuptable_Jaguar_Land_Rover;
    
    
    typedef enum _enumMessageid_Jaguar_Land_Rover{
        emessageid_UNKNOWN_Jaguar_Land_Rover   = 0,
        emessageid_LANGJAG_RLM_CAN_001_Jaguar_Land_Rover  = 1,
        emessageid_LANGJAG_AAM_CAN_001_Jaguar_Land_Rover  = 2,
        emessageid_LANGJAG_AAM_CAN_002_Jaguar_Land_Rover  = 3,
        emessageid_LANGJAG_ABS_CAN_001_Jaguar_Land_Rover  = 4,
        emessageid_LANGJAG_ACM_CAN_001_Jaguar_Land_Rover  = 5,
        emessageid_LANGJAG_ACM_CAN_002_Jaguar_Land_Rover  = 6,
        emessageid_LANGJAG_AHCM_CAN_001_Jaguar_Land_Rover  = 7,
        emessageid_LANGJAG_AHCM_CAN_002_Jaguar_Land_Rover  = 8,
        emessageid_LANGJAG_AHU_CAN_001_Jaguar_Land_Rover  = 9,
        emessageid_LANGJAG_APIM_CAN_001_Jaguar_Land_Rover  = 10,
        emessageid_LANGJAG_APIM_CAN_002_Jaguar_Land_Rover  = 11,
        emessageid_LANGJAG_ARCM_CAN_001_Jaguar_Land_Rover  = 12,
        emessageid_LANGJAG_ARCM_CAN_002_Jaguar_Land_Rover  = 13,
        emessageid_LANGJAG_ATCM_CAN_001_Jaguar_Land_Rover  = 14,
        emessageid_LANGJAG_ATCM_CAN_002_Jaguar_Land_Rover  = 15,
        emessageid_LANGJAG_AUCM_CAN_001_Jaguar_Land_Rover  = 16,
        emessageid_LANGJAG_AUCM_CAN_002_Jaguar_Land_Rover  = 17,
        emessageid_LANGJAG_AWDCM_CAN_001_Jaguar_Land_Rover  = 18,
        emessageid_LANGJAG_BCM_CAN_001_Jaguar_Land_Rover  = 19,
        emessageid_LANGJAG_BCM_CAN_002_Jaguar_Land_Rover  = 20,
        emessageid_LANGJAG_BCM_CAN_003_Jaguar_Land_Rover  = 21,
        emessageid_LANGJAG_BCMB_CAN_001_Jaguar_Land_Rover  = 22,
        emessageid_LANGJAG_BPM_CAN_001_Jaguar_Land_Rover  = 23,
        emessageid_LANGJAG_CAV_CAN_001_Jaguar_Land_Rover  = 24,
        emessageid_LANGJAG_CCM_CAN_001_Jaguar_Land_Rover  = 25,
        emessageid_LANGJAG_CCM_CAN_002_Jaguar_Land_Rover  = 26,
        emessageid_LANGJAG_CDP_CAN_001_Jaguar_Land_Rover  = 27,
        emessageid_LANGJAG_CDP_CAN_002_Jaguar_Land_Rover  = 28,
        emessageid_LANGJAG_CHCM_CAN_001_Jaguar_Land_Rover  = 29,
        emessageid_LANGJAG_CHCMB_CAN_001_Jaguar_Land_Rover  = 30,
        emessageid_LANGJAG_DABM_CAN_001_Jaguar_Land_Rover  = 31,
        emessageid_LANGJAG_DABM_CAN_002_Jaguar_Land_Rover  = 32,
        emessageid_LANGJAG_DACMC_CAN_001_Jaguar_Land_Rover  = 33,
        emessageid_LANGJAG_DACMC_CAN_002_Jaguar_Land_Rover  = 34,
        emessageid_LANGJAG_DCSM_CAN_001_Jaguar_Land_Rover  = 35,
        emessageid_LANGJAG_DCSM_CAN_002_Jaguar_Land_Rover  = 36,
        emessageid_LANGJAG_DDM_CAN_001_Jaguar_Land_Rover  = 37,
        emessageid_LANGJAG_DSM_CAN_001_Jaguar_Land_Rover  = 38,
        emessageid_LANGJAG_DSM_CAN_002_Jaguar_Land_Rover  = 39,
        emessageid_LANGJAG_FACP_CAN_001_Jaguar_Land_Rover  = 40,
        emessageid_LANGJAG_FCDIM_CAN_001_Jaguar_Land_Rover  = 41,
        emessageid_LANGJAG_FCDIM_CAN_002_Jaguar_Land_Rover  = 42,
        emessageid_LANGJAG_FCIM_CAN_001_Jaguar_Land_Rover  = 43,
        emessageid_LANGJAG_FCIMB_CAN_001_Jaguar_Land_Rover  = 44,
        emessageid_LANGJAG_FCIMC_CAN_001_Jaguar_Land_Rover  = 45,
        emessageid_LANGJAG_FEM_CAN_001_Jaguar_Land_Rover  = 46,
        emessageid_LANGJAG_FEM_CAN_002_Jaguar_Land_Rover  = 47,
        emessageid_LANGJAG_FEM_CAN_003_Jaguar_Land_Rover  = 48,
        emessageid_LANGJAG_FLM_CAN_001_Jaguar_Land_Rover  = 49,
        emessageid_LANGJAG_FTCM_CAN_001_Jaguar_Land_Rover  = 50,
        emessageid_LANGJAG_FTCM_CAN_002_Jaguar_Land_Rover  = 51,
        emessageid_LANGJAG_FTCMB_CAN_001_Jaguar_Land_Rover  = 52,
        emessageid_LANGJAG_GPSM_CAN_001_Jaguar_Land_Rover  = 53,
        emessageid_LANGJAG_GSM_CAN_001_Jaguar_Land_Rover  = 54,
        emessageid_LANGJAG_GSMB_CAN_001_Jaguar_Land_Rover  = 55,
        emessageid_LANGJAG_GWM_CAN_001_Jaguar_Land_Rover  = 56,
        emessageid_LANGJAG_GWM_CAN_002_Jaguar_Land_Rover  = 57,
        emessageid_LANGJAG_HCM_CAN_001_Jaguar_Land_Rover  = 58,
        emessageid_LANGJAG_HCMB_CAN_001_Jaguar_Land_Rover  = 59,
        emessageid_LANGJAG_HUD_CAN_001_Jaguar_Land_Rover  = 60,
        emessageid_LANGJAG_HVAC_CAN_001_Jaguar_Land_Rover  = 61,
        emessageid_LANGJAG_HVAC_CAN_002_Jaguar_Land_Rover  = 62,
        emessageid_LANGJAG_ICM_CAN_001_Jaguar_Land_Rover  = 63,
        emessageid_LANGJAG_ICM_CAN_002_Jaguar_Land_Rover  = 64,
        emessageid_LANGJAG_ICS_CAN_001_Jaguar_Land_Rover  = 65,
        emessageid_LANGJAG_IPC_CAN_001_Jaguar_Land_Rover  = 66,
        emessageid_LANGJAG_IPC_CAN_002_Jaguar_Land_Rover  = 67,
        emessageid_LANGJAG_IPC_CAN_003_Jaguar_Land_Rover  = 68,
        emessageid_LANGJAG_IPC_CAN_004_Jaguar_Land_Rover  = 69,
        emessageid_LANGJAG_IPMB_CAN_001_Jaguar_Land_Rover  = 70,
        emessageid_LANGJAG_NCM_CAN_001_Jaguar_Land_Rover  = 71,
        emessageid_LANGJAG_NCM_CAN_002_Jaguar_Land_Rover  = 72,
        emessageid_LANGJAG_NCM_CAN_003_Jaguar_Land_Rover  = 73,
        emessageid_LANGJAG_OCS_CAN_001_Jaguar_Land_Rover  = 74,
        emessageid_LANGJAG_OCS_CAN_002_Jaguar_Land_Rover  = 75,
        emessageid_LANGJAG_PAM_CAN_001_Jaguar_Land_Rover  = 76,
        emessageid_LANGJAG_PAM_CAN_002_Jaguar_Land_Rover  = 77,
        emessageid_LANGJAG_PAM_CAN_003_Jaguar_Land_Rover  = 78,
        emessageid_LANGJAG_PBM_CAN_001_Jaguar_Land_Rover  = 79,
        emessageid_LANGJAG_PBM_CAN_002_Jaguar_Land_Rover  = 80,
        emessageid_LANGJAG_PBM_CAN_003_Jaguar_Land_Rover  = 81,
        emessageid_LANGJAG_PCM_CAN_001_Jaguar_Land_Rover  = 82,
        emessageid_LANGJAG_PCM_CAN_002_Jaguar_Land_Rover  = 83,
        emessageid_LANGJAG_PDM_CAN_001_Jaguar_Land_Rover  = 84,
        emessageid_LANGJAG_PSCM_CAN_001_Jaguar_Land_Rover  = 85,
        emessageid_LANGJAG_PSM_CAN_001_Jaguar_Land_Rover  = 86,
        emessageid_LANGJAG_PSM_CAN_002_Jaguar_Land_Rover  = 87,
        emessageid_LANGJAG_RBM_CAN_001_Jaguar_Land_Rover  = 88,
        emessageid_LANGJAG_RBM_CAN_002_Jaguar_Land_Rover  = 89,
        emessageid_LANGJAG_RCM_CAN_001_Jaguar_Land_Rover  = 90,
        emessageid_LANGJAG_RCM_CAN_002_Jaguar_Land_Rover  = 91,
        emessageid_LANGJAG_RDCM_CAN_001_Jaguar_Land_Rover  = 92,
        emessageid_LANGJAG_RDCM_CAN_002_Jaguar_Land_Rover  = 93,
        emessageid_LANGJAG_RDUM_CAN_001_Jaguar_Land_Rover  = 94,
        emessageid_LANGJAG_RDUM_CAN_002_Jaguar_Land_Rover  = 95,
        emessageid_LANGJAG_REM_CAN_001_Jaguar_Land_Rover  = 96,
        emessageid_LANGJAG_REM_CAN_002_Jaguar_Land_Rover  = 97,
        emessageid_LANGJAG_RFA_CAN_001_Jaguar_Land_Rover  = 98,
        emessageid_LANGJAG_RGTM_CAN_001_Jaguar_Land_Rover  = 99,
        emessageid_LANGJAG_RGTMB_CAN_001_Jaguar_Land_Rover  = 100,
        emessageid_LANGJAG_RHVAC_CAN_001_Jaguar_Land_Rover  = 101,
        emessageid_LANGJAG_RHVAC_CAN_002_Jaguar_Land_Rover  = 102,
        emessageid_LANGJAG_RLSM_CAN_001_Jaguar_Land_Rover  = 103,
        emessageid_LANGJAG_RRSM_CAN_001_Jaguar_Land_Rover  = 104,
        emessageid_LANGJAG_SARM_CAN_001_Jaguar_Land_Rover  = 105,
        emessageid_LANGJAG_SASM_CAN_001_Jaguar_Land_Rover  = 106,
        emessageid_LANGJAG_SASM_CAN_002_Jaguar_Land_Rover  = 107,
        emessageid_LANGJAG_SCME_CAN_001_Jaguar_Land_Rover  = 108,
        emessageid_LANGJAG_SCMF_CAN_001_Jaguar_Land_Rover  = 109,
        emessageid_LANGJAG_SODL_CAN_001_Jaguar_Land_Rover  = 110,
        emessageid_LANGJAG_SODR_CAN_001_Jaguar_Land_Rover  = 111,
        emessageid_LANGJAG_SPMA_CAN_001_Jaguar_Land_Rover  = 112,
        emessageid_LANGJAG_SPMB_CAN_001_Jaguar_Land_Rover  = 113,
        emessageid_LANGJAG_SPRM_CAN_001_Jaguar_Land_Rover  = 114,
        emessageid_LANGJAG_SRM_CAN_001_Jaguar_Land_Rover  = 115,
        emessageid_LANGJAG_SRM_CAN_002_Jaguar_Land_Rover  = 116,
        emessageid_LANGJAG_SUMB_CAN_001_Jaguar_Land_Rover  = 117,
        emessageid_LANGJAG_TCCM_CAN_001_Jaguar_Land_Rover  = 118,
        emessageid_LANGJAG_TCCM_CAN_002_Jaguar_Land_Rover  = 119,
        emessageid_LANGJAG_TCM_CAN_001_Jaguar_Land_Rover  = 120,
        emessageid_LANGJAG_TCM_CAN_002_Jaguar_Land_Rover  = 121,
        emessageid_LANGJAG_TCU_CAN_001_Jaguar_Land_Rover  = 122,
        emessageid_LANGJAG_TEL_CAN_001_Jaguar_Land_Rover  = 123,
        emessageid_LANGJAG_TEL_CAN_002_Jaguar_Land_Rover  = 124,
        emessageid_LANGJAG_TMC_CAN_001_Jaguar_Land_Rover  = 125,
        emessageid_LANGJAG_TPM_CAN_001_Jaguar_Land_Rover  = 126,
        emessageid_LANGJAG_TPM_CAN_002_Jaguar_Land_Rover  = 127,
        emessageid_LANGJAG_TPM_CAN_003_Jaguar_Land_Rover  = 128,
        emessageid_LANGJAG_TRM_CAN_001_Jaguar_Land_Rover  = 129,
        emessageid_LANGJAG_TVM_CAN_001_Jaguar_Land_Rover  = 130,
        emessageid_LANGJAG_TVM_CAN_002_Jaguar_Land_Rover  = 131,
        emessageid_LANGJAG_VDM_CAN_001_Jaguar_Land_Rover  = 132,
        emessageid_LANGJAG_VIM_CAN_001_Jaguar_Land_Rover  = 133,
        emessageid_LANGJAG_VIM_CAN_002_Jaguar_Land_Rover  = 134,
        emessageid_LANGJAG_TCM_BOSCH_001_Jaguar_Land_Rover  = 135,
        emessageid_LANGJAG_PCM_KW2000_001_Jaguar_Land_Rover  = 136,
        emessageid_LANGJAG_ABS_KW2000_001_Jaguar_Land_Rover  = 137,
        emessageid_LANGJAG_ABS_KW2000_002_Jaguar_Land_Rover  = 138,
        emessageid_LANGJAG_ACC_KW2000_001_Jaguar_Land_Rover  = 139,
        emessageid_LANGJAG_ARM_KW2000_001_Jaguar_Land_Rover  = 140,
        emessageid_LANGJAG_BPM_KW2000_001_Jaguar_Land_Rover  = 141,
        emessageid_LANGJAG_PCM_KW2000_002_Jaguar_Land_Rover  = 142,
        emessageid_LANGJAG_PCM_KW2000_003_Jaguar_Land_Rover  = 143,
        emessageid_LANGJAG_IP_KW2000_001_Jaguar_Land_Rover  = 144,
        emessageid_LANGJAG_TCM_KW2000_001_Jaguar_Land_Rover  = 145,
        emessageid_LANGJAG_ABS_DS2_001_Jaguar_Land_Rover  = 146,
        emessageid_LANGJAG_ADHLS_DS2_001_Jaguar_Land_Rover  = 147,
        emessageid_LANGJAG_ARM_DS2_001_Jaguar_Land_Rover  = 148,
        emessageid_LANGJAG_ASU_DS2_001_Jaguar_Land_Rover  = 149,
        emessageid_LANGJAG_ATC_DS2_001_Jaguar_Land_Rover  = 150,
        emessageid_LANGJAG_BPM_DS2_001_Jaguar_Land_Rover  = 151,
        emessageid_LANGJAG_CPM_DS2_001_Jaguar_Land_Rover  = 152,
        emessageid_LANGJAG_DISP_DS2_001_Jaguar_Land_Rover  = 153,
        emessageid_LANGJAG_DSM_DS2_001_Jaguar_Land_Rover  = 154,
        emessageid_LANGJAG_DSP_DS2_001_Jaguar_Land_Rover  = 155,
        emessageid_LANGJAG_FETM_DS2_001_Jaguar_Land_Rover  = 156,
        emessageid_LANGJAG_HID_DS2_001_Jaguar_Land_Rover  = 157,
        emessageid_LANGJAG_HID_DS2_002_Jaguar_Land_Rover  = 158,
        emessageid_LANGJAG_IP_DS2_001_Jaguar_Land_Rover  = 159,
        emessageid_LANGJAG_LCM_DS2_001_Jaguar_Land_Rover  = 160,
        emessageid_LANGJAG_MFD_DS2_001_Jaguar_Land_Rover  = 161,
        emessageid_LANGJAG_MFSW_DS2_001_Jaguar_Land_Rover  = 162,
        emessageid_LANGJAG_NAV_DS2_001_Jaguar_Land_Rover  = 163,
        emessageid_LANGJAG_NAV_DS2_002_Jaguar_Land_Rover  = 164,
        emessageid_LANGJAG_PAM_DS2_001_Jaguar_Land_Rover  = 165,
        emessageid_LANGJAG_PATS_DS2_001_Jaguar_Land_Rover  = 166,
        emessageid_LANGJAG_PATS_DS2_002_Jaguar_Land_Rover  = 167,
        emessageid_LANGJAG_PCM_DS2_001_Jaguar_Land_Rover  = 168,
        emessageid_LANGJAG_RAIN_DS2_001_Jaguar_Land_Rover  = 169,
        emessageid_LANGJAG_SASM_DS2_001_Jaguar_Land_Rover  = 170,
        emessageid_LANGJAG_SCLM_DS2_001_Jaguar_Land_Rover  = 171,
        emessageid_LANGJAG_TBOX_DS2_001_Jaguar_Land_Rover  = 172,
        emessageid_LANGJAG_TCM_DS2_001_Jaguar_Land_Rover  = 173,
        emessageid_LANGJAG_TCM_DS2_002_Jaguar_Land_Rover  = 174,
        emessageid_LANGJAG_TPM_DS2_001_Jaguar_Land_Rover  = 175,
        emessageid_LANGJAG_VACM_DS2_001_Jaguar_Land_Rover  = 176,
        emessageid_LANGJAG_VIDEO_DS2_001_Jaguar_Land_Rover  = 177,
        emessageid_LANGJAG_LCM_L_DS2_DEF_001_Jaguar_Land_Rover  = 178,
        emessageid_LANGJAG_LCM_R_DS2_DEF_001_Jaguar_Land_Rover  = 179,
        emessageid_LANGJAG_BPM_DS2_DEF_001_Jaguar_Land_Rover  = 180,
        emessageid_LANGJAG_DSM_DS2_DEF_001_Jaguar_Land_Rover  = 181,
        emessageid_LANGJAG_HVAC_DS2_DEF_001_Jaguar_Land_Rover  = 182,
        emessageid_LANGJAG_LCM_DS2_DEF_001_Jaguar_Land_Rover  = 183,
        emessageid_LANGJAG_MFSW_DS2_DEF_001_Jaguar_Land_Rover  = 184,
        emessageid_LANGJAG_PAM_DS2_DEF_001_Jaguar_Land_Rover  = 185,
        emessageid_LANGJAG_SCLM_DS2_DEF_001_Jaguar_Land_Rover  = 186,
        emessageid_LANGJAG_RCM_DS2_DEF_001_Jaguar_Land_Rover  = 187,
        emessageid_LANGJAG_RAIN_DS2_DEF_001_Jaguar_Land_Rover  = 188,
        emessageid_LANGJAG_PCM_KW2000_004_Jaguar_Land_Rover  = 189,
    
    }enumMessageid_Jaguar_Land_Rover;
    
    
    typedef enum _enumSystem_Jaguar_Land_Rover{
        esystem_UNKNOWN_Jaguar_Land_Rover   = 0,
        esystem_PCM_Jaguar_Land_Rover  = 1,
        esystem_TCM_Jaguar_Land_Rover  = 2,
        esystem_ABS_Jaguar_Land_Rover  = 3,
        esystem_ACC_Jaguar_Land_Rover  = 4,
        esystem_ARM_Jaguar_Land_Rover  = 5,
        esystem_BPM_Jaguar_Land_Rover  = 6,
        esystem_IP_Jaguar_Land_Rover  = 7,
        esystem_PATS_Jaguar_Land_Rover  = 8,
        esystem_ADHLS_Jaguar_Land_Rover  = 9,
        esystem_ASU_Jaguar_Land_Rover  = 10,
        esystem_ATC_Jaguar_Land_Rover  = 11,
        esystem_CPM_Jaguar_Land_Rover  = 12,
        esystem_DISP_Jaguar_Land_Rover  = 13,
        esystem_DSM_Jaguar_Land_Rover  = 14,
        esystem_DSP_Jaguar_Land_Rover  = 15,
        esystem_FETM_Jaguar_Land_Rover  = 16,
        esystem_HID_Jaguar_Land_Rover  = 17,
        esystem_LCM_Jaguar_Land_Rover  = 18,
        esystem_MFD_Jaguar_Land_Rover  = 19,
        esystem_MFSW_Jaguar_Land_Rover  = 20,
        esystem_NAV_Jaguar_Land_Rover  = 21,
        esystem_PAM_Jaguar_Land_Rover  = 22,
        esystem_RAIN_Jaguar_Land_Rover  = 23,
        esystem_SASM_Jaguar_Land_Rover  = 24,
        esystem_SCLM_Jaguar_Land_Rover  = 25,
        esystem_TBOX_Jaguar_Land_Rover  = 26,
        esystem_TPM_Jaguar_Land_Rover  = 27,
        esystem_VACM_Jaguar_Land_Rover  = 28,
        esystem_VIDEO_Jaguar_Land_Rover  = 29,
        esystem_RLM_Jaguar_Land_Rover  = 30,
        esystem_BCM_Jaguar_Land_Rover  = 31,
        esystem_HVAC_Jaguar_Land_Rover  = 32,
        esystem_IPC_Jaguar_Land_Rover  = 33,
        esystem_PBM_Jaguar_Land_Rover  = 34,
        esystem_TCCM_Jaguar_Land_Rover  = 35,
        esystem_VDM_Jaguar_Land_Rover  = 36,
        esystem_RCM_Jaguar_Land_Rover  = 37,
        esystem_AAM_Jaguar_Land_Rover  = 38,
        esystem_ACM_Jaguar_Land_Rover  = 39,
        esystem_TEL_Jaguar_Land_Rover  = 40,
        esystem_FEM_Jaguar_Land_Rover  = 41,
        esystem_DACMC_Jaguar_Land_Rover  = 42,
        esystem_FLM_Jaguar_Land_Rover  = 43,
        esystem_RDCM_Jaguar_Land_Rover  = 44,
        esystem_REM_Jaguar_Land_Rover  = 45,
        esystem_SRM_Jaguar_Land_Rover  = 46,
        esystem_CCM_Jaguar_Land_Rover  = 47,
        esystem_ATCM_Jaguar_Land_Rover  = 48,
        esystem_TMC_Jaguar_Land_Rover  = 49,
        esystem_TVM_Jaguar_Land_Rover  = 50,
        esystem_DDM_Jaguar_Land_Rover  = 51,
        esystem_HCM_Jaguar_Land_Rover  = 52,
        esystem_PDM_Jaguar_Land_Rover  = 53,
        esystem_FCDIM_Jaguar_Land_Rover  = 54,
        esystem_ICM_Jaguar_Land_Rover  = 55,
        esystem_DABM_Jaguar_Land_Rover  = 56,
        esystem_NCM_Jaguar_Land_Rover  = 57,
        esystem_OCS_Jaguar_Land_Rover  = 58,
        esystem_TRM_Jaguar_Land_Rover  = 59,
        esystem_CDP_Jaguar_Land_Rover  = 60,
        esystem_GWM_Jaguar_Land_Rover  = 61,
        esystem_LCM_L_Jaguar_Land_Rover  = 62,
        esystem_LCM_R_Jaguar_Land_Rover  = 63,
        esystem_VIM_Jaguar_Land_Rover  = 64,
        esystem_RDUM_Jaguar_Land_Rover  = 65,
        esystem_RHVAC_Jaguar_Land_Rover  = 66,
        esystem_DCSM_Jaguar_Land_Rover  = 67,
        esystem_RBM_Jaguar_Land_Rover  = 68,
        esystem_ARCM_Jaguar_Land_Rover  = 69,
        esystem_SUMB_Jaguar_Land_Rover  = 70,
        esystem_GSM_Jaguar_Land_Rover  = 71,
        esystem_FACP_Jaguar_Land_Rover  = 72,
        esystem_RFA_Jaguar_Land_Rover  = 73,
        esystem_BCMB_Jaguar_Land_Rover  = 74,
        esystem_SCME_Jaguar_Land_Rover  = 75,
        esystem_APIM_Jaguar_Land_Rover  = 76,
        esystem_ICS_Jaguar_Land_Rover  = 77,
        esystem_SARM_Jaguar_Land_Rover  = 78,
        esystem_SODL_Jaguar_Land_Rover  = 79,
        esystem_SODR_Jaguar_Land_Rover  = 80,
        esystem_PSM_Jaguar_Land_Rover  = 81,
        esystem_FTCM_Jaguar_Land_Rover  = 82,
        esystem_HCMB_Jaguar_Land_Rover  = 83,
        esystem_IPMB_Jaguar_Land_Rover  = 84,
        esystem_SCMF_Jaguar_Land_Rover  = 85,
        esystem_FCIM_Jaguar_Land_Rover  = 86,
        esystem_FCIMB_Jaguar_Land_Rover  = 87,
        esystem_SPRM_Jaguar_Land_Rover  = 88,
        esystem_AHCM_Jaguar_Land_Rover  = 89,
        esystem_RGTM_Jaguar_Land_Rover  = 90,
        esystem_SPMA_Jaguar_Land_Rover  = 91,
        esystem_SPMB_Jaguar_Land_Rover  = 92,
        esystem_RLSM_Jaguar_Land_Rover  = 93,
        esystem_RRSM_Jaguar_Land_Rover  = 94,
        esystem_AHU_Jaguar_Land_Rover  = 95,
        esystem_PSCM_Jaguar_Land_Rover  = 96,
        esystem_GSMB_Jaguar_Land_Rover  = 97,
        esystem_CHCM_Jaguar_Land_Rover  = 98,
        esystem_FTCMB_Jaguar_Land_Rover  = 99,
        esystem_CHCMB_Jaguar_Land_Rover  = 100,
        esystem_FCIMC_Jaguar_Land_Rover  = 101,
        esystem_RGTMB_Jaguar_Land_Rover  = 102,
        esystem_TCU_Jaguar_Land_Rover  = 103,
        esystem_CAV_Jaguar_Land_Rover  = 104,
        esystem_AWDCM_Jaguar_Land_Rover  = 105,
        esystem_GPSM_Jaguar_Land_Rover  = 106,
        esystem_AUCM_Jaguar_Land_Rover  = 107,
        esystem_HUD_Jaguar_Land_Rover  = 108,
        esystem_KVM_Jaguar_Land_Rover  = 109,
        esystem_ACE_Jaguar_Land_Rover  = 110,
        esystem_RDCSM_Jaguar_Land_Rover  = 111,
        esystem_ADCM_Jaguar_Land_Rover  = 112,
        esystem_EPB_Jaguar_Land_Rover  = 113,
        esystem_GEM_Jaguar_Land_Rover  = 114,
        esystem_ADS_Jaguar_Land_Rover  = 115,
        esystem_ADRC_Jaguar_Land_Rover  = 116,
        esystem_IPK_Jaguar_Land_Rover  = 117,
        esystem_MCC_Jaguar_Land_Rover  = 118,
        esystem_ICE_Jaguar_Land_Rover  = 119,
        esystem_AMP_Jaguar_Land_Rover  = 120,
        esystem_ISM_Jaguar_Land_Rover  = 121,
        esystem_FSJB_Jaguar_Land_Rover  = 122,
        esystem_RSJB_Jaguar_Land_Rover  = 123,
        esystem_ICP_Jaguar_Land_Rover  = 124,
        esystem_CMM_Jaguar_Land_Rover  = 125,
        esystem_RATC_Jaguar_Land_Rover  = 126,
        esystem_RETM_Jaguar_Land_Rover  = 127,
        esystem_ADHLS_L_Jaguar_Land_Rover  = 128,
        esystem_ADHLS_R_Jaguar_Land_Rover  = 129,
        esystem_RSM_Jaguar_Land_Rover  = 130,
        esystem_TCMMB_Jaguar_Land_Rover  = 131,
        esystem_TCMZF_Jaguar_Land_Rover  = 132,
        esystem_SBC_Jaguar_Land_Rover  = 133,
        esystem_DHM_Jaguar_Land_Rover  = 134,
        esystem_PHM_Jaguar_Land_Rover  = 135,
        esystem_SLM_Jaguar_Land_Rover  = 136,
        esystem_SRS_Jaguar_Land_Rover  = 137,
    
    }enumSystem_Jaguar_Land_Rover;
    
    
    typedef enum _enumSubsystem_Jaguar_Land_Rover{
        esubsystem_UNKNOWN_Jaguar_Land_Rover   = 0,
        esubsystem_CPM_____COMBUSTION_____PREHEATER_____MODULE_Jaguar_Land_Rover  = 1,
    
    }enumSubsystem_Jaguar_Land_Rover;
    
    
    typedef enum _enumTiming_Jaguar_Land_Rover{
        etiming_UNKNOWN_Jaguar_Land_Rover   = 0,
        etiming_TWUP_HONDA_BOSCH_Jaguar_Land_Rover  = 1,
        etiming_TIMINGP_HONDA_BOSCH_Jaguar_Land_Rover  = 2,
        etiming_TIMINGW_HONDA_BOSCH_Jaguar_Land_Rover  = 3,
        etiming_KW1281DEFAULT_Jaguar_Land_Rover  = 4,
        etiming_TWUPGENERAL_Jaguar_Land_Rover  = 5,
        etiming_TIMINGP_NORMAL_Jaguar_Land_Rover  = 6,
        etiming_TIMINGW_NORMAL_Jaguar_Land_Rover  = 7,
        etiming_TWUP_BMW_KW_Jaguar_Land_Rover  = 8,
        etiming_TIMINGP_BMW_KW_Jaguar_Land_Rover  = 9,
        etiming_TIMINGW_BMW_KW_Jaguar_Land_Rover  = 10,
        etiming_TWUP_BMW_DS2_Jaguar_Land_Rover  = 11,
        etiming_TIMINGP_BMW_DS2_Jaguar_Land_Rover  = 12,
        etiming_TIMINGW_BMW_DS2_Jaguar_Land_Rover  = 13,
        etiming_TIMINGP_CHRYSLER_CAN_Jaguar_Land_Rover  = 14,
        etiming_TIMINGP_CHRYSLER_CAN_C_UDS_Jaguar_Land_Rover  = 15,
        etiming_TIMINGP_CHRYSLER_CAN_I_UDS_Jaguar_Land_Rover  = 16,
        etiming_TIMINGP_CHRYSLER_CCD_Jaguar_Land_Rover  = 17,
        etiming_TIMINGP_CHRYSLER_CCD2_Jaguar_Land_Rover  = 18,
        etiming_TIMINGP_CHRYSLER_KW2000_Jaguar_Land_Rover  = 19,
        etiming_TIMINGP_CHRYSLER_KWFB_Jaguar_Land_Rover  = 20,
        etiming_TIMINGP_CHRYSLER_MB_ISO_Jaguar_Land_Rover  = 21,
        etiming_TIMINGP_CHRYSLER_MUT_Jaguar_Land_Rover  = 22,
        etiming_TIMINGP_CHRYSLER_SCI_Jaguar_Land_Rover  = 23,
        etiming_TIMINGP_CHRYSLER_VPW_Jaguar_Land_Rover  = 24,
        etiming_TIMINGP_FORD_CAN_Jaguar_Land_Rover  = 25,
        etiming_TIMINGP_FORD_CAN_UDS_Jaguar_Land_Rover  = 26,
        etiming_TIMINGP_FORD_ISO9141_Jaguar_Land_Rover  = 27,
        etiming_TIMINGP_FORD_MCAN_Jaguar_Land_Rover  = 28,
        etiming_TIMINGP_FORD_MCAN_____UDS_Jaguar_Land_Rover  = 29,
        etiming_TIMINGP_FORD_PWM_Jaguar_Land_Rover  = 30,
        etiming_TIMINGP_FORD_UBP_Jaguar_Land_Rover  = 31,
        etiming_TIMINGP_GM_ALDL_Jaguar_Land_Rover  = 32,
        etiming_TIMINGP_GM_CAN_Jaguar_Land_Rover  = 33,
        etiming_TIMINGP_GM_GMLAN_Jaguar_Land_Rover  = 34,
        etiming_TIMINGP_GM_KW_Jaguar_Land_Rover  = 35,
        etiming_TIMINGP_GM_SDL_Jaguar_Land_Rover  = 36,
        etiming_TIMINGP_GM_SWCAN_Jaguar_Land_Rover  = 37,
        etiming_TIMINGP_GM_VPW_Jaguar_Land_Rover  = 38,
        etiming_TIMINGP_HONDA_92HM_Jaguar_Land_Rover  = 39,
        etiming_TIMINGP_HONDA_95HM_Jaguar_Land_Rover  = 40,
        etiming_TIMINGP_HONDA_CAN_Jaguar_Land_Rover  = 41,
        etiming_TIMINGP_HONDA_H99B_Jaguar_Land_Rover  = 42,
        etiming_TIMINGP_HONDA_KW2000_Jaguar_Land_Rover  = 43,
        etiming_TIMINGP_TOYOTA_CAN_Jaguar_Land_Rover  = 44,
        etiming_TIMINGP_TOYOTA_ISO9141_Jaguar_Land_Rover  = 45,
        etiming_TIMINGP_TOYOTA_KW2000_Jaguar_Land_Rover  = 46,
        etiming_TIMINGP_TOYOTA_VPW_Jaguar_Land_Rover  = 47,
        etiming_TIMINGW_CHRYSLER_MB_ISO_Jaguar_Land_Rover  = 48,
        etiming_TIMINGW_CHRYSLER_MUT_Jaguar_Land_Rover  = 49,
        etiming_TIMINGW_FORD_ISO9141_Jaguar_Land_Rover  = 50,
        etiming_TIMINGW_GM_KW_Jaguar_Land_Rover  = 51,
        etiming_TIMINGW_TOYOTA_ISO9141_Jaguar_Land_Rover  = 52,
        etiming_TWUP_CHRYSLER_KW2000_Jaguar_Land_Rover  = 53,
        etiming_TWUP_CHRYSLER_KWFB_Jaguar_Land_Rover  = 54,
        etiming_TWUP_FORD_UBP_Jaguar_Land_Rover  = 55,
        etiming_TWUP_GM_KW_Jaguar_Land_Rover  = 56,
        etiming_TWUP_HONDA_92HM_Jaguar_Land_Rover  = 57,
        etiming_TWUP_HONDA_95HM_Jaguar_Land_Rover  = 58,
        etiming_TWUP_HONDA_H99B_Jaguar_Land_Rover  = 59,
        etiming_TWUP_HONDA_KW2000_Jaguar_Land_Rover  = 60,
        etiming_TWUP_TOYOTA_KW2000_10400_Jaguar_Land_Rover  = 61,
        etiming_TWUP_TOYOTA_KW2000_9600_Jaguar_Land_Rover  = 62,
        etiming_TWUPHONDA_00_Jaguar_Land_Rover  = 63,
        etiming_TIMINGP_CANNORMAL_Jaguar_Land_Rover  = 64,
        etiming_TWUP_GM_KW9600_Jaguar_Land_Rover  = 65,
        etiming_TIMINGP_VOLVO_D2_Jaguar_Land_Rover  = 66,
        etiming_TIMINGP_VOLVO_GGD_Jaguar_Land_Rover  = 67,
        etiming_TIMINGP_VOLVO_KW_Jaguar_Land_Rover  = 68,
        etiming_TIMINGW_VOLVO_D2_Jaguar_Land_Rover  = 69,
        etiming_TWUP_VOLVO_KW_Jaguar_Land_Rover  = 70,
        etiming_TWUP_VOLVO_GGD_Jaguar_Land_Rover  = 71,
        etiming_TWUP_VOLVO_D2_Jaguar_Land_Rover  = 72,
        etiming_TIMINGW_VOLVO_GGD_Jaguar_Land_Rover  = 73,
        etiming_TIMINGW_VOLVO_KW_Jaguar_Land_Rover  = 74,
        etiming_TIMINGP_BMW_KW2000_Jaguar_Land_Rover  = 75,
        etiming_TIMINGP_MERCEDES_BENZ_CAN_Jaguar_Land_Rover  = 76,
        etiming_TIMINGP_MERCEDES_BENZ_CAN_UDS_Jaguar_Land_Rover  = 77,
        etiming_TIMINGP_NISSAN_DDL1_Jaguar_Land_Rover  = 78,
    
    }enumTiming_Jaguar_Land_Rover;
    
    
    typedef enum _enumErasetype_Jaguar_Land_Rover{
        eerasetype_UNKNOWN_Jaguar_Land_Rover   = 0,
        eerasetype_ERASETYPE_ID0002_Jaguar_Land_Rover  = 1,
    
    }enumErasetype_Jaguar_Land_Rover;
    
    
    typedef enum _enumModel_Jaguar_Land_Rover{
        emodel_UNKNOWN_Jaguar_Land_Rover   = 0,
        emodel_RANGE_____ROVER______38A__Jaguar_Land_Rover  = 1,
        emodel_DEFENDER_Jaguar_Land_Rover  = 2,
        emodel_DISCOVERY_____I_Jaguar_Land_Rover  = 3,
        emodel_DISCOVERY_____II_Jaguar_Land_Rover  = 4,
        emodel_FREELANDER_Jaguar_Land_Rover  = 5,
        emodel_RANGE_____ROVER_____NEW_Jaguar_Land_Rover  = 6,
        emodel_LR3_Jaguar_Land_Rover  = 7,
        emodel_LR2_Jaguar_Land_Rover  = 8,
        emodel_RANGE_____ROVER_____SPORT_Jaguar_Land_Rover  = 9,
        emodel_S_TYPE_Jaguar_Land_Rover  = 10,
        emodel_XF_Jaguar_Land_Rover  = 11,
        emodel_XJ_____SERIES_____NEW_Jaguar_Land_Rover  = 12,
        emodel_XK_____SERIES_____NEW_Jaguar_Land_Rover  = 13,
        emodel_X_TYPE_Jaguar_Land_Rover  = 14,
        emodel_LR4_Jaguar_Land_Rover  = 15,
        emodel_RANGE_____ROVER_____EVOQUE_Jaguar_Land_Rover  = 16,
        emodel_F_TYPE_Jaguar_Land_Rover  = 17,
        emodel_RANGE_____ROVER_____ALL_____NEW_Jaguar_Land_Rover  = 18,
        emodel_RANGE_____ROVER_Jaguar_Land_Rover  = 19,
        emodel_DISCOVERY_Jaguar_Land_Rover  = 20,
        emodel_XK_Jaguar_Land_Rover  = 21,
        emodel_XJ_____SERIES_Jaguar_Land_Rover  = 22,
        emodel_XKR_Jaguar_Land_Rover  = 23,
        emodel_XKR_S_Jaguar_Land_Rover  = 24,
        emodel_XJ_____PORTFOLIO_Jaguar_Land_Rover  = 25,
        emodel_XJ8_Jaguar_Land_Rover  = 26,
        emodel_XJR_Jaguar_Land_Rover  = 27,
        emodel_XKR_____PORTFOLIO_Jaguar_Land_Rover  = 28,
        emodel_XK8_Jaguar_Land_Rover  = 29,
        emodel_XJ_____SPORT_Jaguar_Land_Rover  = 30,
        emodel_XJ_Jaguar_Land_Rover  = 31,
        emodel_XJ6_Jaguar_Land_Rover  = 32,
        emodel_XJS_Jaguar_Land_Rover  = 33,
        emodel_XJ12_Jaguar_Land_Rover  = 34,
        emodel_RANGE_____ROVER_____CLASSIC_Jaguar_Land_Rover  = 35,
        emodel_XJ_____SERIES___________XJ6_____SEDAN_Jaguar_Land_Rover  = 36,
        emodel_XJ_____SERIES___________XJ8_Jaguar_Land_Rover  = 37,
        emodel_XK_____SERIES___________XK8_Jaguar_Land_Rover  = 38,
        emodel_XK_____SERIES___________XKR_Jaguar_Land_Rover  = 39,
    
    }enumModel_Jaguar_Land_Rover;
    
    
    typedef enum _enumEngine_Jaguar_Land_Rover{
        eengine_UNKNOWN_Jaguar_Land_Rover   = 0,
        eengine_V8______4_2L_Jaguar_Land_Rover  = 1,
        eengine_V6______3_0L_Jaguar_Land_Rover  = 2,
        eengine_V8______5_0L_Jaguar_Land_Rover  = 3,
        eengine_L4______2_0L_Jaguar_Land_Rover  = 4,
        eengine_L6______3_2L_Jaguar_Land_Rover  = 5,
        eengine_V6______4_0L_Jaguar_Land_Rover  = 6,
        eengine_V8______4_4L_Jaguar_Land_Rover  = 7,
        eengine_V6______2_5L_Jaguar_Land_Rover  = 8,
        eengine_V8______4_6L_Jaguar_Land_Rover  = 9,
        eengine_V8______4_0L_Jaguar_Land_Rover  = 10,
        eengine_L6______4_0L_Jaguar_Land_Rover  = 11,
        eengine_V12______6_0L_Jaguar_Land_Rover  = 12,
    
    }enumEngine_Jaguar_Land_Rover;
    

#endif