/******************************************************************************************************************
* Engineer    : automatic generated
* Date        : 9/29/2015
********************************************************************************************************************/

#ifndef __ENUMS_Global_H__
#define __ENUMS_Global_H__



    
    typedef enum _enumYear_Global{
        eyear_UNKNOWN_Global   = 0,
        eyear_1996_Global  = 16,
        eyear_1997_Global  = 17,
        eyear_1998_Global  = 18,
        eyear_1999_Global  = 19,
        eyear_2000_Global  = 20,
        eyear_2001_Global  = 21,
        eyear_2002_Global  = 22,
        eyear_2003_Global  = 23,
        eyear_2004_Global  = 24,
        eyear_2005_Global  = 25,
        eyear_2006_Global  = 26,
        eyear_2007_Global  = 27,
        eyear_2008_Global  = 28,
        eyear_2009_Global  = 29,
        eyear_2010_Global  = 30,
        eyear_2011_Global  = 31,
        eyear_2012_Global  = 32,
        eyear_2013_Global  = 33,
        eyear_2014_Global  = 34,
        eyear_2015_Global  = 35,
        eyear_OTHERS_Global  = 65534,
        eyear_MAX_Global  = 65535,
    
    }enumYear_Global;
    
    
    typedef enum _enumManufacturer_Global{
        emanufacturer_UNKNOWN_Global   = 0,
        emanufacturer_BMW_Global  = 1,
        emanufacturer_CHRYSLER_Global  = 2,
        emanufacturer_FORD_Global  = 3,
        emanufacturer_GM_Global  = 4,
        emanufacturer_HONDA_Global  = 5,
        emanufacturer_HYUNDAI_Global  = 6,
        emanufacturer_MAZDA_Global  = 10,
        emanufacturer_MERCEDES_BENZ_Global  = 11,
        emanufacturer_NISSAN_Global  = 12,
        emanufacturer_TOYOTA_Global  = 13,
        emanufacturer_VOLKSWAGEN_Global  = 14,
        emanufacturer_VOLVO_Global  = 15,
        emanufacturer_ISUZU_Global  = 16,
        emanufacturer_MITSUBISHI_Global  = 17,
        emanufacturer_SUBARU_Global  = 18,
        emanufacturer_SUZUKI_Global  = 19,
        emanufacturer_PORSCHE_Global  = 20,
        emanufacturer_OTHERS_Global  = 65534,
        emanufacturer_MAX_Global  = 65535,
        emanufacturer_GENERIC_Global  = 65535,
        emanufacturer_JAGUAR_____LAND_____ROVER_Global  = 21,
        emanufacturer_BYD_Global  = 22,
        emanufacturer_CHERY_Global  = 23,
        emanufacturer_DAIHATSU_Global  = 24,
        emanufacturer_SSANGYONG_Global  = 25,
        emanufacturer_ROVER_____GROUP_Global  = 26,
        emanufacturer_SAIC_Global  = 27,
        emanufacturer_FIAT_Global  = 28,
        emanufacturer_PEUGEOT_Global  = 29,
        emanufacturer_DAEWOO_Global  = 30,
        emanufacturer_LIFAN_Global  = 31,
        emanufacturer_FAW_Global  = 32,
        emanufacturer_MG_Global  = 33,
        emanufacturer_OPEL_Global  = 34,
        emanufacturer_RENAULT_Global  = 35,
        emanufacturer_MERCEDES_Global  = 11,
    
    }enumManufacturer_Global;
    
    
    typedef enum _enumMake_Global{
        emake_UNKNOWN_Global   = 0,
        emake_ACURA_Global  = 1,
        emake_AM_____GENERAL_Global  = 2,
        emake_AUDI_Global  = 3,
        emake_BMW_Global  = 4,
        emake_BUICK_Global  = 5,
        emake_CADILLAC_Global  = 6,
        emake_CHEVROLET_Global  = 7,
        emake_CHRYSLER_Global  = 8,
        emake_DAEWOO_Global  = 9,
        emake_DODGE_Global  = 10,
        emake_EAGLE_Global  = 11,
        emake_FORD_Global  = 12,
        emake_GEO_Global  = 13,
        emake_GMC_Global  = 14,
        emake_HONDA_Global  = 15,
        emake_HUMMER_Global  = 16,
        emake_HYUNDAI_Global  = 17,
        emake_INFINITI_Global  = 18,
        emake_JAGUAR_Global  = 19,
        emake_JEEP_Global  = 20,
        emake_KIA_Global  = 21,
        emake_LAND_____ROVER_Global  = 22,
        emake_LEXUS_Global  = 23,
        emake_LINCOLN_Global  = 24,
        emake_MAZDA_Global  = 25,
        emake_MERCEDES_BENZ_Global  = 26,
        emake_MERCURY_Global  = 27,
        emake_MINI_Global  = 28,
        emake_NISSAN_Global  = 29,
        emake_OLDSMOBILE_Global  = 30,
        emake_PLYMOUTH_Global  = 31,
        emake_PONTIAC_Global  = 32,
        emake_RAM_Global  = 33,
        emake_SAAB_Global  = 34,
        emake_SATURN_Global  = 35,
        emake_SCION_Global  = 36,
        emake_SRT_Global  = 37,
        emake_TOYOTA_Global  = 38,
        emake_VOLKSWAGEN_Global  = 39,
        emake_VOLVO_Global  = 40,
        emake_FIAT_Global  = 41,
        emake_ISUZU_Global  = 42,
        emake_MITSUBISHI_Global  = 43,
        emake_PORSCHE_Global  = 44,
        emake_SMART_Global  = 45,
        emake_SUBARU_Global  = 46,
        emake_SUZUKI_Global  = 47,
        emake_OTHERS_Global  = 65534,
        emake_MAX_Global  = 65535,
        emake_BYD_Global  = 48,
        emake_CHERY_Global  = 49,
        emake_DAIHATSU_Global  = 50,
        emake_SSANGYONG_Global  = 51,
        emake_MG_Global  = 52,
        emake_PEUGEOT_Global  = 53,
        emake_SEAT_Global  = 54,
        emake_BENTLEY_Global  = 55,
        emake_ALFA_____ROMEO_Global  = 56,
        emake_CITRO_N_Global  = 57,
        emake_LIFAN_Global  = 58,
        emake_FAW_Global  = 59,
        emake_GM_Global  = 60,
        emake_OPEL_Global  = 61,
        emake_FIAT_FCA__Global  = 62,
    
    }enumMake_Global;
    
    
    typedef enum _enumField_Global{
        efield_UNKNOWN_Global   = 0,
        efield_YEAR_Global  = 1,
        efield_MANUFACTURER_Global  = 2,
        efield_MAKE_Global  = 3,
        efield_MODEL_Global  = 4,
        efield_ENGINE_Global  = 5,
        efield_TRIM_Global  = 6,
        efield_TRANSMISSION_Global  = 7,
        efield_BODYCODE_Global  = 8,
        efield_VIN10TOYEAR_Global  = 9,
        efield_PROTOCOL_Global  = 10,
        efield_DLC_Global  = 11,
        efield_DLCVOLTAGE_Global  = 12,
        efield_PD_RELap DangOR_Global  = 13,
        efield_RELap DangOR_Global  = 14,
        efield_VREF_Global  = 15,
        efield_UARTDATA_Global  = 16,
        efield_CHECKSUM_Global  = 17,
        efield_INITTYPE_Global  = 18,
        efield_CONNECTOR_Global  = 19,
        efield_DTCSTATUSE_Global  = 20,
        efield_BUFFERNAME_Global  = 21,
        efield_DTCDISPLAYTYPE_Global  = 22,
        efield_INNOVAGROUP_Global  = 23,
        efield_BMWVARIANTFORMULA_Global  = 24,
        efield_VARIANT_Global  = 25,
        efield_STEP_Global  = 26,
        efield_BMWREADDTCTYPE_Global  = 27,
        efield_BMWERASEDTCTYPE_Global  = 28,
        efield_BMWPARSERDTCTYPE_Global  = 29,
        efield_COMMAND_Global  = 30,
        efield_BMWVARIANTDECODE_Global  = 31,
        efield_READDTCCOMMANDLIST_Global  = 32,
        efield_COMMANDLIST_Global  = 33,
        efield_ECUINFOTYPE_Global  = 34,
        efield_DTCREADTYPE_Global  = 35,
        efield_LOOKUPTABLE_Global  = 36,
        efield_MESSAGEID_Global  = 37,
        efield_SYSTEM_Global  = 38,
        efield_TIMING_Global  = 39,
        efield_ERASETYPE_Global  = 40,
        efield_SUBSYSTEM_Global  = 41,
        efield_PROGRAMID_Global  = 42,
        efield_UNITINFORESULT_Global  = 43,
        efield_DISPLAYVISIBLE_Global  = 44,
        efield_HONDAOPTION_Global  = 45,
        efield_ECUTYPE_Global  = 46,
        efield_ECUPARTNUMBER_Global  = 47,
        efield_PARSERTYPE_Global  = 48,
        efield_FORMULA_Global  = 49,
        efield_CONVERTUNIT_Global  = 50,
        efield_MERCEDES_SUPPLIER_Global  = 51,
        efield_MERCEDES_QUALIFIER_Global  = 52,
        efield_MODELTYPE_Global  = 53,
        efield_BM_Global  = 54,
        efield_ECUID_Global  = 55,
        efield_TYPE_Global  = 56,
    
    }enumField_Global;
    
    
    typedef enum _enumVin10toyear_Global{
        evin10toyear_UNKNOWN_Global   = 0,
        evin10toyear_T_Global  = 16,
        evin10toyear_V_Global  = 17,
        evin10toyear_W_Global  = 18,
        evin10toyear_X_Global  = 19,
        evin10toyear_Y_Global  = 20,
        evin10toyear_1_Global  = 21,
        evin10toyear_2_Global  = 22,
        evin10toyear_3_Global  = 23,
        evin10toyear_4_Global  = 24,
        evin10toyear_5_Global  = 25,
        evin10toyear_6_Global  = 26,
        evin10toyear_7_Global  = 27,
        evin10toyear_8_Global  = 28,
        evin10toyear_9_Global  = 29,
        evin10toyear_A_Global  = 30,
        evin10toyear_B_Global  = 31,
        evin10toyear_C_Global  = 32,
        evin10toyear_D_Global  = 33,
        evin10toyear_E_Global  = 34,
        evin10toyear_F_Global  = 35,
        evin10toyear_G_Global  = 36,
        evin10toyear_H_Global  = 37,
        evin10toyear_J_Global  = 38,
        evin10toyear_K_Global  = 39,
        evin10toyear_L_Global  = 40,
        evin10toyear_M_Global  = 41,
        evin10toyear_N_Global  = 42,
        evin10toyear_P_Global  = 43,
        evin10toyear_R_Global  = 44,
        evin10toyear_S_Global  = 45,
    
    }enumVin10toyear_Global;
    
    
    typedef enum _enumProtocol_Global{
        eprotocol_UNKNOWN_Global   = 0,
        eprotocol_PROTOCOL_NO_Global  = 0,
        eprotocol_PROTOCOL_VPW_Global  = 1,
        eprotocol_PROTOCOL_PWM_Global  = 2,
        eprotocol_PROTOCOL_ISO9141_Global  = 3,
        eprotocol_PROTOCOL_KW2000_Global  = 4,
        eprotocol_PROTOCOL_CAN500KBAUD_Global  = 5,
        eprotocol_PROTOCOL_XCAN500KBAUD_Global  = 6,
        eprotocol_PROTOCOL_CAN250KBAUD_Global  = 7,
        eprotocol_PROTOCOL_XCAN250KBAUD_Global  = 8,
        eprotocol_PROTOCOL_BOSCH_Global  = 9,
        eprotocol_PROTOCOL_RESERVE_10_Global  = 10,
        eprotocol_PROTOCOL_RESERVE_11_Global  = 11,
        eprotocol_PROTOCOL_RESERVE_12_Global  = 12,
        eprotocol_PROTOCOL_RESERVE_13_Global  = 13,
        eprotocol_PROTOCOL_RESERVE_14_Global  = 14,
        eprotocol_PROTOCOL_KW_Global  = 15,
        eprotocol_PROTOCOL_KW1281_Global  = 16,
        eprotocol_PROTOCOL_MUT_Global  = 17,
        eprotocol_PROTOCOL_CAN_C_UDS_Global  = 18,
        eprotocol_PROTOCOL_CAN_I_UDS_Global  = 19,
        eprotocol_PROTOCOL_RESERVE_20_Global  = 20,
        eprotocol_PROTOCOL_CCD2_Global  = 21,
        eprotocol_PROTOCOL_SDL_Global  = 22,
        eprotocol_PROTOCOL_UBP_Global  = 23,
        eprotocol_PROTOCOL_MCAN_Global  = 24,
        eprotocol_PROTOCOL_MCAN_____UDS_Global  = 25,
        eprotocol_PROTOCOL_H99B_Global  = 26,
        eprotocol_PROTOCOL_95HM_Global  = 27,
        eprotocol_PROTOCOL_92HM_Global  = 28,
        eprotocol_PROTOCOL_CAN_Global  = 29,
        eprotocol_PROTOCOL_RESERVE_30_Global  = 30,
        eprotocol_PROTOCOL_RESERVE_31_Global  = 31,
        eprotocol_PROTOCOL_CCD_Global  = 32,
        eprotocol_PROTOCOL_SCI_Global  = 33,
        eprotocol_PROTOCOL_RESERVE_34_Global  = 34,
        eprotocol_PROTOCOL_RESERVE_35_Global  = 35,
        eprotocol_PROTOCOL_RESERVE_36_Global  = 36,
        eprotocol_PROTOCOL_RESERVE_37_Global  = 37,
        eprotocol_PROTOCOL_RESERVE_38_Global  = 38,
        eprotocol_PROTOCOL_RESERVE_39_Global  = 39,
        eprotocol_PROTOCOL_RESERVE_40_Global  = 40,
        eprotocol_PROTOCOL_RESERVE_41_Global  = 41,
        eprotocol_PROTOCOL_OBD1_Global  = 42,
        eprotocol_PROTOCOL_RESERVE_43_Global  = 43,
        eprotocol_PROTOCOL_RESERVE_44_Global  = 44,
        eprotocol_PROTOCOL_RESERVE_45_Global  = 45,
        eprotocol_PROTOCOL_RESERVE_46_Global  = 46,
        eprotocol_PROTOCOL_RESERVE_47_Global  = 47,
        eprotocol_PROTOCOL_DDL1_Global  = 48,
        eprotocol_PROTOCOL_SWCAN_Global  = 49,
        eprotocol_PROTOCOL_RESERVE_50_Global  = 50,
        eprotocol_PROTOCOL_MB_ISO_Global  = 51,
        eprotocol_PROTOCOL_KWFB_Global  = 52,
        eprotocol_PROTOCOL_BMW_CAN_Global  = 53,
        eprotocol_PROTOCOL_TPCAN_2_0_Global  = 54,
        eprotocol_PROTOCOL_TPCAN_1_6_KW1281_Global  = 55,
        eprotocol_PROTOCOL_TPCAN_1_6_KW2000_Global  = 56,
        eprotocol_PROTOCOL_KWSSM_Global  = 57,
        eprotocol_PROTOCOL_DDL2_Global  = 58,
        eprotocol_PROTOCOL_DS2_Global  = 59,
        eprotocol_PROTOCOL_CAN_UDS_Global  = 60,
        eprotocol_PROTOCOL_CANUDS_Global  = 60,
        eprotocol_PROTOCOL_CAN_D2_Global  = 61,
        eprotocol_PROTOCOL_CAN_GGD_Global  = 62,
        eprotocol_PROTOCOL_ALDL_Global  = 63,
        eprotocol_PROTOCOL_GMLAN_Global  = 64,
        eprotocol_PROTOCOL_MAX_Global  = 65535,
        eprotocol_PROTOCOL_CAN_C_Global  = 65,
        eprotocol_PROTOCOL_TCAN_Global  = 66,
        eprotocol_PROTOCOL_DS1_Global  = 70,
        eprotocol_PROTOCOL_DS2_MID_Global  = 71,
        eprotocol_PROTOCOL_D2_Global  = 73,
        eprotocol_PROTOCOL_GGD_Global  = 74,
        eprotocol_SUZUKI_SDL_Global  = 75,
        eprotocol_PROTOCOL_SUBARU_KWP_4800_Global  = 76,
        eprotocol_PROTOCOL_SUBARU_FHICAN_Global  = 77,
        eprotocol_PROTOCOL_SUBARU_TMC_Global  = 78,
        eprotocol_PROTOCOL_SUBARU_KWP_10400_Global  = 79,
        eprotocol_PROTOCOL_SUBARU_KWP_1953_Global  = 80,
    
    }enumProtocol_Global;
    
    
    typedef enum _enumDlc_Global{
        edlc_UNKNOWN_Global   = 0,
        edlc_PIN1_Global  = 2,
        edlc_PIN1_INV_Global  = 3,
        edlc_PIN2_Global  = 4,
        edlc_PIN2_INV_Global  = 5,
        edlc_PIN3_Global  = 6,
        edlc_PIN3_INV_Global  = 7,
        edlc_PIN4_Global  = 8,
        edlc_PIN4_INV_Global  = 9,
        edlc_PIN5_Global  = 10,
        edlc_PIN5_INV_Global  = 11,
        edlc_PIN6_Global  = 12,
        edlc_PIN6_INV_Global  = 13,
        edlc_PIN7_Global  = 14,
        edlc_PIN7_INV_Global  = 15,
        edlc_PIN8_Global  = 16,
        edlc_PIN8_INV_Global  = 17,
        edlc_PIN9_Global  = 18,
        edlc_PIN9_INV_Global  = 19,
        edlc_PIN10_Global  = 20,
        edlc_PIN10_INV_Global  = 21,
        edlc_PIN11_Global  = 22,
        edlc_PIN11_INV_Global  = 23,
        edlc_PIN12_Global  = 24,
        edlc_PIN12_INV_Global  = 25,
        edlc_PIN13_Global  = 26,
        edlc_PIN13_INV_Global  = 27,
        edlc_PIN14_Global  = 28,
        edlc_PIN14_INV_Global  = 29,
        edlc_PIN15_Global  = 30,
        edlc_PIN15_INV_Global  = 31,
        edlc_PIN3_INV_OBD1_Global  = 32,
        edlc_PIN7_OBD1_Global  = 33,
        edlc_PIN15_OBD1_Global  = 34,
        edlc_CCD_3_11_Global  = 35,
        edlc_PIN_NA_Global  = 255,
        edlc_PIN16_Global  = 32,
        edlc_PIN20_Global  = 33,
        edlc_PIN22_Global  = 34,
        edlc_PIN23_Global  = 35,
        edlc_PIN24_Global  = 36,
        edlc_PIN25_Global  = 37,
        edlc_PIN28_Global  = 38,
        edlc_PIN30_Global  = 39,
        edlc_PIN32_Global  = 40,
        edlc_PIN33_Global  = 41,
        edlc_PIN34_Global  = 42,
        edlc_PIN35_Global  = 43,
        edlc_PIN36_Global  = 44,
        edlc_PIN17_Global  = 45,
        edlc_PIN15_INV_OBD1_Global  = 46,
        edlc_PIN9_OBD1_Global  = 47,
        edlc_PIN2_OBD1_Global  = 48,
        edlc_PIN8_OBD1_Global  = 49,
        edlc_PIN14_OBD1_Global  = 50,
        edlc_PIN11_OBD1_Global  = 51,
        edlc_PIN6_OBD1_Global  = 52,
    
    }enumDlc_Global;
    
    
    typedef enum _enumDlcvoltage_Global{
        edlcvoltage_UNKNOWN_Global   = 0,
        edlcvoltage_LEVEL_FLOAT_Global  = 1,
        edlcvoltage_LEVEL_5V_Global  = 2,
        edlcvoltage_LEVEL_8V_Global  = 3,
        edlcvoltage_LEVEL_12V_Global  = 4,
        edlcvoltage_LEVEL_24V_Global  = 5,
        edlcvoltage_LEVEL_36V_Global  = 6,
    
    }enumDlcvoltage_Global;
    
    
    typedef enum _enumPd_ReLap Dangor_Global{
        epd_reLap Dangor_UNKNOWN_Global   = 0,
        epd_reLap Dangor_PD_NONE_Global  = 0,
        epd_reLap Dangor_PD_OPEN_Global  = 1,
        epd_reLap Dangor_PD_2K8_Global  = 2,
        epd_reLap Dangor_PD_3K9_Global  = 3,
        epd_reLap Dangor_PD_10K_Global  = 4,
    
    }enumPd_ReLap Dangor_Global;
    
    
    typedef enum _enumReLap Dangor_Global{
        ereLap Dangor_UNKNOWN_Global   = 0,
        ereLap Dangor_PU_NONE_Global  = 0,
        ereLap Dangor_PU_511_Global  = 1,
        ereLap Dangor_PU_2K7_Global  = 2,
        ereLap Dangor_PU_4K7_Global  = 4,
        ereLap Dangor_PU_1K_Global  = 8,
        ereLap Dangor_PU_2K_Global  = 16,
        ereLap Dangor_4700_____OHM_Global  = 32,
    
    }enumReLap Dangor_Global;
    
    
    typedef enum _enumVref_Global{
        evref_UNKNOWN_Global   = 0,
        evref_VREF_NA_Global  = 0,
        evref_VREF_AUTO_Global  = 1,
        evref_VREF_1V5_Global  = 2,
        evref_VREF_2V5_Global  = 3,
    
    }enumVref_Global;
    
    
    typedef enum _enumUartdata_Global{
        euartdata_UNKNOWN_Global   = 0,
        euartdata_DATA8BIT_NO_PARITY_Global  = 0,
        euartdata_DATA8BIT_EVEN_PARITY_Global  = 1,
        euartdata_DATA8BIT_ODD_PARIRY_Global  = 2,
    
    }enumUartdata_Global;
    
    
    typedef enum _enumChecksum_Global{
        echecksum_UNKNOWN_Global   = 0,
        echecksum_CS_NONE_Global  = 0,
        echecksum_CS_NORMAL_1BYTE_Global  = 1,
        echecksum_CS_INVERT_1BYTE_Global  = 2,
        echecksum_CS_NORMAL_2BYTE_Global  = 3,
        echecksum_CS_CRC_1D_Global  = 4,
        echecksum_CS_CRC_01_Global  = 5,
    
    }enumChecksum_Global;
    
    
    typedef enum _enumInittype_Global{
        einittype_UNKNOWN_Global   = 0,
        einittype_INIT_NONE_Global  = 0,
        einittype_INIT_FIVEBAUDS_Global  = 1,
        einittype_INIT_FASTBAUDS_Global  = 2,
        einittype_INIT_MAX_Global  = 3,
        einittype___Global  = 255,
    
    }enumInittype_Global;
    
    
    typedef enum _enumConnector_Global{
        econnector_UNKNOWN_Global   = 0,
        econnector_NONE_Global  = 0,
        econnector_OBDII_Global  = 1,
        econnector_GM_OBD1_Global  = 2,
        econnector_FORD_OBD1_Global  = 3,
        econnector_CHRYSLER_OBD1_Global  = 4,
        econnector_TOYOTA_OBD1_Global  = 5,
        econnector_HONDA_OBD1_Global  = 6,
        econnector_KIA_20_PINS_Global  = 7,
        econnector_TOYOTA_17_PINS_Global  = 8,
        econnector_TOYOTA_22_PINS_Global  = 9,
        econnector_BMW_20_PINS_Global  = 10,
        econnector_NISSAN_14_PINS_Global  = 11,
        econnector_BMW_16_PINS_Global  = 12,
        econnector_BENZ_38_PINS_Global  = 13,
        econnector_CHRYSLER_16_PINS_Global  = 14,
        econnector_BENZ_14PIN_PINS_Global  = 15,
        econnector_MAZDA_17_PINS_Global  = 16,
        econnector_MIT_12_16_PINS_Global  = 17,
        econnector_NISSAN_14_TSURU_Global  = 18,
        econnector_MAX_Global  = 65535,
        econnector_OEM_Global  = 19,
        econnector_HYUNDAI_12_Global  = 20,
        econnector_KIA_20_Global  = 21,
        econnector_NISSAN_14_Global  = 22,
        econnector_TOYOTA_17_22_Global  = 23,
        econnector_BMW_OEM_20_Global  = 24,
        econnector_BENZ_14_Global  = 25,
        econnector_BMW_20_Global  = 26,
        econnector_BENZ_38_Global  = 27,
    
    }enumConnector_Global;
    
    
    typedef enum _enumDtcstatuse_Global{
        edtcstatuse_UNKNOWN_Global   = 0,
        edtcstatuse_TYPE_DTC_STATUS_NA_Global  = 0,
        edtcstatuse_TYPE_DTC_STATUS_GENERAL_Global  = 1,
        edtcstatuse_TYPE_DTC_STATUS_CHRYSLER_CAN_Global  = 2,
        edtcstatuse_TYPE_DTC_STATUS_CHRYSLER_CAN_UDS_Global  = 3,
        edtcstatuse_TYPE_DTC_STATUS_GM_GMLAN_DOC_Global  = 4,
        edtcstatuse_TYPE_DTC_STATUS_HONDABODY_KW_Global  = 5,
        edtcstatuse_TYPE_DTC_STATUS_HYUNDAI_1_Global  = 6,
        edtcstatuse_TYPE_DTC_STATUS_HYUNDAI_2_Global  = 7,
        edtcstatuse_TYPE_DTC_STATUS_VAG_0_Global  = 8,
        edtcstatuse_TYPE_DTC_STATUS_VAG_1_Global  = 9,
        edtcstatuse_TYPE_DTC_STATUS_VAG_2_Global  = 10,
        edtcstatuse_TYPE_DTC_STATUS_VAG_3_Global  = 11,
        edtcstatuse_TYPE_DTC_STATUS_VAG_4_Global  = 12,
        edtcstatuse_TYPE_DTC_STATUS_VAG_5_Global  = 13,
        edtcstatuse_TYPE_DTC_STATUS_VAG_6_Global  = 14,
        edtcstatuse_TYPE_DTC_STATUS_VAG_7_Global  = 15,
        edtcstatuse_TYPE_DTC_STATUS_VOLVO_1_Global  = 16,
        edtcstatuse_TYPE_DTC_STATUS_MERCEDES_CANUDS_Global  = 17,
        edtcstatuse_TYPE_DTC_STATUS_MERCEDES_KW2000_CAN_Global  = 18,
        edtcstatuse_TYPE_DTC_STATUS_MERCEDES_KWFB_Global  = 19,
        edtcstatuse_TYPE_DTC_STATUS_VOLVO_2_Global  = 20,
        edtcstatuse_TYPE_DTC_STATUS_NISSAN_BYTE_Global  = 21,
        edtcstatuse_TYPE_DTC_STATUS_NISSAN_BIT_Global  = 22,
        edtcstatuse_TYPE_DTC_STATUS_HYUNDAI_SRS_0207_Global  = 23,
    
    }enumDtcstatuse_Global;
    
    
    typedef enum _enumBuffername_Global{
        ebuffername_UNKNOWN_Global   = 0,
        ebuffername_NONE_Global  = 0,
        ebuffername_HISTORY_Global  = 1,
        ebuffername_HISTORICAL_Global  = 2,
        ebuffername_CURRENT_Global  = 3,
        ebuffername_STORED_Global  = 4,
        ebuffername_PENDING_Global  = 5,
        ebuffername_MIL_Global  = 6,
        ebuffername_READINESS_Global  = 7,
        ebuffername_PERMANENT_Global  = 8,
        ebuffername_TEMPORARY_Global  = 9,
        ebuffername_FAIL_SINCE_CLEAR_Global  = 10,
        ebuffername_KOEO_Global  = 11,
        ebuffername_KOER_Global  = 12,
        ebuffername_CONTINUOUS_Global  = 13,
        ebuffername_PAST_Global  = 14,
        ebuffername_PRESENT_Global  = 15,
        ebuffername_CONFIRMED_Global  = 16,
        ebuffername_CM_Global  = 17,
        ebuffername_DCHECK_Global  = 18,
        ebuffername_NOTPRESENT_Global  = 19,
        ebuffername_ACTIVE_Global  = 20,
        ebuffername_MEMORY_Global  = 21,
        ebuffername_INTERMITTENT_Global  = 22,
        ebuffername_INVALID_Global  = 23,
        ebuffername_STATIC_Global  = 24,
        ebuffername_ON_DEMAND_Global  = 25,
        ebuffername_CURRENT_DTC_SINCE_POWER_UP_Global  = 26,
        ebuffername_DTC_SUPPORTED_BY_CALIBRATION_Global  = 27,
        ebuffername_TEST_NOT_PASSED_SINCE_CURRENT_POWER_UP_Global  = 28,
        ebuffername_TEST_NOT_PASSED_SINCE_DTC_CLEARED_Global  = 29,
        ebuffername_KOEO_INJECTOR_Global  = 30,
        ebuffername_KOER_GLOWPLUG_Global  = 31,
        ebuffername_MAX_Global  = 255,
        ebuffername_LATCHED_Global  = 32,
        ebuffername_NOT_____ACTIVE_Global  = 33,
        ebuffername_TEST_____NOT_____PASS_____SINCE_____CODE_____CLEARED_Global  = 34,
        ebuffername_FAILED_____SINCE_____CLEAR_Global  = 35,
        ebuffername_MIL_HISTORY_Global  = 36,
        ebuffername_LAST_____TEST_____FAILED_Global  = 37,
        ebuffername_CURRENT_HISTORY_Global  = 38,
        ebuffername_RECORD_Global  = 39,
        ebuffername_STORAGE_Global  = 40,
        ebuffername_CHASSIS_Global  = 41,
        ebuffername_REGION_Global  = 42,
        ebuffername_CURRENT_____DTC_Global  = 43,
        ebuffername_HISTORY_____DTC_Global  = 44,
        ebuffername_CHASSI_____DTC_Global  = 45,
        ebuffername_REGION_____DTC_Global  = 46,
        ebuffername_PROVISIONAL_Global  = 47,
    
    }enumBuffername_Global;
    
    
    typedef enum _enumDtcdisplaytype_Global{
        edtcdisplaytype_UNKNOWN_Global   = 0,
        edtcdisplaytype_DTC_1BYTE_HB_LB_Global  = 1,
        edtcdisplaytype_DTC_DEC_Global  = 2,
        edtcdisplaytype_DTC_DEC_2DIGIT_Global  = 3,
        edtcdisplaytype_DTC_DEC_3DIGIT_Global  = 4,
        edtcdisplaytype_DTC_DEC_4DIGIT_Global  = 5,
        edtcdisplaytype_DTC_DEC_5DIGIT_Global  = 6,
        edtcdisplaytype_DTC_HEX_Global  = 7,
        edtcdisplaytype_DTC_HEX_2DIGIT_Global  = 8,
        edtcdisplaytype_DTC_HEX_3DIGIT_Global  = 9,
        edtcdisplaytype_DTC_HEX_4DIGIT_Global  = 10,
        edtcdisplaytype_DTC_HEX_5DIGIT_Global  = 11,
        edtcdisplaytype_DTC_HEX_6DIGIT_Global  = 12,
        edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_DEC_Global  = 13,
        edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_DEC_2_Global  = 14,
        edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_DEC_3_Global  = 15,
        edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_HEX_Global  = 16,
        edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_HEX_NO_TRIM_Global  = 17,
        edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_DEC_Global  = 18,
        edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_DEC_2_Global  = 19,
        edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_DEC_3_Global  = 20,
        edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_HEX_Global  = 21,
        edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_HEX_NO_TRIM_Global  = 22,
        edtcdisplaytype_DTC_MAIN_SAE_SUB_1BYTE_DEC_Global  = 23,
        edtcdisplaytype_DTC_MAIN_SAE_SUB_1BYTE_DEC_NO_TRIM_Global  = 24,
        edtcdisplaytype_DTC_MAIN_SAE_SUB_1BYTE_HEX_Global  = 25,
        edtcdisplaytype_DTC_MAIN_SAE_SUB_1BYTE_HEX_NO_TRIM_Global  = 26,
        edtcdisplaytype_DTC_OEM_SPECIAL_Global  = 27,
        edtcdisplaytype_DTC_SAE_Global  = 28,
        edtcdisplaytype_DTC_HONDA_HEX_1BYTE_Global  = 29,
        edtcdisplaytype_DTC_MAIN_DEC_5DIGIT_SUB_DEC_3_Global  = 30,
        edtcdisplaytype_DTC_HONDA_MAIN_SUB_HEX_Global  = 31,
        edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_DEC_NO_TRIM_Global  = 32,
    
    }enumDtcdisplaytype_Global;
    
    
    typedef enum _enumInnovagroup_Global{
        einnovagroup_UNKNOWN_Global   = 0,
        einnovagroup_GROUP_OBDII_Global  = 1,
        einnovagroup_GROUP_ABS_Global  = 2,
        einnovagroup_GROUP_SRS_Global  = 4,
        einnovagroup_GROUP_ENH_TCM_Global  = 8,
        einnovagroup_GROUP_ENH_ECM_Global  = 16,
        einnovagroup_GROUP_ENH_PCM_Global  = 16,
        einnovagroup_GROUP_OBDI_Global  = 32,
        einnovagroup_INNOVA_GROUP_UNKNOW_Global  = 255,
    
    }enumInnovagroup_Global;
    

#endif