/******************************************************************************************************************
* Engineer    : automatic generated
* Date        : 9/11/2015
********************************************************************************************************************/

#ifndef __ENUMS_Nissan_H__
#define __ENUMS_Nissan_H__

    
    typedef enum _enumCommand_Nissan{
        ecommand_UNKNOWN_Nissan   = 0,
        ecommand_02_____3E_____01_____FF_____FF_____FF_____FF_____FF_Nissan  = 1,
        ecommand_02_____10_____81_____FF_____FF_____FF_____FF_____FF_Nissan  = 2,
        ecommand_3E_Nissan  = 3,
        ecommand_82_Nissan  = 4,
        ecommand_30_Nissan  = 5,
        ecommand_02_____10_____C0_____FF_____FF_____FF_____FF_____FF_Nissan  = 6,
        ecommand_02_____21_____83_____FF_____FF_____FF_____FF_____FF_Nissan  = 7,
        ecommand_04_____14_____FF_____FF_____FF_____FF_____FF_____FF_Nissan  = 8,
        ecommand_03_____19_____02_____FF_____FF_____FF_____FF_____FF_Nissan  = 9,
        ecommand_03_____14_____FF_____00_____FF_____FF_____FF_____FF_Nissan  = 10,
        ecommand_03_____17_____FF_____00_____FF_____FF_____FF_____FF_Nissan  = 11,
        ecommand_81_Nissan  = 12,
        ecommand_1A_____80_Nissan  = 13,
        ecommand_14_Nissan  = 14,
        ecommand_A3_Nissan  = 15,
        ecommand_21_____FE_Nissan  = 16,
        ecommand_14_____FF_____00_Nissan  = 17,
        ecommand_17_____FF_____00_Nissan  = 18,
        ecommand_FF_Nissan  = 19,
        ecommand_D0_Nissan  = 20,
        ecommand_C1_Nissan  = 21,
        ecommand_D1_Nissan  = 22,
        ecommand_A2_____00_Nissan  = 23,
        ecommand_A2_____01_Nissan  = 24,
        ecommand_A2_____02_Nissan  = 25,
        ecommand_02_____10_____01_____FF_____FF_____FF_____FF_____FF_Nissan  = 26,
        ecommand_01_____1A_____FF_____FF_____FF_____FF_____FF_____FF_Nissan  = 27,
        ecommand_01_____14_____FF_____FF_____FF_____FF_____FF_____FF_Nissan  = 28,
        ecommand_02_____13_____81_____FF_____FF_____FF_____FF_____FF_Nissan  = 29,
        ecommand_02_____13_____82_____FF_____FF_____FF_____FF_____FF_Nissan  = 30,
        ecommand_C1_____8F_____0B_____18_____1E_____01_____01_____04_____18_____1C_____01_____03_____39_____AD_Nissan  = 31,
        ecommand_D1_____8F_____06_____18_____1C_____01_____01_____39_____6F_Nissan  = 32,
        ecommand_03_____19_____02_____01_____FF_____FF_____FF_____FF_Nissan  = 33,
        ecommand_03_____31_____02_____00_____FF_____FF_____FF_____FF_Nissan  = 34,
        ecommand_03_____19_____02_____3B_____FF_____FF_____FF_____FF_Nissan  = 35,
        ecommand_01_____3E_____FF_____FF_____FF_____FF_____FF_____FF_Nissan  = 36,
        ecommand_1A_____81_Nissan  = 37,
        ecommand_02_____21_____C2_____FF_____FF_____FF_____FF_____FF_Nissan  = 38,
        ecommand_21_____11_____00_____04_____01_Nissan  = 39,
    
    }enumCommand_Nissan;
    
    
    typedef enum _enumReaddtccommandlist_Nissan{
        ereaddtccommandlist_UNKNOWN_Nissan   = 0,
        ereaddtccommandlist_03_____19_____02_____FF_____FF_____FF_____FF_____FF___1_Nissan  = 1,
        ereaddtccommandlist_03_____17_____FF_____00_____FF_____FF_____FF_____FF___2_Nissan  = 2,
        ereaddtccommandlist_A3___3_Nissan  = 3,
        ereaddtccommandlist_17_____FF_____00___4_Nissan  = 4,
        ereaddtccommandlist_D1___5_Nissan  = 5,
        ereaddtccommandlist_A2_____00______CURRENT___A2_____01______STORAGE___A2_____02______HISTORY___6_Nissan  = 6,
        ereaddtccommandlist_D1___7_Nissan  = 7,
        ereaddtccommandlist_02_____13_____81_____FF_____FF_____FF_____FF_____FF______CURRENT___02_____13_____82_____FF_____FF_____FF_____FF_____FF______PAST___8_Nissan  = 8,
        ereaddtccommandlist_D1_____8F_____06_____18_____1C_____01_____01_____39_____6F___9_Nissan  = 9,
        ereaddtccommandlist_03_____19_____02_____01_____FF_____FF_____FF_____FF___10_Nissan  = 10,
        ereaddtccommandlist_03_____19_____02_____3B_____FF_____FF_____FF_____FF___11_Nissan  = 11,
        ereaddtccommandlist_03_____19_____02_____FF_____FF_____FF_____FF_____FF___12_Nissan  = 12,
    
    }enumReaddtccommandlist_Nissan;
    
    
    typedef enum _enumCommandlist_Nissan{
        ecommandlist_UNKNOWN_Nissan   = 0,
        ecommandlist_02_____10_____C0_____FF_____FF_____FF_____FF_____FF_Nissan  = 1,
        ecommandlist_02_____21_____83_____FF_____FF_____FF_____FF_____FF_Nissan  = 2,
        ecommandlist_04_____14_____FF_____FF_____FF_____FF_____FF_____FF_Nissan  = 3,
        ecommandlist_03_____14_____FF_____00_____FF_____FF_____FF_____FF_Nissan  = 4,
        ecommandlist_02_____10_____81_____FF_____FF_____FF_____FF_____FF_Nissan  = 5,
        ecommandlist_81_Nissan  = 6,
        ecommandlist_1A_____80_Nissan  = 7,
        ecommandlist_14_Nissan  = 8,
        ecommandlist_21_____FE_Nissan  = 9,
        ecommandlist_14_____FF_____00_Nissan  = 10,
        ecommandlist_FF_Nissan  = 11,
        ecommandlist_D0_Nissan  = 12,
        ecommandlist_C1_Nissan  = 13,
        ecommandlist_02_____3E_____01_____FF_____FF_____FF_____FF_____FF_Nissan  = 14,
        ecommandlist_02_____10_____01_____FF_____FF_____FF_____FF_____FF_Nissan  = 15,
        ecommandlist_01_____1A_____FF_____FF_____FF_____FF_____FF_____FF_Nissan  = 16,
        ecommandlist_01_____14_____FF_____FF_____FF_____FF_____FF_____FF_Nissan  = 17,
        ecommandlist_C1_____8F_____0B_____18_____1E_____01_____01_____04_____18_____1C_____01_____03_____39_____AD_Nissan  = 18,
        ecommandlist_03_____31_____02_____00_____FF_____FF_____FF_____FF_Nissan  = 19,
        ecommandlist_01_____3E_____FF_____FF_____FF_____FF_____FF_____FF_Nissan  = 20,
        ecommandlist_1A_____81_Nissan  = 21,
        ecommandlist_02_____21_____C2_____FF_____FF_____FF_____FF_____FF_Nissan  = 22,
        ecommandlist_21_____11_____00_____04_____01_Nissan  = 23,
    
    }enumCommandlist_Nissan;
    
    
    typedef enum _enumEcuinfotype_Nissan{
        eecuinfotype_UNKNOWN_Nissan   = 0,
        eecuinfotype_ECUTYPE_ID0000_Nissan  = 1,
        eecuinfotype_ECUTYPE_ID0001_Nissan  = 2,
    
    }enumEcuinfotype_Nissan;
    
    
    typedef enum _enumProgramid_Nissan{
        eprogramid_UNKNOWN_Nissan   = 0,
        eprogramid_4WAS_FRONT__0001_Nissan  = 1,
        eprogramid_4WAS_MAIN__RAS_HICAS_0002_Nissan  = 2,
        eprogramid_4WAS_MAIN__RAS_HICAS_0003_Nissan  = 3,
        eprogramid_ACCELE_____PEDAL_____ACT_0004_Nissan  = 4,
        eprogramid_ADAPTIVE_____LIGHT_0005_Nissan  = 5,
        eprogramid_ADAPTIVE_____LIGHT_0006_Nissan  = 6,
        eprogramid_AIR_____LEVELIZER_0007_Nissan  = 7,
        eprogramid_AIR_____LEVELIZER_0008_Nissan  = 8,
        eprogramid_AIR_____PRESSURE_____MONITOR_0009_Nissan  = 9,
        eprogramid_ALL_____MODE_____AWD_4WD_0010_Nissan  = 10,
        eprogramid_ALL_____MODE_____AWD_4WD_0011_Nissan  = 11,
        eprogramid_ALL_____MODE_____AWD_4WD_0012_Nissan  = 12,
        eprogramid_AUTO_____BACK_____DOOR_0013_Nissan  = 13,
        eprogramid_AUTO_____DRIVER_____POLap DangION_0014_Nissan  = 14,
        eprogramid_AUTO_____DRIVER_____POLap DangION_0015_Nissan  = 15,
        eprogramid_AVM_AROUND_____VIEW_____MONITOR_0016_Nissan  = 16,
        eprogramid_BCM_0017_Nissan  = 17,
        eprogramid_BCM_0018_Nissan  = 18,
        eprogramid_BCM_0019_Nissan  = 19,
        eprogramid_BCM_0020_Nissan  = 20,
        eprogramid_BCM_0021_Nissan  = 21,
        eprogramid_BCM_0022_Nissan  = 22,
        eprogramid_CAN_____GATEWAY_0023_Nissan  = 23,
        eprogramid_EPB_ELECTRIC_____PARKING_____BRAKE_0024_Nissan  = 24,
        eprogramid_EPS_0025_Nissan  = 25,
        eprogramid_EPS_0026_Nissan  = 26,
        eprogramid_EPS_0027_Nissan  = 27,
        eprogramid_EPS_0028_Nissan  = 28,
        eprogramid_EV_____BATTERY_0029_Nissan  = 29,
        eprogramid_HVAC_0030_Nissan  = 30,
        eprogramid_HVAC_0031_Nissan  = 31,
        eprogramid_HVAC_0032_Nissan  = 32,
        eprogramid_HVAC_0033_Nissan  = 33,
        eprogramid_ICC_ADAPTIVE_____CRUISE_____CONTROL_0034_Nissan  = 34,
        eprogramid_ICC_ADAPTIVE_____CRUISE_____CONTROL_0035_Nissan  = 35,
        eprogramid_INTELLIGENT_____KEY_0036_Nissan  = 36,
        eprogramid_IPDM_____E_R_0037_Nissan  = 37,
        eprogramid_MULTI_____AV_0038_Nissan  = 38,
        eprogramid_MULTI_____AV_0039_Nissan  = 39,
        eprogramid_PRECRASH_____SEATBELT_0040_Nissan  = 40,
        eprogramid_PRECRASH_____SEATBELT_0041_Nissan  = 41,
        eprogramid_ABS_0042_Nissan  = 42,
        eprogramid_AIRBAG_0043_Nissan  = 43,
        eprogramid_ENGINE_0044_Nissan  = 44,
        eprogramid_ENGINE_0045_Nissan  = 45,
        eprogramid_ENGINE_0046_Nissan  = 46,
        eprogramid_ENGINE_0047_Nissan  = 47,
        eprogramid_TRANSMISSION_0048_Nissan  = 48,
        eprogramid_TRANSMISSION_0049_Nissan  = 49,
        eprogramid_TRANSMISSION_0050_Nissan  = 50,
        eprogramid_TRANSMISSION_0051_Nissan  = 51,
        eprogramid_TRANSMISSION_0052_Nissan  = 52,
        eprogramid_TRANSMISSION_0053_Nissan  = 53,
        eprogramid_TRANSMISSION_0054_Nissan  = 54,
        eprogramid_TRANSMISSION_0055_Nissan  = 55,
        eprogramid_TRANSMISSION_0056_Nissan  = 56,
        eprogramid_TRANSMISSION_0057_Nissan  = 57,
        eprogramid_TRANSMISSION_0058_Nissan  = 58,
        eprogramid_TRANSMISSION_0059_Nissan  = 59,
        eprogramid_TRANSMISSION_0060_Nissan  = 60,
        eprogramid_TRANSMISSION_0061_Nissan  = 61,
        eprogramid_TRANSMISSION_0062_Nissan  = 62,
        eprogramid_TRANSMISSION_0063_Nissan  = 63,
        eprogramid_TRANSMISSION_0064_Nissan  = 64,
        eprogramid_TRANSMISSION_0065_Nissan  = 65,
        eprogramid_TRANSMISSION_0066_Nissan  = 66,
        eprogramid_TRANSMISSION_0067_Nissan  = 67,
        eprogramid_TRANSMISSION_0068_Nissan  = 68,
        eprogramid_TRANSMISSION_0069_Nissan  = 69,
        eprogramid_TRANSMISSION_0070_Nissan  = 70,
        eprogramid_TRANSMISSION_0071_Nissan  = 71,
        eprogramid_TRANSMISSION_0072_Nissan  = 72,
        eprogramid_TRANSMISSION_0073_Nissan  = 73,
        eprogramid_TRANSMISSION_0074_Nissan  = 74,
        eprogramid_TRANSMISSION_0075_Nissan  = 75,
        eprogramid_TRANSMISSION_0076_Nissan  = 76,
        eprogramid_ALL_____MODE_____AWD_4WD_0078_Nissan  = 77,
        eprogramid_DCM_0079_Nissan  = 78,
        eprogramid_SIDE_____RADAR_____LEFT_0080_Nissan  = 79,
        eprogramid_SIDE_____RADAR_____RIGHT_0081_Nissan  = 80,
        eprogramid_CONVERTIBLE_____ROOF_0082_Nissan  = 81,
        eprogramid_MULTI_____AV_0083_Nissan  = 82,
        eprogramid_CHARGER_0084_Nissan  = 83,
        eprogramid_CONVERTIBLE_____ROOF_0085_Nissan  = 84,
        eprogramid_HEV_0086_Nissan  = 85,
        eprogramid_HV_____BATTERY_0087_Nissan  = 86,
        eprogramid_MOTOR_____CONTROL_0088_Nissan  = 87,
        eprogramid_MOTOR_____CONTROL_EV_0089_Nissan  = 88,
        eprogramid_SBW_0090_Nissan  = 89,
        eprogramid_HVAC_0091_Nissan  = 90,
        eprogramid_AUTO_____BACK_____DOOR_0092_Nissan  = 91,
        eprogramid_AUTO_____SLIDE_____DOOR_____LEFT_0093_Nissan  = 92,
        eprogramid_AUTO_____SLIDE_____DOOR_____RIGHT_0094_Nissan  = 93,
        eprogramid_LANE_____CAMERA_0095_Nissan  = 94,
        eprogramid_EPS_0096_Nissan  = 95,
        eprogramid_IPDM_____E_R_0097_Nissan  = 96,
        eprogramid_LANE_____CAMERA_0098_Nissan  = 97,
        eprogramid_LASER_0099_Nissan  = 98,
        eprogramid_SONAR_0100_Nissan  = 99,
        eprogramid_CONVERTIBLE_____ROOF_0101_Nissan  = 100,
        eprogramid_EACT_BRAKE_0102_Nissan  = 101,
        eprogramid_ICC_ADAPTIVE_____CRUISE_____CONTROL_0103_Nissan  = 102,
        eprogramid_MULTI_____AV_0104_Nissan  = 103,
        eprogramid_MULTI_____DISPLAY_0105_Nissan  = 104,
        eprogramid_EV_0106_Nissan  = 105,
        eprogramid_ABS_0107_Nissan  = 106,
        eprogramid_ABS_0108_Nissan  = 107,
        eprogramid_ENGINE_0109_Nissan  = 108,
        eprogramid_AIRBAG_0110_Nissan  = 109,
        eprogramid_TRANSMISSION_0111_Nissan  = 110,
        eprogramid_TRANSMISSION_0112_Nissan  = 111,
        eprogramid_TRANSMISSION_0113_Nissan  = 112,
        eprogramid_TRANSMISSION_0114_Nissan  = 113,
        eprogramid_BSW_BLIND_____SPOT_____WARNING_0115_Nissan  = 114,
    
    }enumProgramid_Nissan;
    
    
    typedef enum _enumDtcreadtype_Nissan{
        edtcreadtype_UNKNOWN_Nissan   = 0,
        edtcreadtype_READDTCTYPE_ID0000_Nissan  = 1,
        edtcreadtype_READDTCTYPE_ID0001_Nissan  = 2,
        edtcreadtype_READDTCTYPE_ID0008_Nissan  = 3,
        edtcreadtype_READDTCTYPE_ID0003_Nissan  = 4,
        edtcreadtype_READDTCTYPE_ID0004_Nissan  = 5,
        edtcreadtype_READDTCTYPE_ID0005_Nissan  = 6,
        edtcreadtype_READDTCTYPE_ID0002_Nissan  = 7,
        edtcreadtype_READDTCTYPE_ID0006_Nissan  = 8,
        edtcreadtype_READDTCTYPE_ID0007_Nissan  = 9,
    
    }enumDtcreadtype_Nissan;
    
    
    typedef enum _enumLookuptable_Nissan{
        elookuptable_UNKNOWN_Nissan   = 0,
        elookuptable_DTC_____PARSER_____01_Nissan  = 1,
    
    }enumLookuptable_Nissan;
    
    
    typedef enum _enumMessageid_Nissan{
        emessageid_UNKNOWN_Nissan   = 0,
        emessageid_NISSAN_ENGINE_MSGID_0001_Nissan  = 1,
        emessageid_NISSAN_ENGINE_MSGID_0002_Nissan  = 2,
        emessageid_NISSAN_TRANSMISSION_MSGID_0001_Nissan  = 3,
        emessageid_NISSAN_TRANSMISSION_MSGID_0002_Nissan  = 4,
        emessageid_NISSAN_ABS_MSGID_0001_Nissan  = 5,
        emessageid_NISSAN_ABS_MSGID_0002_Nissan  = 6,
        emessageid_NISSAN_AIRBAG_MSGID_0001_Nissan  = 7,
        emessageid_NISSAN_AIRBAG_MSGID_0002_Nissan  = 8,
        emessageid_NISSAN_BCM_MSGID_0001_Nissan  = 9,
        emessageid_NISSAN_BCM_MSGID_0002_Nissan  = 10,
        emessageid_NISSAN_METER_M_A_MSGID_0001_Nissan  = 11,
        emessageid_NISSAN_HVAC_MSGID_0001_Nissan  = 12,
        emessageid_NISSAN_EPS_MSGID_0001_Nissan  = 13,
        emessageid_NISSAN_MULTI_____AV_MSGID_0001_Nissan  = 14,
        emessageid_NISSAN_MULTI_____AV_MSGID_0002_Nissan  = 15,
        emessageid_NISSAN_IPDM_____E_R_MSGID_0001_Nissan  = 16,
        emessageid_NISSAN_AIR_____PRESSURE_____MONITOR_MSGID_0001_Nissan  = 17,
        emessageid_NISSAN_AIR_____PRESSURE_____MONITOR_MSGID_0002_Nissan  = 18,
        emessageid_NISSAN_E_4WD_MSGID_0001_Nissan  = 19,
        emessageid_NISSAN_INTELLIGENT_____KEY_MSGID_0001_Nissan  = 20,
        emessageid_NISSAN_DIU_MSGID_0001_Nissan  = 21,
        emessageid_NISSAN_AUTO_____SLIDE_____DOOR_____LEFT_MSGID_0001_Nissan  = 22,
        emessageid_NISSAN_AUTO_____SLIDE_____DOOR_____RIGHT_MSGID_0001_Nissan  = 23,
        emessageid_NISSAN_PRECRASH_____SEATBELT_MSGID_0001_Nissan  = 24,
        emessageid_NISSAN_AUTO_____DRIVER_____POLap DangION_MSGID_0001_Nissan  = 25,
        emessageid_NISSAN_ALL_____MODE_____AWD_4WD_MSGID_0001_Nissan  = 26,
        emessageid_NISSAN_ALL_____MODE_____AWD_4WD_MSGID_0002_Nissan  = 27,
        emessageid_NISSAN_4WAS_FRONT__MSGID_0001_Nissan  = 28,
        emessageid_NISSAN_4WAS_MAIN__RAS_HICAS_MSGID_0001_Nissan  = 29,
        emessageid_NISSAN_ADAPTIVE_____LIGHT_MSGID_0001_Nissan  = 30,
        emessageid_NISSAN_AIR_____LEVELIZER_MSGID_0001_Nissan  = 31,
        emessageid_NISSAN_ICC_ADAPTIVE_____CRUISE_____CONTROL_MSGID_0001_Nissan  = 32,
        emessageid_NISSAN_SONAR_MSGID_0001_Nissan  = 33,
        emessageid_NISSAN_EPB_ELECTRIC_____PARKING_____BRAKE_MSGID_0001_Nissan  = 34,
        emessageid_NISSAN_LASER_MSGID_0001_Nissan  = 35,
        emessageid_NISSAN_DIFF_____LOCK_MSGID_0001_Nissan  = 36,
        emessageid_NISSAN_MOTOR_____ASSIST_MSGID_0001_Nissan  = 37,
        emessageid_NISSAN_CAN_____GATEWAY_MSGID_0001_Nissan  = 38,
        emessageid_NISSAN_ACCELE_____PEDAL_____ACT_MSGID_0001_Nissan  = 39,
        emessageid_NISSAN_AUTO_____BACK_____DOOR_MSGID_0001_Nissan  = 40,
        emessageid_NISSAN_CONVERTIBLE_____ROOF_MSGID_0001_Nissan  = 41,
        emessageid_NISSAN_MULTI_____DISPLAY_MSGID_0001_Nissan  = 42,
        emessageid_NISSAN_LANE_____CAMERA_MSGID_0001_Nissan  = 43,
        emessageid_NISSAN_AVM_AROUND_____VIEW_____MONITOR_MSGID_0001_Nissan  = 44,
        emessageid_NISSAN_BSW_BLIND_____SPOT_____WARNING_MSGID_0001_Nissan  = 45,
        emessageid_NISSAN_SIDE_____RADAR_____LEFT_MSGID_0001_Nissan  = 46,
        emessageid_NISSAN_SIDE_____RADAR_____RIGHT_MSGID_0001_Nissan  = 47,
        emessageid_NISSAN_DCM_MSGID_0001_Nissan  = 48,
        emessageid_NISSAN_BRAKE_MSGID_0001_Nissan  = 49,
        emessageid_NISSAN_EV_____BATTERY_MSGID_0001_Nissan  = 50,
        emessageid_NISSAN_MOTOR_____CONTROL_EV__MSGID_0001_Nissan  = 51,
        emessageid_NISSAN_CHARGER_MSGID_0001_Nissan  = 52,
        emessageid_NISSAN_SBW_MSGID_0001_Nissan  = 53,
        emessageid_NISSAN_EV_MSGID_0001_Nissan  = 54,
        emessageid_NISSAN_HEV_MSGID_0001_Nissan  = 55,
        emessageid_NISSAN_HV_____BATTERY_MSGID_0001_Nissan  = 56,
        emessageid_NISSAN_MOTOR_____CONTROL_MSGID_0001_Nissan  = 57,
        emessageid_NISSAN_SUB_____METER_MSGID_0001_Nissan  = 58,
        emessageid_NISSAN_HEAD_____LAMP_____LEVELIZER_MSGID_0001_Nissan  = 59,
        emessageid_NISSAN_VSP_VECHICLE_____SOUND_____FOR_____PEDESTRIANS_MSGID_0001_Nissan  = 60,
        emessageid_NISSAN_SVT_MSGID_0001_Nissan  = 61,
        emessageid_NISSAN_NATS_____IMMU_MSGID_0001_Nissan  = 62,
        emessageid_NISSAN_SMART_____ENTRANCE_MSGID_0001_Nissan  = 63,
        emessageid_NISSAN_TCS_MSGID_0001_Nissan  = 64,
        emessageid_NISSAN_TCS_MSGID_0002_Nissan  = 65,
        emessageid_NISSAN_ACTIVE_____SUS_MSGID_0001_Nissan  = 66,
        emessageid_NISSAN_ACTIVE_____SUS_MSGID_0002_Nissan  = 67,
        emessageid_NISSAN_DISTANCE_____CONTROL_MSGID_0001_Nissan  = 68,
        emessageid_NISSAN_DISTANCE_____CONTROL_MSGID_0002_Nissan  = 69,
        emessageid_NISSAN_OCCUPANT_____DETECTION_MSGID_0001_Nissan  = 70,
        emessageid_NISSAN_RCAM_MSGID_0001_Nissan  = 71,
        emessageid_NISSAN_SBLIND_____CAMERA_MSGID_0001_Nissan  = 72,
        emessageid_NISSAN_TOTAL_____ILLUM_MSGID_0001_Nissan  = 73,
    
    }enumMessageid_Nissan;
    
    
    typedef enum _enumSystem_Nissan{
        esystem_UNKNOWN_Nissan   = 0,
    
    }enumSystem_Nissan;
    
    
    typedef enum _enumSubsystem_Nissan{
        esubsystem_UNKNOWN_Nissan   = 0,
        esubsystem_ENGINE_Nissan  = 1,
        esubsystem_TRANSMISSION_Nissan  = 2,
        esubsystem_ABS_Nissan  = 3,
        esubsystem_AIRBAG_Nissan  = 4,
        esubsystem_BCM_Nissan  = 5,
        esubsystem_ALL_____MODE_____AWD_4WD_Nissan  = 6,
        esubsystem_MULTI_____AV_Nissan  = 7,
        esubsystem_TCS_Nissan  = 8,
        esubsystem_DISTANCE_____CONTROL_Nissan  = 9,
        esubsystem_ACTIVE_____SUS_Nissan  = 10,
        esubsystem_AIR_____LEVELIZER_Nissan  = 11,
        esubsystem_SONAR_Nissan  = 12,
        esubsystem_REARVIEW_____CAMERA_Nissan  = 13,
        esubsystem_DIU_Nissan  = 14,
        esubsystem_MOTOR_____ASSIST_Nissan  = 15,
        esubsystem_NATS_____IMMU_Nissan  = 16,
        esubsystem_SMART_____ENTRANCE_Nissan  = 17,
        esubsystem_AUTO_____DRIVER_____POLap DangION_Nissan  = 18,
        esubsystem_DIFF_____LOCK_Nissan  = 19,
        esubsystem_E_4WD_Nissan  = 20,
        esubsystem_IPDM_____E_R_Nissan  = 21,
        esubsystem_METER_M_A_Nissan  = 22,
        esubsystem_AIR_____PRESSURE_____MONITOR_Nissan  = 23,
        esubsystem_INTELLIGENT_____KEY_Nissan  = 24,
        esubsystem_ADAPTIVE_____LIGHT_Nissan  = 25,
        esubsystem_SBLIND_____CAMERA_Nissan  = 26,
        esubsystem_PRECRASH_____SEATBELT_Nissan  = 27,
        esubsystem_4WAS_MAIN__RAS_HICAS_Nissan  = 28,
        esubsystem_HVAC_Nissan  = 29,
        esubsystem_LANE_____CAMERA_Nissan  = 30,
        esubsystem_HEAD_____LAMP_____LEVELIZER_Nissan  = 31,
        esubsystem_ICC_ADAPTIVE_____CRUISE_____CONTROL_Nissan  = 32,
        esubsystem_4WAS_FRONT__Nissan  = 33,
        esubsystem_EPS_Nissan  = 34,
        esubsystem_SUB_____METER_Nissan  = 35,
        esubsystem_HEV_Nissan  = 36,
        esubsystem_ACCELE_____PEDAL_____ACT_Nissan  = 37,
        esubsystem_CAN_____GATEWAY_Nissan  = 38,
        esubsystem_AUTO_____BACK_____DOOR_Nissan  = 39,
        esubsystem_CONVERTIBLE_____ROOF_Nissan  = 40,
        esubsystem_OCCUPANT_____DETECTION_Nissan  = 41,
        esubsystem_TOTAL_____ILLUM_Nissan  = 42,
        esubsystem_SVT_Nissan  = 43,
        esubsystem_SIDE_____RADAR_____LEFT_Nissan  = 44,
        esubsystem_SIDE_____RADAR_____RIGHT_Nissan  = 45,
        esubsystem_BSW_BLIND_____SPOT_____WARNING_Nissan  = 46,
        esubsystem_LASER_Nissan  = 47,
        esubsystem_MULTI_____DISPLAY_Nissan  = 48,
        esubsystem_EV_Nissan  = 49,
        esubsystem_MOTOR_____CONTROL_EV_Nissan  = 50,
        esubsystem_EV_____BATTERY_Nissan  = 51,
        esubsystem_CHARGER_Nissan  = 52,
        esubsystem_DCM_Nissan  = 53,
        esubsystem_EPB_ELECTRIC_____PARKING_____BRAKE_Nissan  = 54,
        esubsystem_EACT_BRAKE_Nissan  = 55,
        esubsystem_SBW_Nissan  = 56,
        esubsystem_VSP_VECHICLE_____SOUND_____FOR_____PEDESTRIANS_Nissan  = 57,
        esubsystem_AUTO_____SLIDE_____DOOR_____LEFT_Nissan  = 58,
        esubsystem_AUTO_____SLIDE_____DOOR_____RIGHT_Nissan  = 59,
        esubsystem_AVM_AROUND_____VIEW_____MONITOR_Nissan  = 60,
        esubsystem_MOTOR_____CONTROL_Nissan  = 61,
        esubsystem_HV_____BATTERY_Nissan  = 62,
    
    }enumSubsystem_Nissan;
    
    
    typedef enum _enumTiming_Nissan{
        etiming_UNKNOWN_Nissan   = 0,
        etiming_TIMINGP_NISSAN_CAN_Nissan  = 1,
        etiming_TWUP_NISSAN_DDL2_Nissan  = 2,
        etiming_TIMINGP_NISSAN_DDL2_Nissan  = 3,
        etiming_TIMINGW_NISSAN_DDL2_Nissan  = 4,
        etiming_TWUP_NISSAN_KW2000_Nissan  = 5,
        etiming_TIMINGP_NISSAN_KW2000_Nissan  = 6,
        etiming_TIMINGW_NISSAN_KW2000_Nissan  = 7,
        etiming_TWUP_NISSAN_DDL1_Nissan  = 8,
        etiming_TIMINGP_NISSAN_DDL1_Nissan  = 9,
        etiming_TIMINGW_NISSAN_DDL1_Nissan  = 10,
        etiming_TIMINGP_NISSAN_TCAN_Nissan  = 11,
        etiming_KW1281DEFAULT_Nissan  = 12,
        etiming_TIMINGP_CHRYSLER_CAN_Nissan  = 13,
        etiming_TIMINGP_CHRYSLER_CAN_C_UDS_Nissan  = 14,
        etiming_TIMINGP_CHRYSLER_CAN_I_UDS_Nissan  = 15,
        etiming_TIMINGP_CHRYSLER_CCD_Nissan  = 16,
        etiming_TIMINGP_CHRYSLER_CCD2_Nissan  = 17,
        etiming_TIMINGP_CHRYSLER_KW2000_Nissan  = 18,
        etiming_TIMINGP_CHRYSLER_KWFB_Nissan  = 19,
        etiming_TIMINGP_CHRYSLER_MB_ISO_Nissan  = 20,
        etiming_TIMINGP_CHRYSLER_MUT_Nissan  = 21,
        etiming_TIMINGP_CHRYSLER_SCI_Nissan  = 22,
        etiming_TIMINGP_CHRYSLER_VPW_Nissan  = 23,
        etiming_TIMINGP_FORD_CAN_Nissan  = 24,
        etiming_TIMINGP_FORD_CAN_UDS_Nissan  = 25,
        etiming_TIMINGP_FORD_ISO9141_Nissan  = 26,
        etiming_TIMINGP_FORD_MCAN_Nissan  = 27,
        etiming_TIMINGP_FORD_MCAN_____UDS_Nissan  = 28,
        etiming_TIMINGP_FORD_PWM_Nissan  = 29,
        etiming_TIMINGP_FORD_UBP_Nissan  = 30,
        etiming_TIMINGP_GM_ALDL_Nissan  = 31,
        etiming_TIMINGP_GM_CAN_Nissan  = 32,
        etiming_TIMINGP_GM_GMLAN_Nissan  = 33,
        etiming_TIMINGP_GM_KW_Nissan  = 34,
        etiming_TIMINGP_GM_SDL_Nissan  = 35,
        etiming_TIMINGP_GM_SWCAN_Nissan  = 36,
        etiming_TIMINGP_GM_VPW_Nissan  = 37,
        etiming_TIMINGP_HONDA_92HM_Nissan  = 38,
        etiming_TIMINGP_HONDA_95HM_Nissan  = 39,
        etiming_TIMINGP_HONDA_BOSCH_Nissan  = 40,
        etiming_TIMINGP_HONDA_CAN_Nissan  = 41,
        etiming_TIMINGP_HONDA_H99B_Nissan  = 42,
        etiming_TIMINGP_HONDA_KW2000_Nissan  = 43,
        etiming_TIMINGP_TOYOTA_CAN_Nissan  = 44,
        etiming_TIMINGP_TOYOTA_ISO9141_Nissan  = 45,
        etiming_TIMINGP_TOYOTA_KW2000_Nissan  = 46,
        etiming_TIMINGP_TOYOTA_VPW_Nissan  = 47,
        etiming_TIMINGW_CHRYSLER_MB_ISO_Nissan  = 48,
        etiming_TIMINGW_CHRYSLER_MUT_Nissan  = 49,
        etiming_TIMINGW_FORD_ISO9141_Nissan  = 50,
        etiming_TIMINGW_GM_KW_Nissan  = 51,
        etiming_TIMINGW_HONDA_BOSCH_Nissan  = 52,
        etiming_TIMINGW_TOYOTA_ISO9141_Nissan  = 53,
        etiming_TWUP_CHRYSLER_KW2000_Nissan  = 54,
        etiming_TWUP_CHRYSLER_KWFB_Nissan  = 55,
        etiming_TWUP_FORD_UBP_Nissan  = 56,
        etiming_TWUP_GM_KW_Nissan  = 57,
        etiming_TWUP_HONDA_92HM_Nissan  = 58,
        etiming_TWUP_HONDA_95HM_Nissan  = 59,
        etiming_TWUP_HONDA_H99B_Nissan  = 60,
        etiming_TWUP_HONDA_KW2000_Nissan  = 61,
        etiming_TWUP_TOYOTA_KW2000_10400_Nissan  = 62,
        etiming_TWUP_TOYOTA_KW2000_9600_Nissan  = 63,
        etiming_TWUPHONDA_00_Nissan  = 64,
        etiming_TIMINGP_NORMAL_Nissan  = 65,
        etiming_TIMINGP_CANNORMAL_Nissan  = 66,
        etiming_TIMINGW_NORMAL_Nissan  = 67,
        etiming_TWUPGENERAL_Nissan  = 68,
        etiming_TWUP_GM_KW9600_Nissan  = 69,
        etiming_TIMINGP_VOLVO_D2_Nissan  = 70,
        etiming_TIMINGP_VOLVO_GGD_Nissan  = 71,
        etiming_TIMINGP_VOLVO_KW_Nissan  = 72,
        etiming_TIMINGW_VOLVO_D2_Nissan  = 73,
        etiming_TWUP_VOLVO_KW_Nissan  = 74,
        etiming_TWUP_VOLVO_GGD_Nissan  = 75,
        etiming_TWUP_VOLVO_D2_Nissan  = 76,
        etiming_TIMINGW_VOLVO_GGD_Nissan  = 77,
        etiming_TIMINGW_VOLVO_KW_Nissan  = 78,
        etiming_TIMINGP_BMW_KW2000_Nissan  = 79,
        etiming_TIMINGP_MERCEDES_BENZ_CAN_Nissan  = 80,
        etiming_TIMINGP_MERCEDES_BENZ_CAN_UDS_Nissan  = 81,
    
    }enumTiming_Nissan;
    
    
    typedef enum _enumErasetype_Nissan{
        eerasetype_UNKNOWN_Nissan   = 0,
    
    }enumErasetype_Nissan;
    
    
    typedef enum _enumModel_Nissan{
        emodel_UNKNOWN_Nissan   = 0,
        emodel_200SX_Nissan  = 1,
        emodel_240SX_Nissan  = 2,
        emodel_300ZX_Nissan  = 3,
        emodel_ALTIMA_Nissan  = 4,
        emodel_G20_Nissan  = 5,
        emodel_I30_Nissan  = 6,
        emodel_J30_Nissan  = 7,
        emodel_MAXIMA_Nissan  = 8,
        emodel_PATHFINDER_Nissan  = 9,
        emodel_PICKUP_Nissan  = 10,
        emodel_Q45_Nissan  = 11,
        emodel_QUEST_Nissan  = 12,
        emodel_SENTRA_Nissan  = 13,
        emodel_QX4_Nissan  = 14,
        emodel_FRONTIER_Nissan  = 15,
        emodel_ALTRA_EV_Nissan  = 16,
        emodel_XTERRA_Nissan  = 17,
        emodel_I35_Nissan  = 18,
        emodel_350Z_Nissan  = 19,
        emodel_FX35_Nissan  = 20,
        emodel_FX45_Nissan  = 21,
        emodel_G35_Nissan  = 22,
        emodel_M45_Nissan  = 23,
        emodel_MURANO_Nissan  = 24,
        emodel_ARMADA_Nissan  = 25,
        emodel_QX56_Nissan  = 26,
        emodel_TITAN_Nissan  = 27,
        emodel_X_TRAIL_Nissan  = 28,
        emodel_M35_Nissan  = 29,
        emodel_M35X_Nissan  = 30,
        emodel_ALTIMA_____HYBRID_Nissan  = 31,
        emodel_G35X_Nissan  = 32,
        emodel_VERSA_Nissan  = 33,
        emodel_ALTIMA_____COUPE_Nissan  = 34,
        emodel_EX35_Nissan  = 35,
        emodel_G37_Nissan  = 36,
        emodel_ROGUE_Nissan  = 37,
        emodel_370Z_Nissan  = 38,
        emodel_370Z_____CONVERTIBLE_Nissan  = 39,
        emodel_CUBE_Nissan  = 40,
        emodel_FX50_Nissan  = 41,
        emodel_G37_____CONVERTIBLE_Nissan  = 42,
        emodel_G37_____COUPE_Nissan  = 43,
        emodel_G37X_Nissan  = 44,
        emodel_GT_R_Nissan  = 45,
        emodel_M45X_Nissan  = 46,
        emodel_G25_Nissan  = 47,
        emodel_G25X_Nissan  = 48,
        emodel_JUKE_Nissan  = 49,
        emodel_LEAF_Nissan  = 50,
        emodel_M37_Nissan  = 51,
        emodel_M37X_Nissan  = 52,
        emodel_M56_Nissan  = 53,
        emodel_M56X_Nissan  = 54,
        emodel_MURANO_____CROSSCABRIOLET_Nissan  = 55,
        emodel_VERSA_____HATCHBACK_Nissan  = 56,
        emodel_M35H_Nissan  = 57,
        emodel_NV_Nissan  = 58,
        emodel_NV3500_Nissan  = 59,
        emodel_EX37_Nissan  = 60,
        emodel_FX37_Nissan  = 61,
        emodel_JX35_Nissan  = 62,
        emodel_NV1500_Nissan  = 63,
        emodel_NV200_Nissan  = 64,
        emodel_NV2500_Nissan  = 65,
        emodel_JUKE_____NISMO_Nissan  = 66,
        emodel_PATHFINDER_____HYBRID_Nissan  = 67,
        emodel_Q50_Nissan  = 68,
        emodel_Q50_____HYBRID_Nissan  = 69,
        emodel_Q60_Nissan  = 70,
        emodel_Q60_____CONVERTIBLE_Nissan  = 71,
        emodel_Q70_Nissan  = 72,
        emodel_Q70_____HYBRID_Nissan  = 73,
        emodel_QX50_Nissan  = 74,
        emodel_QX60_Nissan  = 75,
        emodel_QX60_____HYBRID_Nissan  = 76,
        emodel_QX70_Nissan  = 77,
        emodel_QX80_Nissan  = 78,
        emodel_VERSA_____NOTE_Nissan  = 79,
    
    }enumModel_Nissan;
    
    
    typedef enum _enumEngine_Nissan{
        eengine_UNKNOWN_Nissan   = 0,
        eengine_L4______1_6L______1597_____CC_______DOHC_____16V_Nissan  = 1,
        eengine_V6______3_0L______TWIN_____TURBO_Nissan  = 2,
        eengine_V6______3_3L______200_____CID__Nissan  = 3,
        eengine_L4______2_4L______2389_____CC__Nissan  = 4,
        eengine_V6______3_0L______2960_____CC__Nissan  = 5,
        eengine_L4______1_6L______1597_____CC_______DOHC_Nissan  = 6,
        eengine_V8______4_5L______4494_____CC__Nissan  = 7,
        eengine_V8______4_1L_Nissan  = 8,
        eengine_ELECTRIC_____MOTOR______62_____KW______216_400_____VOLTS______AC_Nissan  = 9,
        eengine_V6______3_3L______200_____CID_______SOHC_Nissan  = 10,
        eengine_V6______3_3L______SOHC_____12V_Nissan  = 11,
        eengine_V6______3_3L______SUPERCHARGED_Nissan  = 12,
        eengine_V8______4_5L_Nissan  = 13,
        eengine_V8______4_5L______DOHC_____32V_Nissan  = 14,
        eengine_V8______5_6L_Nissan  = 15,
        eengine_V8______5_6L______FFV_Nissan  = 16,
        eengine_L4______2_5L______DOHC_____16V_Nissan  = 17,
        eengine_V6______3_7L______DOHC_____24V_Nissan  = 18,
        eengine_V6______3_8L______DOHC_____24V______TURBO_Nissan  = 19,
        eengine_L4______1_6L______TURBO_Nissan  = 20,
        eengine_ELECTRIC_____MOTOR______SYNCHRONOUS______80_____KW_Nissan  = 21,
        eengine_L4______2_0L______DOHC______16V_Nissan  = 22,
        eengine_L4______1_6L______DOHC_____16V_Nissan  = 23,
        eengine_V6______4_0L______DOHC______24V______SEFI_Nissan  = 24,
        eengine_V6______3_7L______DOHC______24V_Nissan  = 25,
        eengine_L4______2_5L______DOHC______16V_Nissan  = 26,
        eengine_V8______5_6L______DOHC______32V_Nissan  = 27,
        eengine_V8______5_6L______DOHC______32V______FFV_Nissan  = 28,
        eengine_L4______1_8L______16V_Nissan  = 29,
        eengine_V6______4_0L______DOHC______24V_Nissan  = 30,
        eengine_V6______3_8L______DOHC______24V______SEFI______TURBO_Nissan  = 31,
        eengine_L4______1_6L______DOHC______16V______TURBO_Nissan  = 32,
        eengine_UU______U______ELECTRIC_Nissan  = 33,
        eengine_L4______2_5L______DOHC______16V______HYBRID______SUPERCHARGED_Nissan  = 34,
        eengine_V6______3_5L______DOHC______24V______HYBRID_Nissan  = 35,
        eengine_V6______3_7L______DOHC______24V______SEFI_Nissan  = 36,
        eengine_V8______5_6L______DOHC______32V______DI_Nissan  = 37,
        eengine_V6______3_5L______DOHC______24V______SEFI______HYBRID_Nissan  = 38,
        eengine_V8______5_0L______DOHC______32V_Nissan  = 39,
        eengine_L4______2_5L______DOHC______16V______SEFI_Nissan  = 40,
        eengine_L4______1_6L______DOHC______16V______SEFI_Nissan  = 41,
        eengine_L4______1_6L______DOHC______16V_Nissan  = 42,
        eengine_L4______2_0L_Nissan  = 43,
        eengine_L4______2_4L_Nissan  = 44,
        eengine_V6______3_0L_Nissan  = 45,
        eengine_V6______3_3L_Nissan  = 46,
        eengine_L4______1_8L_Nissan  = 47,
        eengine_V6______3_5L_Nissan  = 48,
        eengine_L4______2_5L_Nissan  = 49,
        eengine_V6______4_0L_Nissan  = 50,
        eengine_V6______3_7L_Nissan  = 51,
        eengine_V8______5_0L_Nissan  = 52,
        eengine_L4______1_6L_Nissan  = 53,
        eengine_V6______2_5L_Nissan  = 54,
        eengine_L4______1_8L______DOHC_____16V_Nissan  = 55,
        eengine_V6______3_5L______DOHC______24V_Nissan  = 56,
    
    }enumEngine_Nissan;
    

#endif