/******************************************************************************************************************
* Engineer    : automatic generated
* Date        : 9/11/2015
********************************************************************************************************************/

#ifndef __ENUMS_Jaguar_Land_Rover_H__
#define __ENUMS_Jaguar_Land_Rover_H__

    
    typedef enum _enumYear_Jaguar_Land_Rover{
        eyear_UNKNOWN_Jaguar_Land_Rover   = 0,
        eyear_1996_Jaguar_Land_Rover  = 16,
        eyear_1997_Jaguar_Land_Rover  = 17,
        eyear_1998_Jaguar_Land_Rover  = 18,
        eyear_1999_Jaguar_Land_Rover  = 19,
        eyear_2000_Jaguar_Land_Rover  = 20,
        eyear_2001_Jaguar_Land_Rover  = 21,
        eyear_2002_Jaguar_Land_Rover  = 22,
        eyear_2003_Jaguar_Land_Rover  = 23,
        eyear_2004_Jaguar_Land_Rover  = 24,
        eyear_2005_Jaguar_Land_Rover  = 25,
        eyear_2006_Jaguar_Land_Rover  = 26,
        eyear_2007_Jaguar_Land_Rover  = 27,
        eyear_2008_Jaguar_Land_Rover  = 28,
        eyear_2009_Jaguar_Land_Rover  = 29,
        eyear_2010_Jaguar_Land_Rover  = 30,
        eyear_2011_Jaguar_Land_Rover  = 31,
        eyear_2012_Jaguar_Land_Rover  = 32,
        eyear_2013_Jaguar_Land_Rover  = 33,
        eyear_2014_Jaguar_Land_Rover  = 34,
        eyear_2015_Jaguar_Land_Rover  = 35,
        eyear_OTHERS_Jaguar_Land_Rover  = 65534,
        eyear_MAX_Jaguar_Land_Rover  = 65535,
    
    }enumYear_Jaguar_Land_Rover;
    
    
    typedef enum _enumManufacturer_Jaguar_Land_Rover{
        emanufacturer_UNKNOWN_Jaguar_Land_Rover   = 0,
        emanufacturer_BMW_Jaguar_Land_Rover  = 1,
        emanufacturer_CHRYSLER_Jaguar_Land_Rover  = 2,
        emanufacturer_FORD_Jaguar_Land_Rover  = 3,
        emanufacturer_GM_Jaguar_Land_Rover  = 4,
        emanufacturer_HONDA_Jaguar_Land_Rover  = 5,
        emanufacturer_HYUNDAI_Jaguar_Land_Rover  = 6,
        emanufacturer_JAGUAR_Jaguar_Land_Rover  = 7,
        emanufacturer_KIA_Jaguar_Land_Rover  = 8,
        emanufacturer_LAND_____ROVER_Jaguar_Land_Rover  = 9,
        emanufacturer_MAZDA_Jaguar_Land_Rover  = 10,
        emanufacturer_MERCEDES_BENZ_Jaguar_Land_Rover  = 11,
        emanufacturer_NISSAN_Jaguar_Land_Rover  = 12,
        emanufacturer_TOYOTA_Jaguar_Land_Rover  = 13,
        emanufacturer_VOLKSWAGEN_Jaguar_Land_Rover  = 14,
        emanufacturer_VOLVO_Jaguar_Land_Rover  = 15,
        emanufacturer_ISUZU_Jaguar_Land_Rover  = 16,
        emanufacturer_MITSUBISHI_Jaguar_Land_Rover  = 17,
        emanufacturer_SUBARU_Jaguar_Land_Rover  = 18,
        emanufacturer_SUZUKI_Jaguar_Land_Rover  = 19,
        emanufacturer_PORSCHE_Jaguar_Land_Rover  = 20,
        emanufacturer_OTHERS_Jaguar_Land_Rover  = 65534,
        emanufacturer_MAX_Jaguar_Land_Rover  = 65535,
        emanufacturer_GENNERIC_Jaguar_Land_Rover  = 65535,
        emanufacturer_GENERIC_Jaguar_Land_Rover  = 65535,
        emanufacturer_MERCEDES_Jaguar_Land_Rover  = 11,
        emanufacturer_JAGUAR_____LAND_____ROVER_Jaguar_Land_Rover  = 21,
        emanufacturer_BYD_Jaguar_Land_Rover  = 22,
        emanufacturer_CHERY_Jaguar_Land_Rover  = 23,
        emanufacturer_DAIHATSU_Jaguar_Land_Rover  = 24,
        emanufacturer_SSANGYONG_Jaguar_Land_Rover  = 25,
        emanufacturer_ROVER_____GROUP_Jaguar_Land_Rover  = 26,
        emanufacturer_SAIC_Jaguar_Land_Rover  = 27,
        emanufacturer_FIAT_Jaguar_Land_Rover  = 28,
        emanufacturer_PEUGEOT_Jaguar_Land_Rover  = 29,
        emanufacturer_DAEWOO_Jaguar_Land_Rover  = 30,
        emanufacturer_LIFAN_Jaguar_Land_Rover  = 31,
        emanufacturer_FAW_Jaguar_Land_Rover  = 32,
        emanufacturer_MG_Jaguar_Land_Rover  = 33,
    
    }enumManufacturer_Jaguar_Land_Rover;
    
    
    typedef enum _enumMake_Jaguar_Land_Rover{
        emake_UNKNOWN_Jaguar_Land_Rover   = 0,
        emake_ACURA_Jaguar_Land_Rover  = 1,
        emake_AM_____GENERAL_Jaguar_Land_Rover  = 2,
        emake_AUDI_Jaguar_Land_Rover  = 3,
        emake_BMW_Jaguar_Land_Rover  = 4,
        emake_BUICK_Jaguar_Land_Rover  = 5,
        emake_CADILLAC_Jaguar_Land_Rover  = 6,
        emake_CHEVROLET_Jaguar_Land_Rover  = 7,
        emake_CHRYSLER_Jaguar_Land_Rover  = 8,
        emake_DAEWOO_Jaguar_Land_Rover  = 9,
        emake_DODGE_Jaguar_Land_Rover  = 10,
        emake_EAGLE_Jaguar_Land_Rover  = 11,
        emake_FORD_Jaguar_Land_Rover  = 12,
        emake_GEO_Jaguar_Land_Rover  = 13,
        emake_GMC_Jaguar_Land_Rover  = 14,
        emake_HONDA_Jaguar_Land_Rover  = 15,
        emake_HUMMER_Jaguar_Land_Rover  = 16,
        emake_HYUNDAI_Jaguar_Land_Rover  = 17,
        emake_INFINITI_Jaguar_Land_Rover  = 18,
        emake_JAGUAR_Jaguar_Land_Rover  = 19,
        emake_JEEP_Jaguar_Land_Rover  = 20,
        emake_KIA_Jaguar_Land_Rover  = 21,
        emake_LAND_____ROVER_Jaguar_Land_Rover  = 22,
        emake_LEXUS_Jaguar_Land_Rover  = 23,
        emake_LINCOLN_Jaguar_Land_Rover  = 24,
        emake_MAZDA_Jaguar_Land_Rover  = 25,
        emake_MERCEDES_BENZ_Jaguar_Land_Rover  = 26,
        emake_MERCURY_Jaguar_Land_Rover  = 27,
        emake_MINI_Jaguar_Land_Rover  = 28,
        emake_NISSAN_Jaguar_Land_Rover  = 29,
        emake_OLDSMOBILE_Jaguar_Land_Rover  = 30,
        emake_PLYMOUTH_Jaguar_Land_Rover  = 31,
        emake_PONTIAC_Jaguar_Land_Rover  = 32,
        emake_RAM_Jaguar_Land_Rover  = 33,
        emake_SAAB_Jaguar_Land_Rover  = 34,
        emake_SATURN_Jaguar_Land_Rover  = 35,
        emake_SCION_Jaguar_Land_Rover  = 36,
        emake_SRT_Jaguar_Land_Rover  = 37,
        emake_TOYOTA_Jaguar_Land_Rover  = 38,
        emake_VOLKSWAGEN_Jaguar_Land_Rover  = 39,
        emake_VOLVO_Jaguar_Land_Rover  = 40,
        emake_FIAT_Jaguar_Land_Rover  = 41,
        emake_ISUZU_Jaguar_Land_Rover  = 42,
        emake_MITSUBISHI_Jaguar_Land_Rover  = 43,
        emake_PORSCHE_Jaguar_Land_Rover  = 44,
        emake_SMART_Jaguar_Land_Rover  = 45,
        emake_SUBARU_Jaguar_Land_Rover  = 46,
        emake_SUZUKI_Jaguar_Land_Rover  = 47,
        emake_OTHERS_Jaguar_Land_Rover  = 65534,
        emake_MAX_Jaguar_Land_Rover  = 65535,
        emake_BYD_Jaguar_Land_Rover  = 48,
        emake_CHERY_Jaguar_Land_Rover  = 49,
        emake_DAIHATSU_Jaguar_Land_Rover  = 50,
        emake_SSANGYONG_Jaguar_Land_Rover  = 51,
        emake_MG_Jaguar_Land_Rover  = 52,
        emake_PEUGEOT_Jaguar_Land_Rover  = 53,
        emake_SEAT_Jaguar_Land_Rover  = 54,
        emake_BENTLEY_Jaguar_Land_Rover  = 55,
        emake_ALFA_____ROMEO_Jaguar_Land_Rover  = 56,
        emake_CITRO_N_Jaguar_Land_Rover  = 57,
        emake_LIFAN_Jaguar_Land_Rover  = 58,
        emake_FAW_Jaguar_Land_Rover  = 59,
        emake_GM_Jaguar_Land_Rover  = 60,
    
    }enumMake_Jaguar_Land_Rover;
    
    
    typedef enum _enumVin10toyear_Jaguar_Land_Rover{
        evin10toyear_UNKNOWN_Jaguar_Land_Rover   = 0,
        evin10toyear_T_Jaguar_Land_Rover  = 16,
        evin10toyear_V_Jaguar_Land_Rover  = 17,
        evin10toyear_W_Jaguar_Land_Rover  = 18,
        evin10toyear_X_Jaguar_Land_Rover  = 19,
        evin10toyear_Y_Jaguar_Land_Rover  = 20,
        evin10toyear_1_Jaguar_Land_Rover  = 21,
        evin10toyear_2_Jaguar_Land_Rover  = 22,
        evin10toyear_3_Jaguar_Land_Rover  = 23,
        evin10toyear_4_Jaguar_Land_Rover  = 24,
        evin10toyear_5_Jaguar_Land_Rover  = 25,
        evin10toyear_6_Jaguar_Land_Rover  = 26,
        evin10toyear_7_Jaguar_Land_Rover  = 27,
        evin10toyear_8_Jaguar_Land_Rover  = 28,
        evin10toyear_9_Jaguar_Land_Rover  = 29,
        evin10toyear_A_Jaguar_Land_Rover  = 30,
        evin10toyear_B_Jaguar_Land_Rover  = 31,
        evin10toyear_C_Jaguar_Land_Rover  = 32,
        evin10toyear_D_Jaguar_Land_Rover  = 33,
        evin10toyear_E_Jaguar_Land_Rover  = 34,
        evin10toyear_F_Jaguar_Land_Rover  = 35,
        evin10toyear_G_Jaguar_Land_Rover  = 36,
        evin10toyear_H_Jaguar_Land_Rover  = 37,
        evin10toyear_J_Jaguar_Land_Rover  = 38,
        evin10toyear_K_Jaguar_Land_Rover  = 39,
        evin10toyear_L_Jaguar_Land_Rover  = 40,
        evin10toyear_M_Jaguar_Land_Rover  = 41,
        evin10toyear_N_Jaguar_Land_Rover  = 42,
        evin10toyear_P_Jaguar_Land_Rover  = 43,
        evin10toyear_R_Jaguar_Land_Rover  = 44,
        evin10toyear_S_Jaguar_Land_Rover  = 45,
    
    }enumVin10toyear_Jaguar_Land_Rover;
    
    
    typedef enum _enumProtocol_Jaguar_Land_Rover{
        eprotocol_UNKNOWN_Jaguar_Land_Rover   = 0,
        eprotocol_PROTOCOL_NO_Jaguar_Land_Rover  = 0,
        eprotocol_PROTOCOL_VPW_Jaguar_Land_Rover  = 1,
        eprotocol_PROTOCOL_PWM_Jaguar_Land_Rover  = 2,
        eprotocol_PROTOCOL_ISO9141_Jaguar_Land_Rover  = 3,
        eprotocol_PROTOCOL_KW2000_Jaguar_Land_Rover  = 4,
        eprotocol_PROTOCOL_CAN500KBAUD_Jaguar_Land_Rover  = 5,
        eprotocol_PROTOCOL_XCAN500KBAUD_Jaguar_Land_Rover  = 6,
        eprotocol_PROTOCOL_CAN250KBAUD_Jaguar_Land_Rover  = 7,
        eprotocol_PROTOCOL_XCAN250KBAUD_Jaguar_Land_Rover  = 8,
        eprotocol_PROTOCOL_BOSCH_Jaguar_Land_Rover  = 9,
        eprotocol_PROTOCOL_RESERVE_10_Jaguar_Land_Rover  = 10,
        eprotocol_PROTOCOL_RESERVE_11_Jaguar_Land_Rover  = 11,
        eprotocol_PROTOCOL_RESERVE_12_Jaguar_Land_Rover  = 12,
        eprotocol_PROTOCOL_RESERVE_13_Jaguar_Land_Rover  = 13,
        eprotocol_PROTOCOL_RESERVE_14_Jaguar_Land_Rover  = 14,
        eprotocol_PROTOCOL_KW_Jaguar_Land_Rover  = 15,
        eprotocol_PROTOCOL_KW1281_Jaguar_Land_Rover  = 16,
        eprotocol_PROTOCOL_MUT_Jaguar_Land_Rover  = 17,
        eprotocol_PROTOCOL_CAN_C_UDS_Jaguar_Land_Rover  = 18,
        eprotocol_PROTOCOL_CAN_I_UDS_Jaguar_Land_Rover  = 19,
        eprotocol_PROTOCOL_RESERVE_20_Jaguar_Land_Rover  = 20,
        eprotocol_PROTOCOL_CCD2_Jaguar_Land_Rover  = 21,
        eprotocol_PROTOCOL_SDL_Jaguar_Land_Rover  = 22,
        eprotocol_PROTOCOL_UBP_Jaguar_Land_Rover  = 23,
        eprotocol_PROTOCOL_MCAN_Jaguar_Land_Rover  = 24,
        eprotocol_PROTOCOL_MCAN_____UDS_Jaguar_Land_Rover  = 25,
        eprotocol_PROTOCOL_H99B_Jaguar_Land_Rover  = 26,
        eprotocol_PROTOCOL_95HM_Jaguar_Land_Rover  = 27,
        eprotocol_PROTOCOL_92HM_Jaguar_Land_Rover  = 28,
        eprotocol_PROTOCOL_CAN_Jaguar_Land_Rover  = 29,
        eprotocol_PROTOCOL_RESERVE_30_Jaguar_Land_Rover  = 30,
        eprotocol_PROTOCOL_RESERVE_31_Jaguar_Land_Rover  = 31,
        eprotocol_PROTOCOL_CCD_Jaguar_Land_Rover  = 32,
        eprotocol_PROTOCOL_SCI_Jaguar_Land_Rover  = 33,
        eprotocol_PROTOCOL_RESERVE_34_Jaguar_Land_Rover  = 34,
        eprotocol_PROTOCOL_RESERVE_35_Jaguar_Land_Rover  = 35,
        eprotocol_PROTOCOL_RESERVE_36_Jaguar_Land_Rover  = 36,
        eprotocol_PROTOCOL_RESERVE_37_Jaguar_Land_Rover  = 37,
        eprotocol_PROTOCOL_RESERVE_38_Jaguar_Land_Rover  = 38,
        eprotocol_PROTOCOL_RESERVE_39_Jaguar_Land_Rover  = 39,
        eprotocol_PROTOCOL_RESERVE_40_Jaguar_Land_Rover  = 40,
        eprotocol_PROTOCOL_RESERVE_41_Jaguar_Land_Rover  = 41,
        eprotocol_PROTOCOL_OBD1_Jaguar_Land_Rover  = 42,
        eprotocol_PROTOCOL_RESERVE_43_Jaguar_Land_Rover  = 43,
        eprotocol_PROTOCOL_RESERVE_44_Jaguar_Land_Rover  = 44,
        eprotocol_PROTOCOL_RESERVE_45_Jaguar_Land_Rover  = 45,
        eprotocol_PROTOCOL_RESERVE_46_Jaguar_Land_Rover  = 46,
        eprotocol_PROTOCOL_RESERVE_47_Jaguar_Land_Rover  = 47,
        eprotocol_PROTOCOL_DDL1_Jaguar_Land_Rover  = 48,
        eprotocol_PROTOCOL_SWCAN_Jaguar_Land_Rover  = 49,
        eprotocol_PROTOCOL_RESERVE_50_Jaguar_Land_Rover  = 50,
        eprotocol_PROTOCOL_MB_ISO_Jaguar_Land_Rover  = 51,
        eprotocol_PROTOCOL_KWFB_Jaguar_Land_Rover  = 52,
        eprotocol_PROTOCOL_BMW_CAN_Jaguar_Land_Rover  = 53,
        eprotocol_PROTOCOL_TPCAN_2_0_Jaguar_Land_Rover  = 54,
        eprotocol_PROTOCOL_TPCAN_1_6_KW1281_Jaguar_Land_Rover  = 55,
        eprotocol_PROTOCOL_TPCAN_1_6_KW2000_Jaguar_Land_Rover  = 56,
        eprotocol_PROTOCOL_KWSSM_Jaguar_Land_Rover  = 57,
        eprotocol_PROTOCOL_DDL2_Jaguar_Land_Rover  = 58,
        eprotocol_PROTOCOL_DS2_Jaguar_Land_Rover  = 59,
        eprotocol_PROTOCOL_CAN_UDS_Jaguar_Land_Rover  = 60,
        eprotocol_PROTOCOL_CANUDS_Jaguar_Land_Rover  = 60,
        eprotocol_PROTOCOL_CAN_D2_Jaguar_Land_Rover  = 61,
        eprotocol_PROTOCOL_CAN_GGD_Jaguar_Land_Rover  = 62,
        eprotocol_PROTOCOL_ALDL_Jaguar_Land_Rover  = 63,
        eprotocol_PROTOCOL_GMLAN_Jaguar_Land_Rover  = 64,
        eprotocol_PROTOCOL_MAX_Jaguar_Land_Rover  = 65535,
        eprotocol_PROTOCOL_CAN_C_Jaguar_Land_Rover  = 65,
        eprotocol_PROTOCOL_TCAN_Jaguar_Land_Rover  = 66,
        eprotocol_PROTOCOL_DS1_Jaguar_Land_Rover  = 70,
        eprotocol_PROTOCOL_DS2_MID_Jaguar_Land_Rover  = 71,
        eprotocol_PROTOCOL_D2_Jaguar_Land_Rover  = 73,
        eprotocol_PROTOCOL_GGD_Jaguar_Land_Rover  = 74,
        eprotocol_SUZUKI_SDL_Jaguar_Land_Rover  = 75,
    
    }enumProtocol_Jaguar_Land_Rover;
    
    
    typedef enum _enumDlc_Jaguar_Land_Rover{
        edlc_UNKNOWN_Jaguar_Land_Rover   = 0,
        edlc_PIN1_Jaguar_Land_Rover  = 2,
        edlc_PIN1_INV_Jaguar_Land_Rover  = 3,
        edlc_PIN2_Jaguar_Land_Rover  = 4,
        edlc_PIN2_INV_Jaguar_Land_Rover  = 5,
        edlc_PIN3_Jaguar_Land_Rover  = 6,
        edlc_PIN3_INV_Jaguar_Land_Rover  = 7,
        edlc_PIN4_Jaguar_Land_Rover  = 8,
        edlc_PIN4_INV_Jaguar_Land_Rover  = 9,
        edlc_PIN5_Jaguar_Land_Rover  = 10,
        edlc_PIN5_INV_Jaguar_Land_Rover  = 11,
        edlc_PIN6_Jaguar_Land_Rover  = 12,
        edlc_PIN6_INV_Jaguar_Land_Rover  = 13,
        edlc_PIN7_Jaguar_Land_Rover  = 14,
        edlc_PIN7_INV_Jaguar_Land_Rover  = 15,
        edlc_PIN8_Jaguar_Land_Rover  = 16,
        edlc_PIN8_INV_Jaguar_Land_Rover  = 17,
        edlc_PIN9_Jaguar_Land_Rover  = 18,
        edlc_PIN9_INV_Jaguar_Land_Rover  = 19,
        edlc_PIN10_Jaguar_Land_Rover  = 20,
        edlc_PIN10_INV_Jaguar_Land_Rover  = 21,
        edlc_PIN11_Jaguar_Land_Rover  = 22,
        edlc_PIN11_INV_Jaguar_Land_Rover  = 23,
        edlc_PIN12_Jaguar_Land_Rover  = 24,
        edlc_PIN12_INV_Jaguar_Land_Rover  = 25,
        edlc_PIN13_Jaguar_Land_Rover  = 26,
        edlc_PIN13_INV_Jaguar_Land_Rover  = 27,
        edlc_PIN14_Jaguar_Land_Rover  = 28,
        edlc_PIN14_INV_Jaguar_Land_Rover  = 29,
        edlc_PIN15_Jaguar_Land_Rover  = 30,
        edlc_PIN15_INV_Jaguar_Land_Rover  = 31,
        edlc_PIN3_INV_OBD1_Jaguar_Land_Rover  = 32,
        edlc_PIN7_OBD1_Jaguar_Land_Rover  = 33,
        edlc_PIN15_OBD1_Jaguar_Land_Rover  = 34,
        edlc_CCD_3_11_Jaguar_Land_Rover  = 35,
        edlc_PIN_NA_Jaguar_Land_Rover  = 255,
        edlc_PIN16_Jaguar_Land_Rover  = 32,
        edlc_PIN20_Jaguar_Land_Rover  = 33,
        edlc_PIN22_Jaguar_Land_Rover  = 34,
        edlc_PIN23_Jaguar_Land_Rover  = 35,
        edlc_PIN24_Jaguar_Land_Rover  = 36,
        edlc_PIN25_Jaguar_Land_Rover  = 37,
        edlc_PIN28_Jaguar_Land_Rover  = 38,
        edlc_PIN30_Jaguar_Land_Rover  = 39,
        edlc_PIN32_Jaguar_Land_Rover  = 40,
        edlc_PIN33_Jaguar_Land_Rover  = 41,
        edlc_PIN34_Jaguar_Land_Rover  = 42,
        edlc_PIN35_Jaguar_Land_Rover  = 43,
        edlc_PIN36_Jaguar_Land_Rover  = 44,
        edlc_PIN17_Jaguar_Land_Rover  = 45,
        edlc_PIN15_INV_OBD1_Jaguar_Land_Rover  = 46,
        edlc_PIN9_OBD1_Jaguar_Land_Rover  = 47,
        edlc_PIN2_OBD1_Jaguar_Land_Rover  = 48,
        edlc_PIN8_OBD1_Jaguar_Land_Rover  = 49,
        edlc_PIN14_OBD1_Jaguar_Land_Rover  = 50,
        edlc_PIN11_OBD1_Jaguar_Land_Rover  = 51,
        edlc_PIN6_OBD1_Jaguar_Land_Rover  = 52,
    
    }enumDlc_Jaguar_Land_Rover;
    
    
    typedef enum _enumDlcvoltage_Jaguar_Land_Rover{
        edlcvoltage_UNKNOWN_Jaguar_Land_Rover   = 0,
        edlcvoltage_LEVEL_FLOAT_Jaguar_Land_Rover  = 1,
        edlcvoltage_LEVEL_5V_Jaguar_Land_Rover  = 2,
        edlcvoltage_LEVEL_8V_Jaguar_Land_Rover  = 3,
        edlcvoltage_LEVEL_12V_Jaguar_Land_Rover  = 4,
        edlcvoltage_LEVEL_24V_Jaguar_Land_Rover  = 5,
        edlcvoltage_LEVEL_36V_Jaguar_Land_Rover  = 6,
    
    }enumDlcvoltage_Jaguar_Land_Rover;
    
    
    typedef enum _enumPd_ReLap Dangor_Jaguar_Land_Rover{
        epd_reLap Dangor_UNKNOWN_Jaguar_Land_Rover   = 0,
        epd_reLap Dangor_PD_NONE_Jaguar_Land_Rover  = 0,
        epd_reLap Dangor_PD_OPEN_Jaguar_Land_Rover  = 1,
        epd_reLap Dangor_PD_2K8_Jaguar_Land_Rover  = 2,
        epd_reLap Dangor_PD_3K9_Jaguar_Land_Rover  = 3,
        epd_reLap Dangor_PD_10K_Jaguar_Land_Rover  = 4,
    
    }enumPd_ReLap Dangor_Jaguar_Land_Rover;
    
    
    typedef enum _enumReLap Dangor_Jaguar_Land_Rover{
        ereLap Dangor_UNKNOWN_Jaguar_Land_Rover   = 0,
        ereLap Dangor_PU_NONE_Jaguar_Land_Rover  = 0,
        ereLap Dangor_PU_511_Jaguar_Land_Rover  = 1,
        ereLap Dangor_PU_2K7_Jaguar_Land_Rover  = 2,
        ereLap Dangor_PU_4K7_Jaguar_Land_Rover  = 4,
        ereLap Dangor_PU_1K_Jaguar_Land_Rover  = 8,
        ereLap Dangor_PU_2K_Jaguar_Land_Rover  = 16,
        ereLap Dangor_4700_____OHM_Jaguar_Land_Rover  = 32,
    
    }enumReLap Dangor_Jaguar_Land_Rover;
    
    
    typedef enum _enumVref_Jaguar_Land_Rover{
        evref_UNKNOWN_Jaguar_Land_Rover   = 0,
        evref_VREF_NA_Jaguar_Land_Rover  = 0,
        evref_VREF_AUTO_Jaguar_Land_Rover  = 1,
        evref_VREF_1V5_Jaguar_Land_Rover  = 2,
        evref_VREF_2V5_Jaguar_Land_Rover  = 3,
    
    }enumVref_Jaguar_Land_Rover;
    
    
    typedef enum _enumUartdata_Jaguar_Land_Rover{
        euartdata_UNKNOWN_Jaguar_Land_Rover   = 0,
        euartdata_DATA8BIT_NO_PARITY_Jaguar_Land_Rover  = 0,
        euartdata_DATA8BIT_EVEN_PARITY_Jaguar_Land_Rover  = 1,
        euartdata_DATA8BIT_ODD_PARIRY_Jaguar_Land_Rover  = 2,
    
    }enumUartdata_Jaguar_Land_Rover;
    
    
    typedef enum _enumChecksum_Jaguar_Land_Rover{
        echecksum_UNKNOWN_Jaguar_Land_Rover   = 0,
        echecksum_CS_NONE_Jaguar_Land_Rover  = 0,
        echecksum_CS_NORMAL_1BYTE_Jaguar_Land_Rover  = 1,
        echecksum_CS_INVERT_1BYTE_Jaguar_Land_Rover  = 2,
        echecksum_CS_NORMAL_2BYTE_Jaguar_Land_Rover  = 3,
        echecksum_CS_CRC_1D_Jaguar_Land_Rover  = 4,
        echecksum_CS_CRC_01_Jaguar_Land_Rover  = 5,
    
    }enumChecksum_Jaguar_Land_Rover;
    
    
    typedef enum _enumInittype_Jaguar_Land_Rover{
        einittype_UNKNOWN_Jaguar_Land_Rover   = 0,
        einittype_INIT_NONE_Jaguar_Land_Rover  = 0,
        einittype_INIT_FIVEBAUDS_Jaguar_Land_Rover  = 1,
        einittype_INIT_FASTBAUDS_Jaguar_Land_Rover  = 2,
        einittype_INIT_MAX_Jaguar_Land_Rover  = 3,
        einittype___Jaguar_Land_Rover  = 255,
    
    }enumInittype_Jaguar_Land_Rover;
    
    
    typedef enum _enumConnector_Jaguar_Land_Rover{
        econnector_UNKNOWN_Jaguar_Land_Rover   = 0,
        econnector_NONE_Jaguar_Land_Rover  = 0,
        econnector_OBDII_Jaguar_Land_Rover  = 1,
        econnector_GM_OBD1_Jaguar_Land_Rover  = 2,
        econnector_FORD_OBD1_Jaguar_Land_Rover  = 3,
        econnector_CHRYSLER_OBD1_Jaguar_Land_Rover  = 4,
        econnector_TOYOTA_OBD1_Jaguar_Land_Rover  = 5,
        econnector_HONDA_OBD1_Jaguar_Land_Rover  = 6,
        econnector_KIA_20_PINS_Jaguar_Land_Rover  = 7,
        econnector_TOYOTA_17_PINS_Jaguar_Land_Rover  = 8,
        econnector_TOYOTA_22_PINS_Jaguar_Land_Rover  = 9,
        econnector_BMW_20_PINS_Jaguar_Land_Rover  = 10,
        econnector_NISSAN_14_PINS_Jaguar_Land_Rover  = 11,
        econnector_BMW_16_PINS_Jaguar_Land_Rover  = 12,
        econnector_BENZ_38_PINS_Jaguar_Land_Rover  = 13,
        econnector_CHRYSLER_16_PINS_Jaguar_Land_Rover  = 14,
        econnector_BENZ_14PIN_PINS_Jaguar_Land_Rover  = 15,
        econnector_MAZDA_17_PINS_Jaguar_Land_Rover  = 16,
        econnector_MIT_12_16_PINS_Jaguar_Land_Rover  = 17,
        econnector_NISSAN_14_TSURU_Jaguar_Land_Rover  = 18,
        econnector_MAX_Jaguar_Land_Rover  = 65535,
        econnector_OEM_Jaguar_Land_Rover  = 19,
        econnector_HYUNDAI_12_Jaguar_Land_Rover  = 20,
        econnector_KIA_20_Jaguar_Land_Rover  = 21,
        econnector_NISSAN_14_Jaguar_Land_Rover  = 22,
        econnector_TOYOTA_17_22_Jaguar_Land_Rover  = 23,
        econnector_BMW_OEM_20_Jaguar_Land_Rover  = 24,
        econnector_BENZ_14_Jaguar_Land_Rover  = 25,
        econnector_BMW_20_Jaguar_Land_Rover  = 26,
    
    }enumConnector_Jaguar_Land_Rover;
    
    
    typedef enum _enumDtcstatuse_Jaguar_Land_Rover{
        edtcstatuse_UNKNOWN_Jaguar_Land_Rover   = 0,
        edtcstatuse_TYPE_DTC_STATUS_NA_Jaguar_Land_Rover  = 0,
        edtcstatuse_TYPE_DTC_STATUS_GENERAL_Jaguar_Land_Rover  = 1,
        edtcstatuse_TYPE_DTC_STATUS_CHRYSLER_CAN_Jaguar_Land_Rover  = 2,
        edtcstatuse_TYPE_DTC_STATUS_CHRYSLER_CAN_UDS_Jaguar_Land_Rover  = 3,
        edtcstatuse_TYPE_DTC_STATUS_GM_GMLAN_DOC_Jaguar_Land_Rover  = 4,
        edtcstatuse_TYPE_DTC_STATUS_HONDABODY_KW_Jaguar_Land_Rover  = 5,
        edtcstatuse_TYPE_DTC_STATUS_HYUNDAI_1_Jaguar_Land_Rover  = 6,
        edtcstatuse_TYPE_DTC_STATUS_HYUNDAI_2_Jaguar_Land_Rover  = 7,
        edtcstatuse_TYPE_DTC_STATUS_VAG_0_Jaguar_Land_Rover  = 8,
        edtcstatuse_TYPE_DTC_STATUS_VAG_1_Jaguar_Land_Rover  = 9,
        edtcstatuse_TYPE_DTC_STATUS_VAG_2_Jaguar_Land_Rover  = 10,
        edtcstatuse_TYPE_DTC_STATUS_VAG_3_Jaguar_Land_Rover  = 11,
        edtcstatuse_TYPE_DTC_STATUS_VAG_4_Jaguar_Land_Rover  = 12,
        edtcstatuse_TYPE_DTC_STATUS_VAG_5_Jaguar_Land_Rover  = 13,
        edtcstatuse_TYPE_DTC_STATUS_VAG_6_Jaguar_Land_Rover  = 14,
        edtcstatuse_TYPE_DTC_STATUS_VAG_7_Jaguar_Land_Rover  = 15,
        edtcstatuse_TYPE_DTC_STATUS_VOLVO_1_Jaguar_Land_Rover  = 16,
        edtcstatuse_TYPE_DTC_STATUS_MERCEDES_CANUDS_Jaguar_Land_Rover  = 17,
        edtcstatuse_TYPE_DTC_STATUS_MERCEDES_KW2000_CAN_Jaguar_Land_Rover  = 18,
        edtcstatuse_TYPE_DTC_STATUS_MERCEDES_KWFB_Jaguar_Land_Rover  = 19,
        edtcstatuse_TYPE_DTC_STATUS_VOLVO_2_Jaguar_Land_Rover  = 20,
        edtcstatuse_TYPE_DTC_STATUS_NISSAN_BYTE_Jaguar_Land_Rover  = 21,
        edtcstatuse_TYPE_DTC_STATUS_NISSAN_BIT_Jaguar_Land_Rover  = 22,
        edtcstatuse_TYPE_DTC_STATUS_HYUNDAI_SRS_0207_Jaguar_Land_Rover  = 23,
    
    }enumDtcstatuse_Jaguar_Land_Rover;
    
    
    typedef enum _enumBuffername_Jaguar_Land_Rover{
        ebuffername_UNKNOWN_Jaguar_Land_Rover   = 0,
        ebuffername_NONE_Jaguar_Land_Rover  = 0,
        ebuffername_HISTORY_Jaguar_Land_Rover  = 1,
        ebuffername_HISTORICAL_Jaguar_Land_Rover  = 2,
        ebuffername_CURRENT_Jaguar_Land_Rover  = 3,
        ebuffername_STORED_Jaguar_Land_Rover  = 4,
        ebuffername_PENDING_Jaguar_Land_Rover  = 5,
        ebuffername_MIL_Jaguar_Land_Rover  = 6,
        ebuffername_READINESS_Jaguar_Land_Rover  = 7,
        ebuffername_PERMANENT_Jaguar_Land_Rover  = 8,
        ebuffername_TEMPORARY_Jaguar_Land_Rover  = 9,
        ebuffername_FAIL_SINCE_CLEAR_Jaguar_Land_Rover  = 10,
        ebuffername_KOEO_Jaguar_Land_Rover  = 11,
        ebuffername_KOER_Jaguar_Land_Rover  = 12,
        ebuffername_CONTINUOUS_Jaguar_Land_Rover  = 13,
        ebuffername_PAST_Jaguar_Land_Rover  = 14,
        ebuffername_PRESENT_Jaguar_Land_Rover  = 15,
        ebuffername_CONFIRMED_Jaguar_Land_Rover  = 16,
        ebuffername_CM_Jaguar_Land_Rover  = 17,
        ebuffername_DCHECK_Jaguar_Land_Rover  = 18,
        ebuffername_NOTPRESENT_Jaguar_Land_Rover  = 19,
        ebuffername_ACTIVE_Jaguar_Land_Rover  = 20,
        ebuffername_MEMORY_Jaguar_Land_Rover  = 21,
        ebuffername_INTERMITTENT_Jaguar_Land_Rover  = 22,
        ebuffername_INVALID_Jaguar_Land_Rover  = 23,
        ebuffername_STATIC_Jaguar_Land_Rover  = 24,
        ebuffername_ON_DEMAND_Jaguar_Land_Rover  = 25,
        ebuffername_CURRENT_DTC_SINCE_POWER_UP_Jaguar_Land_Rover  = 26,
        ebuffername_DTC_SUPPORTED_BY_CALIBRATION_Jaguar_Land_Rover  = 27,
        ebuffername_TEST_NOT_PASSED_SINCE_CURRENT_POWER_UP_Jaguar_Land_Rover  = 28,
        ebuffername_TEST_NOT_PASSED_SINCE_DTC_CLEARED_Jaguar_Land_Rover  = 29,
        ebuffername_KOEO_INJECTOR_Jaguar_Land_Rover  = 30,
        ebuffername_KOER_GLOWPLUG_Jaguar_Land_Rover  = 31,
        ebuffername_MAX_Jaguar_Land_Rover  = 255,
        ebuffername_LATCHED_Jaguar_Land_Rover  = 32,
        ebuffername_NOT_____ACTIVE_Jaguar_Land_Rover  = 33,
        ebuffername_TEST_____NOT_____PASS_____SINCE_____CODE_____CLEARED_Jaguar_Land_Rover  = 34,
        ebuffername_FAILED_____SINCE_____CLEAR_Jaguar_Land_Rover  = 35,
        ebuffername_MIL_HISTORY_Jaguar_Land_Rover  = 36,
        ebuffername_LAST_____TEST_____FAILED_Jaguar_Land_Rover  = 37,
        ebuffername_CURRENT_HISTORY_Jaguar_Land_Rover  = 38,
        ebuffername_RECORD_Jaguar_Land_Rover  = 39,
        ebuffername_STORAGE_Jaguar_Land_Rover  = 40,
        ebuffername_CHASSIS_Jaguar_Land_Rover  = 41,
        ebuffername_REGION_Jaguar_Land_Rover  = 42,
        ebuffername_CURRENT_____DTC_Jaguar_Land_Rover  = 43,
        ebuffername_HISTORY_____DTC_Jaguar_Land_Rover  = 44,
        ebuffername_CHASSI_____DTC_Jaguar_Land_Rover  = 45,
        ebuffername_REGION_____DTC_Jaguar_Land_Rover  = 46,
    
    }enumBuffername_Jaguar_Land_Rover;
    
    
    typedef enum _enumDtcdisplaytype_Jaguar_Land_Rover{
        edtcdisplaytype_UNKNOWN_Jaguar_Land_Rover   = 0,
        edtcdisplaytype_DTC_1BYTE_HB_LB_Jaguar_Land_Rover  = 1,
        edtcdisplaytype_DTC_DEC_Jaguar_Land_Rover  = 2,
        edtcdisplaytype_DTC_DEC_2DIGIT_Jaguar_Land_Rover  = 3,
        edtcdisplaytype_DTC_DEC_3DIGIT_Jaguar_Land_Rover  = 4,
        edtcdisplaytype_DTC_DEC_4DIGIT_Jaguar_Land_Rover  = 5,
        edtcdisplaytype_DTC_DEC_5DIGIT_Jaguar_Land_Rover  = 6,
        edtcdisplaytype_DTC_HEX_Jaguar_Land_Rover  = 7,
        edtcdisplaytype_DTC_HEX_2DIGIT_Jaguar_Land_Rover  = 8,
        edtcdisplaytype_DTC_HEX_3DIGIT_Jaguar_Land_Rover  = 9,
        edtcdisplaytype_DTC_HEX_4DIGIT_Jaguar_Land_Rover  = 10,
        edtcdisplaytype_DTC_HEX_5DIGIT_Jaguar_Land_Rover  = 11,
        edtcdisplaytype_DTC_HEX_6DIGIT_Jaguar_Land_Rover  = 12,
        edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_DEC_Jaguar_Land_Rover  = 13,
        edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_DEC_2_Jaguar_Land_Rover  = 14,
        edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_DEC_3_Jaguar_Land_Rover  = 15,
        edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_HEX_Jaguar_Land_Rover  = 16,
        edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_HEX_NO_TRIM_Jaguar_Land_Rover  = 17,
        edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_DEC_Jaguar_Land_Rover  = 18,
        edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_DEC_2_Jaguar_Land_Rover  = 19,
        edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_DEC_3_Jaguar_Land_Rover  = 20,
        edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_HEX_Jaguar_Land_Rover  = 21,
        edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_HEX_NO_TRIM_Jaguar_Land_Rover  = 22,
        edtcdisplaytype_DTC_MAIN_SAE_SUB_1BYTE_DEC_Jaguar_Land_Rover  = 23,
        edtcdisplaytype_DTC_MAIN_SAE_SUB_1BYTE_DEC_NO_TRIM_Jaguar_Land_Rover  = 24,
        edtcdisplaytype_DTC_MAIN_SAE_SUB_1BYTE_HEX_Jaguar_Land_Rover  = 25,
        edtcdisplaytype_DTC_MAIN_SAE_SUB_1BYTE_HEX_NO_TRIM_Jaguar_Land_Rover  = 26,
        edtcdisplaytype_DTC_OEM_SPECIAL_Jaguar_Land_Rover  = 27,
        edtcdisplaytype_DTC_SAE_Jaguar_Land_Rover  = 28,
        edtcdisplaytype_DTC_HONDA_HEX_1BYTE_Jaguar_Land_Rover  = 29,
        edtcdisplaytype_DTC_MAIN_DEC_5DIGIT_SUB_DEC_3_Jaguar_Land_Rover  = 30,
        edtcdisplaytype_DTC_HONDA_MAIN_SUB_HEX_Jaguar_Land_Rover  = 31,
        edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_DEC_NO_TRIM_Jaguar_Land_Rover  = 32,
    
    }enumDtcdisplaytype_Jaguar_Land_Rover;
    
    
    typedef enum _enumInnovagroup_Jaguar_Land_Rover{
        einnovagroup_UNKNOWN_Jaguar_Land_Rover   = 0,
        einnovagroup_GROUP_OBDII_Jaguar_Land_Rover  = 1,
        einnovagroup_GROUP_ABS_Jaguar_Land_Rover  = 2,
        einnovagroup_GROUP_SRS_Jaguar_Land_Rover  = 4,
        einnovagroup_GROUP_ENH_TCM_Jaguar_Land_Rover  = 8,
        einnovagroup_GROUP_ENH_ECM_Jaguar_Land_Rover  = 16,
        einnovagroup_GROUP_ENH_PCM_Jaguar_Land_Rover  = 16,
        einnovagroup_GROUP_OBDI_Jaguar_Land_Rover  = 32,
        einnovagroup_INNOVA_GROUP_UNKNOW_Jaguar_Land_Rover  = 255,
    
    }enumInnovagroup_Jaguar_Land_Rover;
    

#endif