/******************************************************************************************************************
* Engineer    : automatic generated
* Date        : 10/14/2015
* Version   : V01.00.01
********************************************************************************************************************/


#ifndef __ENUMS_Global_H__
#define __ENUMS_Global_H__





typedef enum _enumYear_Global{
    eyear_UNKNOWN_Global   = 0,
    eyear_1996_Global  = 16,
    eyear_1997_Global  = 17,
    eyear_1998_Global  = 18,
    eyear_1999_Global  = 19,
    eyear_2000_Global  = 20,
    eyear_2001_Global  = 21,
    eyear_2002_Global  = 22,
    eyear_2003_Global  = 23,
    eyear_2004_Global  = 24,
    eyear_2005_Global  = 25,
    eyear_2006_Global  = 26,
    eyear_2007_Global  = 27,
    eyear_2008_Global  = 28,
    eyear_2009_Global  = 29,
    eyear_2010_Global  = 30,
    eyear_2011_Global  = 31,
    eyear_2012_Global  = 32,
    eyear_2013_Global  = 33,
    eyear_2014_Global  = 34,
    eyear_2015_Global  = 35,
    eyear_Others_Global  = 65534,
    eyear_MAX_Global  = 65535,
    eyear_2016_Global  = 36,
}enumYear_Global;


typedef enum _enumManufacturer_Global{
    emanufacturer_UNKNOWN_Global   = 0,
    emanufacturer_BMW_Global  = 1,
    emanufacturer_Chrysler_Global  = 2,
    emanufacturer_Ford_Global  = 3,
    emanufacturer_GM_Global  = 4,
    emanufacturer_Honda_Global  = 5,
    emanufacturer_Hyundai_Global  = 6,
    emanufacturer_Mazda_Global  = 10,
    emanufacturer_Mercedes_Benz_Global  = 11,
    emanufacturer_Nissan_Global  = 12,
    emanufacturer_Toyota_Global  = 13,
    emanufacturer_Volkswagen_Global  = 14,
    emanufacturer_Volvo_Global  = 15,
    emanufacturer_Isuzu_Global  = 16,
    emanufacturer_Mitsubishi_Global  = 17,
    emanufacturer_Subaru_Global  = 18,
    emanufacturer_Suzuki_Global  = 19,
    emanufacturer_Porsche_Global  = 20,
    emanufacturer_Others_Global  = 65534,
    emanufacturer_MAX_Global  = 65535,
    emanufacturer_Generic_Global  = 65535,
    emanufacturer_Jaguar_____Land_____Rover_Global  = 21,
    emanufacturer_BYD_Global  = 22,
    emanufacturer_Chery_Global  = 23,
    emanufacturer_Daihatsu_Global  = 24,
    emanufacturer_Ssangyong_Global  = 25,
    emanufacturer_Rover_____Group_Global  = 26,
    emanufacturer_SAIC_Global  = 27,
    emanufacturer_Fiat_Global  = 28,
    emanufacturer_Peugeot_Global  = 29,
    emanufacturer_Daewoo_Global  = 30,
    emanufacturer_Lifan_Global  = 31,
    emanufacturer_Faw_Global  = 32,
    emanufacturer_MG_Global  = 33,
    emanufacturer_Opel_Global  = 34,
    emanufacturer_Renault_Global  = 35,
    emanufacturer_GlobalTruck_Global  = 65533,
}enumManufacturer_Global;


typedef enum _enumMake_Global{
    emake_UNKNOWN_Global   = 0,
    emake_Acura_Global  = 1,
    emake_AM_____General_Global  = 2,
    emake_Audi_Global  = 3,
    emake_BMW_Global  = 4,
    emake_Buick_Global  = 5,
    emake_Cadillac_Global  = 6,
    emake_Chevrolet_Global  = 7,
    emake_Chrysler_Global  = 8,
    emake_Daewoo_Global  = 9,
    emake_Dodge_Global  = 10,
    emake_Eagle_Global  = 11,
    emake_Ford_Global  = 12,
    emake_Geo_Global  = 13,
    emake_GMC_Global  = 14,
    emake_Honda_Global  = 15,
    emake_Hummer_Global  = 16,
    emake_Hyundai_Global  = 17,
    emake_Infiniti_Global  = 18,
    emake_Jaguar_Global  = 19,
    emake_Jeep_Global  = 20,
    emake_Kia_Global  = 21,
    emake_Land_____Rover_Global  = 22,
    emake_Lexus_Global  = 23,
    emake_Lincoln_Global  = 24,
    emake_Mazda_Global  = 25,
    emake_Mercedes_Benz_Global  = 26,
    emake_Mercury_Global  = 27,
    emake_Mini_Global  = 28,
    emake_Nissan_Global  = 29,
    emake_Oldsmobile_Global  = 30,
    emake_Plymouth_Global  = 31,
    emake_Pontiac_Global  = 32,
    emake_Ram_Global  = 33,
    emake_Saab_Global  = 34,
    emake_Saturn_Global  = 35,
    emake_Scion_Global  = 36,
    emake_SRT_Global  = 37,
    emake_Toyota_Global  = 38,
    emake_Volkswagen_Global  = 39,
    emake_Volvo_Global  = 40,
    emake_Fiat_Global  = 41,
    emake_Isuzu_Global  = 42,
    emake_Mitsubishi_Global  = 43,
    emake_Porsche_Global  = 44,
    emake_Smart_Global  = 45,
    emake_Subaru_Global  = 46,
    emake_Suzuki_Global  = 47,
    emake_Others_Global  = 65534,
    emake_MAX_Global  = 65535,
    emake_BYD_Global  = 48,
    emake_Chery_Global  = 49,
    emake_Daihatsu_Global  = 50,
    emake_Ssangyong_Global  = 51,
    emake_MG_Global  = 52,
    emake_Peugeot_Global  = 53,
    emake_Seat_Global  = 54,
    emake_Bentley_Global  = 55,
    emake_Alfa_____Romeo_Global  = 56,
    emake_Citro_n_Global  = 57,
    emake_Lifan_Global  = 58,
    emake_Faw_Global  = 59,
    emake_GM_Global  = 60,
    emake_Opel_Global  = 61,
    emake_Fiat_FCA__Global  = 62,
    emake_Renault_Global  = 63,
}enumMake_Global;


typedef enum _enumField_Global{
    efield_UNKNOWN_Global   = 0,
    efield_year_Global  = 1,
    efield_manufacturer_Global  = 2,
    efield_make_Global  = 3,
    efield_model_Global  = 4,
    efield_engine_Global  = 5,
    efield_trim_Global  = 6,
    efield_transmission_Global  = 7,
    efield_bodycode_Global  = 8,
    efield_vin10toyear_Global  = 9,
    efield_protocol_Global  = 10,
    efield_dlc_Global  = 11,
    efield_dlcvoltage_Global  = 12,
    efield_pd_reLap Dangor_Global  = 13,
    efield_reLap Dangor_Global  = 14,
    efield_vref_Global  = 15,
    efield_uartdata_Global  = 16,
    efield_checksum_Global  = 17,
    efield_inittype_Global  = 18,
    efield_connector_Global  = 19,
    efield_dtcstatuse_Global  = 20,
    efield_buffername_Global  = 21,
    efield_dtcdisplaytype_Global  = 22,
    efield_innovagroup_Global  = 23,
    efield_bmwvariantformula_Global  = 24,
    efield_variant_Global  = 25,
    efield_step_Global  = 26,
    efield_bmwreaddtctype_Global  = 27,
    efield_bmwerasedtctype_Global  = 28,
    efield_bmwparserdtctype_Global  = 29,
    efield_command_Global  = 30,
    efield_bmwvariantdecode_Global  = 31,
    efield_readdtccommandlist_Global  = 32,
    efield_commandlist_Global  = 33,
    efield_ecuinfotype_Global  = 34,
    efield_dtcreadtype_Global  = 35,
    efield_lookuptable_Global  = 36,
    efield_messageid_Global  = 37,
    efield_system_Global  = 38,
    efield_timing_Global  = 39,
    efield_erasetype_Global  = 40,
    efield_subsystem_Global  = 41,
    efield_programid_Global  = 42,
    efield_unitinforesult_Global  = 43,
    efield_displayvisible_Global  = 44,
    efield_hondaoption_Global  = 45,
    efield_ecutype_Global  = 46,
    efield_ecupartnumber_Global  = 47,
    efield_parsertype_Global  = 48,
    efield_formula_Global  = 49,
    efield_convertunit_Global  = 50,
    efield_mercedes_supplier_Global  = 51,
    efield_mercedes_qualifier_Global  = 52,
    efield_modeltype_Global  = 53,
    efield_bm_Global  = 54,
    efield_ecuid_Global  = 55,
    efield_type_Global  = 56,
}enumField_Global;


typedef enum _enumVin10toyear_Global{
    evin10toyear_UNKNOWN_Global   = 0,
    evin10toyear_T_Global  = 16,
    evin10toyear_V_Global  = 17,
    evin10toyear_W_Global  = 18,
    evin10toyear_X_Global  = 19,
    evin10toyear_Y_Global  = 20,
    evin10toyear_1_Global  = 21,
    evin10toyear_2_Global  = 22,
    evin10toyear_3_Global  = 23,
    evin10toyear_4_Global  = 24,
    evin10toyear_5_Global  = 25,
    evin10toyear_6_Global  = 26,
    evin10toyear_7_Global  = 27,
    evin10toyear_8_Global  = 28,
    evin10toyear_9_Global  = 29,
    evin10toyear_A_Global  = 30,
    evin10toyear_B_Global  = 31,
    evin10toyear_C_Global  = 32,
    evin10toyear_D_Global  = 33,
    evin10toyear_E_Global  = 34,
    evin10toyear_F_Global  = 35,
    evin10toyear_G_Global  = 36,
    evin10toyear_H_Global  = 37,
    evin10toyear_J_Global  = 38,
    evin10toyear_K_Global  = 39,
    evin10toyear_L_Global  = 40,
    evin10toyear_M_Global  = 41,
    evin10toyear_N_Global  = 42,
    evin10toyear_P_Global  = 43,
    evin10toyear_R_Global  = 44,
    evin10toyear_S_Global  = 45,
}enumVin10toyear_Global;


typedef enum _enumProtocol_Global{
    eprotocol_UNKNOWN_Global   = 0,
    eprotocol_PROTOCOL_NO_Global  = 0,
    eprotocol_PROTOCOL_VPW_Global  = 1,
    eprotocol_PROTOCOL_PWM_Global  = 2,
    eprotocol_PROTOCOL_ISO9141_Global  = 3,
    eprotocol_PROTOCOL_KW2000_Global  = 4,
    eprotocol_PROTOCOL_CAN500KBAUD_Global  = 5,
    eprotocol_PROTOCOL_XCAN500KBAUD_Global  = 6,
    eprotocol_PROTOCOL_CAN250KBAUD_Global  = 7,
    eprotocol_PROTOCOL_XCAN250KBAUD_Global  = 8,
    eprotocol_PROTOCOL_BOSCH_Global  = 9,
    eprotocol_PROTOCOL_RESERVE_10_Global  = 10,
    eprotocol_PROTOCOL_RESERVE_11_Global  = 11,
    eprotocol_PROTOCOL_RESERVE_12_Global  = 12,
    eprotocol_PROTOCOL_RESERVE_13_Global  = 13,
    eprotocol_PROTOCOL_RESERVE_14_Global  = 14,
    eprotocol_PROTOCOL_KW_Global  = 15,
    eprotocol_PROTOCOL_KW1281_Global  = 16,
    eprotocol_PROTOCOL_MUT_Global  = 17,
    eprotocol_PROTOCOL_CAN_C_UDS_Global  = 18,
    eprotocol_PROTOCOL_CAN_I_UDS_Global  = 19,
    eprotocol_PROTOCOL_RESERVE_20_Global  = 20,
    eprotocol_PROTOCOL_CCD2_Global  = 21,
    eprotocol_PROTOCOL_SDL_Global  = 22,
    eprotocol_PROTOCOL_UBP_Global  = 23,
    eprotocol_PROTOCOL_MCAN_Global  = 24,
    eprotocol_PROTOCOL_MCAN_____UDS_Global  = 25,
    eprotocol_PROTOCOL_H99B_Global  = 26,
    eprotocol_PROTOCOL_95HM_Global  = 27,
    eprotocol_PROTOCOL_92HM_Global  = 28,
    eprotocol_PROTOCOL_CAN_Global  = 29,
    eprotocol_PROTOCOL_RESERVE_30_Global  = 30,
    eprotocol_PROTOCOL_RESERVE_31_Global  = 31,
    eprotocol_PROTOCOL_CCD_Global  = 32,
    eprotocol_PROTOCOL_SCI_Global  = 33,
    eprotocol_PROTOCOL_RESERVE_34_Global  = 34,
    eprotocol_PROTOCOL_RESERVE_35_Global  = 35,
    eprotocol_PROTOCOL_RESERVE_36_Global  = 36,
    eprotocol_PROTOCOL_RESERVE_37_Global  = 37,
    eprotocol_PROTOCOL_RESERVE_38_Global  = 38,
    eprotocol_PROTOCOL_RESERVE_39_Global  = 39,
    eprotocol_PROTOCOL_RESERVE_40_Global  = 40,
    eprotocol_PROTOCOL_RESERVE_41_Global  = 41,
    eprotocol_PROTOCOL_OBD1_Global  = 42,
    eprotocol_PROTOCOL_RESERVE_43_Global  = 43,
    eprotocol_PROTOCOL_RESERVE_44_Global  = 44,
    eprotocol_PROTOCOL_RESERVE_45_Global  = 45,
    eprotocol_PROTOCOL_RESERVE_46_Global  = 46,
    eprotocol_PROTOCOL_RESERVE_47_Global  = 47,
    eprotocol_PROTOCOL_DDL1_Global  = 48,
    eprotocol_PROTOCOL_SWCAN_Global  = 49,
    eprotocol_PROTOCOL_RESERVE_50_Global  = 50,
    eprotocol_PROTOCOL_MB_ISO_Global  = 51,
    eprotocol_PROTOCOL_KWFB_Global  = 52,
    eprotocol_PROTOCOL_BMW_CAN_Global  = 53,
    eprotocol_PROTOCOL_TPCAN_2_0_Global  = 54,
    eprotocol_PROTOCOL_TPCAN_1_6_KW1281_Global  = 55,
    eprotocol_PROTOCOL_TPCAN_1_6_KW2000_Global  = 56,
    eprotocol_PROTOCOL_KWSSM_Global  = 57,
    eprotocol_PROTOCOL_DDL2_Global  = 58,
    eprotocol_PROTOCOL_DS2_Global  = 59,
    eprotocol_PROTOCOL_CAN_UDS_Global  = 60,
    eprotocol_PROTOCOL_CANUDS_Global  = 60,
    eprotocol_PROTOCOL_CAN_D2_Global  = 61,
    eprotocol_PROTOCOL_CAN_GGD_Global  = 62,
    eprotocol_PROTOCOL_ALDL_Global  = 63,
    eprotocol_PROTOCOL_GMLAN_Global  = 64,
    eprotocol_PROTOCOL_MAX_Global  = 65535,
    eprotocol_PROTOCOL_CAN_C_Global  = 65,
    eprotocol_PROTOCOL_TCAN_Global  = 66,
    eprotocol_PROTOCOL_DS1_Global  = 70,
    eprotocol_PROTOCOL_DS2_MID_Global  = 71,
    eprotocol_PROTOCOL_D2_Global  = 73,
    eprotocol_PROTOCOL_GGD_Global  = 74,
    eprotocol_Suzuki_SDL_Global  = 75,
    eprotocol_PROTOCOL_SUBARU_KWP_4800_Global  = 76,
    eprotocol_PROTOCOL_SUBARU_FHICAN_Global  = 77,
    eprotocol_PROTOCOL_SUBARU_TMC_Global  = 78,
    eprotocol_PROTOCOL_SUBARU_KWP_10400_Global  = 79,
    eprotocol_PROTOCOL_SUBARU_KWP_1953_Global  = 80,
    eprotocol_PROTOCOL_J1708_Global  = 81,
    eprotocol_PROTOCOL_J1939_Global  = 82,
}enumProtocol_Global;


typedef enum _enumDlc_Global{
    edlc_UNKNOWN_Global   = 0,
    edlc_PIN1_Global  = 2,
    edlc_PIN1_INV_Global  = 3,
    edlc_PIN2_Global  = 4,
    edlc_PIN2_INV_Global  = 5,
    edlc_PIN3_Global  = 6,
    edlc_PIN3_INV_Global  = 7,
    edlc_PIN4_Global  = 8,
    edlc_PIN4_INV_Global  = 9,
    edlc_PIN5_Global  = 10,
    edlc_PIN5_INV_Global  = 11,
    edlc_PIN6_Global  = 12,
    edlc_PIN6_INV_Global  = 13,
    edlc_PIN7_Global  = 14,
    edlc_PIN7_INV_Global  = 15,
    edlc_PIN8_Global  = 16,
    edlc_PIN8_INV_Global  = 17,
    edlc_PIN9_Global  = 18,
    edlc_PIN9_INV_Global  = 19,
    edlc_PIN10_Global  = 20,
    edlc_PIN10_INV_Global  = 21,
    edlc_PIN11_Global  = 22,
    edlc_PIN11_INV_Global  = 23,
    edlc_PIN12_Global  = 24,
    edlc_PIN12_INV_Global  = 25,
    edlc_PIN13_Global  = 26,
    edlc_PIN13_INV_Global  = 27,
    edlc_PIN14_Global  = 28,
    edlc_PIN14_INV_Global  = 29,
    edlc_PIN15_Global  = 30,
    edlc_PIN15_INV_Global  = 31,
    edlc_PIN3_INV_OBD1_Global  = 32,
    edlc_PIN7_OBD1_Global  = 33,
    edlc_PIN15_OBD1_Global  = 34,
    edlc_CCD_3_11_Global  = 35,
    edlc_PIN_NA_Global  = 255,
    edlc_PIN16_Global  = 32,
    edlc_PIN20_Global  = 33,
    edlc_PIN22_Global  = 34,
    edlc_PIN23_Global  = 35,
    edlc_PIN24_Global  = 36,
    edlc_PIN25_Global  = 37,
    edlc_PIN28_Global  = 38,
    edlc_PIN30_Global  = 39,
    edlc_PIN32_Global  = 40,
    edlc_PIN33_Global  = 41,
    edlc_PIN34_Global  = 42,
    edlc_PIN35_Global  = 43,
    edlc_PIN36_Global  = 44,
    edlc_PIN17_Global  = 45,
    edlc_PIN15_INV_OBD1_Global  = 46,
    edlc_PIN9_OBD1_Global  = 47,
    edlc_PIN2_OBD1_Global  = 48,
    edlc_PIN8_OBD1_Global  = 49,
    edlc_PIN14_OBD1_Global  = 50,
    edlc_PIN11_OBD1_Global  = 51,
    edlc_PIN6_OBD1_Global  = 52,
}enumDlc_Global;


typedef enum _enumDlcvoltage_Global{
    edlcvoltage_UNKNOWN_Global   = 0,
    edlcvoltage_LEVEL_FLOAT_Global  = 1,
    edlcvoltage_LEVEL_5V_Global  = 2,
    edlcvoltage_LEVEL_8V_Global  = 3,
    edlcvoltage_LEVEL_12V_Global  = 4,
    edlcvoltage_LEVEL_24V_Global  = 5,
    edlcvoltage_LEVEL_36V_Global  = 6,
}enumDlcvoltage_Global;


typedef enum _enumPd_ReLap Dangor_Global{
    epd_reLap Dangor_UNKNOWN_Global   = 0,
    epd_reLap Dangor_PD_NONE_Global  = 0,
    epd_reLap Dangor_PD_OPEN_Global  = 1,
    epd_reLap Dangor_PD_2K8_Global  = 2,
    epd_reLap Dangor_PD_3K9_Global  = 3,
    epd_reLap Dangor_PD_10K_Global  = 4,
}enumPd_ReLap Dangor_Global;


typedef enum _enumReLap Dangor_Global{
    ereLap Dangor_UNKNOWN_Global   = 0,
    ereLap Dangor_PU_NONE_Global  = 0,
    ereLap Dangor_PU_511_Global  = 1,
    ereLap Dangor_PU_2K7_Global  = 2,
    ereLap Dangor_PU_4K7_Global  = 4,
    ereLap Dangor_PU_1K_Global  = 8,
    ereLap Dangor_PU_2K_Global  = 16,
}enumReLap Dangor_Global;


typedef enum _enumVref_Global{
    evref_UNKNOWN_Global   = 0,
    evref_VREF_NA_Global  = 0,
    evref_VREF_AUTO_Global  = 1,
    evref_VREF_1V5_Global  = 2,
    evref_VREF_2V5_Global  = 3,
}enumVref_Global;


typedef enum _enumUartdata_Global{
    euartdata_UNKNOWN_Global   = 0,
    euartdata_DATA8BIT_NO_PARITY_Global  = 0,
    euartdata_DATA8BIT_EVEN_PARITY_Global  = 1,
    euartdata_DATA8BIT_ODD_PARIRY_Global  = 2,
}enumUartdata_Global;


typedef enum _enumChecksum_Global{
    echecksum_UNKNOWN_Global   = 0,
    echecksum_CS_NONE_Global  = 0,
    echecksum_CS_NORMAL_1BYTE_Global  = 1,
    echecksum_CS_INVERT_1BYTE_Global  = 2,
    echecksum_CS_NORMAL_2BYTE_Global  = 3,
    echecksum_CS_CRC_1D_Global  = 4,
    echecksum_CS_CRC_01_Global  = 5,
}enumChecksum_Global;


typedef enum _enumInittype_Global{
    einittype_UNKNOWN_Global   = 0,
    einittype_INIT_NONE_Global  = 0,
    einittype_INIT_FIVEBAUDS_Global  = 1,
    einittype_INIT_FASTBAUDS_Global  = 2,
    einittype_INIT_MAX_Global  = 3,
}enumInittype_Global;


typedef enum _enumConnector_Global{
    econnector_UNKNOWN_Global   = 0,
    econnector_NONE_Global  = 0,
    econnector_OBDII_Global  = 1,
    econnector_GM_OBD1_Global  = 2,
    econnector_FORD_OBD1_Global  = 3,
    econnector_CHRYSLER_OBD1_Global  = 4,
    econnector_TOYOTA_OBD1_Global  = 5,
    econnector_HONDA_OBD1_Global  = 6,
    econnector_KIA_20_PINS_Global  = 7,
    econnector_TOYOTA_17_PINS_Global  = 8,
    econnector_TOYOTA_22_PINS_Global  = 9,
    econnector_BMW_20_PINS_Global  = 10,
    econnector_NISSAN_14_PINS_Global  = 11,
    econnector_BMW_16_PINS_Global  = 12,
    econnector_BENZ_38_PINS_Global  = 13,
    econnector_CHRYSLER_16_PINS_Global  = 14,
    econnector_BENZ_14PIN_PINS_Global  = 15,
    econnector_MAZDA_17_PINS_Global  = 16,
    econnector_MIT_12_16_PINS_Global  = 17,
    econnector_NISSAN_14_TSURU_Global  = 18,
    econnector_MAX_Global  = 65535,
    econnector_OEM_Global  = 19,
    econnector_Hyundai_12_Global  = 20,
    econnector_Kia_20_Global  = 21,
    econnector_NISSAN_14_Global  = 22,
    econnector_TOYOTA_17_22_Global  = 23,
    econnector_BMW_OEM_20_Global  = 24,
    econnector_BENZ_14_Global  = 25,
    econnector_BMW_20_Global  = 26,
    econnector_BENZ_38_Global  = 27,
}enumConnector_Global;


typedef enum _enumDtcstatuse_Global{
    edtcstatuse_UNKNOWN_Global   = 0,
    edtcstatuse_Type_Dtc_Status_NA_Global  = 0,
    edtcstatuse_Type_Dtc_Status_General_Global  = 1,
    edtcstatuse_Type_Dtc_Status_Chrysler_CAN_Global  = 2,
    edtcstatuse_Type_Dtc_Status_Chrysler_CAN_UDS_Global  = 3,
    edtcstatuse_Type_Dtc_Status_GM_GMLAN_DOC_Global  = 4,
    edtcstatuse_Type_Dtc_Status_HondaBody_KW_Global  = 5,
    edtcstatuse_Type_Dtc_Status_Hyundai_1_Global  = 6,
    edtcstatuse_Type_Dtc_Status_Hyundai_2_Global  = 7,
    edtcstatuse_Type_Dtc_Status_VAG_0_Global  = 8,
    edtcstatuse_Type_Dtc_Status_VAG_1_Global  = 9,
    edtcstatuse_Type_Dtc_Status_VAG_2_Global  = 10,
    edtcstatuse_Type_Dtc_Status_VAG_3_Global  = 11,
    edtcstatuse_Type_Dtc_Status_VAG_4_Global  = 12,
    edtcstatuse_Type_Dtc_Status_VAG_5_Global  = 13,
    edtcstatuse_Type_Dtc_Status_VAG_6_Global  = 14,
    edtcstatuse_Type_Dtc_Status_VAG_7_Global  = 15,
    edtcstatuse_Type_Dtc_Status_Volvo_1_Global  = 16,
    edtcstatuse_Type_Dtc_Status_Mercedes_CANUDS_Global  = 17,
    edtcstatuse_Type_Dtc_Status_Mercedes_KW2000_CAN_Global  = 18,
    edtcstatuse_Type_Dtc_Status_Mercedes_KWFB_Global  = 19,
    edtcstatuse_Type_Dtc_Status_Volvo_2_Global  = 20,
    edtcstatuse_Type_Dtc_Status_Nissan_Byte_Global  = 21,
    edtcstatuse_Type_Dtc_Status_Nissan_Bit_Global  = 22,
    edtcstatuse_Type_Dtc_Status_Hyundai_SRS_0207_Global  = 23,
}enumDtcstatuse_Global;


typedef enum _enumBuffername_Global{
    ebuffername_UNKNOWN_Global   = 0,
    ebuffername_NONE_Global  = 0,
    ebuffername_HISTORY_Global  = 1,
    ebuffername_HISTORICAL_Global  = 2,
    ebuffername_CURRENT_Global  = 3,
    ebuffername_STORED_Global  = 4,
    ebuffername_PENDING_Global  = 5,
    ebuffername_MIL_Global  = 6,
    ebuffername_READINESS_Global  = 7,
    ebuffername_PERMANENT_Global  = 8,
    ebuffername_TEMPORARY_Global  = 9,
    ebuffername_FAIL_SINCE_CLEAR_Global  = 10,
    ebuffername_KOEO_Global  = 11,
    ebuffername_KOER_Global  = 12,
    ebuffername_CONTINUOUS_Global  = 13,
    ebuffername_PAST_Global  = 14,
    ebuffername_PRESENT_Global  = 15,
    ebuffername_CONFIRMED_Global  = 16,
    ebuffername_CM_Global  = 17,
    ebuffername_DCHECK_Global  = 18,
    ebuffername_NOTPRESENT_Global  = 19,
    ebuffername_ACTIVE_Global  = 20,
    ebuffername_MEMORY_Global  = 21,
    ebuffername_INTERMITTENT_Global  = 22,
    ebuffername_INVALID_Global  = 23,
    ebuffername_STATIC_Global  = 24,
    ebuffername_ON_DEMAND_Global  = 25,
    ebuffername_CURRENT_DTC_SINCE_POWER_UP_Global  = 26,
    ebuffername_DTC_SUPPORTED_BY_CALIBRATION_Global  = 27,
    ebuffername_TEST_NOT_PASSED_SINCE_CURRENT_POWER_UP_Global  = 28,
    ebuffername_TEST_NOT_PASSED_SINCE_DTC_CLEARED_Global  = 29,
    ebuffername_KOEO_INJECTOR_Global  = 30,
    ebuffername_KOER_GLOWPLUG_Global  = 31,
    ebuffername_MAX_Global  = 255,
    ebuffername_LATCHED_Global  = 32,
    ebuffername_NOT_____ACTIVE_Global  = 33,
    ebuffername_Test_____not_____Pass_____Since_____Code_____Cleared_Global  = 34,
    ebuffername_Failed_____Since_____Clear_Global  = 35,
    ebuffername_MIL_History_Global  = 36,
    ebuffername_Last_____Test_____Failed_Global  = 37,
    ebuffername_Current_History_Global  = 38,
    ebuffername_Record_Global  = 39,
    ebuffername_Storage_Global  = 40,
    ebuffername_Chassis_Global  = 41,
    ebuffername_Region_Global  = 42,
    ebuffername_Current_____DTC_Global  = 43,
    ebuffername_History_____DTC_Global  = 44,
    ebuffername_Chassi_____DTC_Global  = 45,
    ebuffername_Region_____DTC_Global  = 46,
    ebuffername_Provisional_Global  = 47,
}enumBuffername_Global;


typedef enum _enumDtcdisplaytype_Global{
    edtcdisplaytype_UNKNOWN_Global   = 0,
    edtcdisplaytype_DTC_1BYTE_HB_LB_Global  = 1,
    edtcdisplaytype_DTC_DEC_Global  = 2,
    edtcdisplaytype_DTC_DEC_2DIGIT_Global  = 3,
    edtcdisplaytype_DTC_DEC_3DIGIT_Global  = 4,
    edtcdisplaytype_DTC_DEC_4DIGIT_Global  = 5,
    edtcdisplaytype_DTC_DEC_5DIGIT_Global  = 6,
    edtcdisplaytype_DTC_HEX_Global  = 7,
    edtcdisplaytype_DTC_HEX_2DIGIT_Global  = 8,
    edtcdisplaytype_DTC_HEX_3DIGIT_Global  = 9,
    edtcdisplaytype_DTC_HEX_4DIGIT_Global  = 10,
    edtcdisplaytype_DTC_HEX_5DIGIT_Global  = 11,
    edtcdisplaytype_DTC_HEX_6DIGIT_Global  = 12,
    edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_DEC_Global  = 13,
    edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_DEC_2_Global  = 14,
    edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_DEC_3_Global  = 15,
    edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_HEX_Global  = 16,
    edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_HEX_NO_TRIM_Global  = 17,
    edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_DEC_Global  = 18,
    edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_DEC_2_Global  = 19,
    edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_DEC_3_Global  = 20,
    edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_HEX_Global  = 21,
    edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_HEX_NO_TRIM_Global  = 22,
    edtcdisplaytype_DTC_MAIN_SAE_SUB_1BYTE_DEC_Global  = 23,
    edtcdisplaytype_DTC_MAIN_SAE_SUB_1BYTE_DEC_NO_TRIM_Global  = 24,
    edtcdisplaytype_DTC_MAIN_SAE_SUB_1BYTE_HEX_Global  = 25,
    edtcdisplaytype_DTC_MAIN_SAE_SUB_1BYTE_HEX_NO_TRIM_Global  = 26,
    edtcdisplaytype_DTC_OEM_SPECIAL_Global  = 27,
    edtcdisplaytype_DTC_SAE_Global  = 28,
    edtcdisplaytype_DTC_HONDA_HEX_1BYTE_Global  = 29,
    edtcdisplaytype_DTC_MAIN_DEC_5DIGIT_SUB_DEC_3_Global  = 30,
    edtcdisplaytype_DTC_HONDA_MAIN_SUB_HEX_Global  = 31,
    edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_DEC_NO_TRIM_Global  = 32,
    edtcdisplaytype_DTC_TRUCK_J1708_Global  = 33,
    edtcdisplaytype_DTC_TRUCK_J1939_Global  = 34,
}enumDtcdisplaytype_Global;


typedef enum _enumInnovagroup_Global{
    einnovagroup_UNKNOWN_Global   = 0,
    einnovagroup_GROUP_OBDII_Global  = 1,
    einnovagroup_GROUP_ABS_Global  = 2,
    einnovagroup_GROUP_SRS_Global  = 4,
    einnovagroup_GROUP_ENH_TCM_Global  = 8,
    einnovagroup_GROUP_ENH_ECM_Global  = 16,
    einnovagroup_GROUP_ENH_PCM_Global  = 16,
    einnovagroup_GROUP_OBDI_Global  = 32,
    einnovagroup_INNOVA_GROUP_UNKNOW_Global  = 255,
}enumInnovagroup_Global;


#endif