/******************************************************************************************************************
* Engineer    : automatic generated
* Date        : 10/1/2015
* Version   : V01.00.01
********************************************************************************************************************/


#ifndef __ENUMS_Jaguar_____Land_____Rover_H__
#define __ENUMS_Jaguar_____Land_____Rover_H__



    
    typedef enum _enumCommand_Jaguar_____Land_____Rover{
        ecommand_UNKNOWN_Jaguar_____Land_____Rover   = 0,
        ecommand_03_____22_____F1_____90_____00_____00_____00_____00_Jaguar_____Land_____Rover  = 1,
        ecommand_09_Jaguar_____Land_____Rover  = 2,
        ecommand_06_Jaguar_____Land_____Rover  = 3,
        ecommand_03_____22_____00_____02_Jaguar_____Land_____Rover  = 4,
        ecommand_01_____20_Jaguar_____Land_____Rover  = 5,
        ecommand_3E_Jaguar_____Land_____Rover  = 6,
        ecommand_82_Jaguar_____Land_____Rover  = 7,
        ecommand_3E_____00_____00_Jaguar_____Land_____Rover  = 8,
        ecommand_00_Jaguar_____Land_____Rover  = 9,
        ecommand_9F_Jaguar_____Land_____Rover  = 10,
        ecommand_03_____22_____F1_____03_____00_____00_____00_____00_Jaguar_____Land_____Rover  = 11,
        ecommand_04_____14_____FF_____FF_____FF_____00_____00_____00_Jaguar_____Land_____Rover  = 12,
        ecommand_03_____19_____02_____AF_____00_____00_____00_____00_Jaguar_____Land_____Rover  = 13,
        ecommand_05_Jaguar_____Land_____Rover  = 14,
        ecommand_07_Jaguar_____Land_____Rover  = 15,
        ecommand_02_____10_____02_Jaguar_____Land_____Rover  = 16,
        ecommand_01_____04_Jaguar_____Land_____Rover  = 17,
        ecommand_01_____14_Jaguar_____Land_____Rover  = 18,
        ecommand_01_____03_Jaguar_____Land_____Rover  = 19,
        ecommand_03_____13_____02_____00_Jaguar_____Land_____Rover  = 20,
        ecommand_03_____13_____12_____FE_Current_____trip_Jaguar_____Land_____Rover  = 21,
        ecommand_03_____13_____12_____FE_Previous_____trip_Jaguar_____Land_____Rover  = 22,
        ecommand_81_Jaguar_____Land_____Rover  = 23,
        ecommand_14_____FF_____FF_Jaguar_____Land_____Rover  = 24,
        ecommand_18_____02_____FF_____FF_Jaguar_____Land_____Rover  = 25,
        ecommand_10_____87_Jaguar_____Land_____Rover  = 26,
        ecommand_14_____80_____00_Jaguar_____Land_____Rover  = 27,
        ecommand_18_____00_____80_____00_Jaguar_____Land_____Rover  = 28,
        ecommand_10_____81_Jaguar_____Land_____Rover  = 29,
        ecommand_A0_____00_Jaguar_____Land_____Rover  = 30,
        ecommand_12_____04_____00_Jaguar_____Land_____Rover  = 31,
        ecommand_12_____04_____05_Jaguar_____Land_____Rover  = 32,
        ecommand_12_____04_____A0_Jaguar_____Land_____Rover  = 33,
        ecommand_12_____05_____14_____00_Jaguar_____Land_____Rover  = 34,
        ecommand_12_____05_____14_____01_Jaguar_____Land_____Rover  = 35,
        ecommand_19_____04_____00_Jaguar_____Land_____Rover  = 36,
        ecommand_04_____01_Jaguar_____Land_____Rover  = 37,
        ecommand_1A_____9A_Jaguar_____Land_____Rover  = 38,
        ecommand_1A_____9B_Jaguar_____Land_____Rover  = 39,
        ecommand_1A_____9C_Jaguar_____Land_____Rover  = 40,
        ecommand_1A_____9D_Jaguar_____Land_____Rover  = 41,
        ecommand_1A_____87_Jaguar_____Land_____Rover  = 42,
    
    }enumCommand_Jaguar_____Land_____Rover;
    
    
    typedef enum _enumReaddtccommandlist_Jaguar_____Land_____Rover{
        ereaddtccommandlist_UNKNOWN_Jaguar_____Land_____Rover   = 0,
        ereaddtccommandlist_03_____19_____02_____AF_____00_____00_____00_____00_Permanent___1_Jaguar_____Land_____Rover  = 1,
        ereaddtccommandlist_07_Confirmed___2_Jaguar_____Land_____Rover  = 2,
        ereaddtccommandlist_01_____03_Stored___03_____13_____02_____00_Permanent___03_____13_____12_____FE_Current_____trip___03_____13_____12_____FE_Previous_____trip___3_Jaguar_____Land_____Rover  = 3,
        ereaddtccommandlist_18_____02_____FF_____FF___4_Jaguar_____Land_____Rover  = 4,
        ereaddtccommandlist_18_____00_____80_____00___5_Jaguar_____Land_____Rover  = 5,
        ereaddtccommandlist_A0_____00___6_Jaguar_____Land_____Rover  = 6,
        ereaddtccommandlist_12_____05_____14_____00___12_____05_____14_____01___7_Jaguar_____Land_____Rover  = 7,
        ereaddtccommandlist_12_____05_____14_____00___12_____05_____14_____01___8_Jaguar_____Land_____Rover  = 8,
        ereaddtccommandlist_04_____01___9_Jaguar_____Land_____Rover  = 9,
    
    }enumReaddtccommandlist_Jaguar_____Land_____Rover;
    
    
    typedef enum _enumCommandlist_Jaguar_____Land_____Rover{
        ecommandlist_UNKNOWN_Jaguar_____Land_____Rover   = 0,
        ecommandlist_03_____22_____F1_____03_____00_____00_____00_____00_Jaguar_____Land_____Rover  = 1,
        ecommandlist_04_____14_____FF_____FF_____FF_____00_____00_____00_Jaguar_____Land_____Rover  = 2,
        ecommandlist_09_Jaguar_____Land_____Rover  = 3,
        ecommandlist_05_Jaguar_____Land_____Rover  = 4,
        ecommandlist_02_____10_____02_Jaguar_____Land_____Rover  = 5,
        ecommandlist_01_____04___01_____14_Jaguar_____Land_____Rover  = 6,
        ecommandlist_81_Jaguar_____Land_____Rover  = 7,
        ecommandlist_14_____FF_____FF_Jaguar_____Land_____Rover  = 8,
        ecommandlist_10_____87_Jaguar_____Land_____Rover  = 9,
        ecommandlist_14_____80_____00_Jaguar_____Land_____Rover  = 10,
        ecommandlist_10_____81_Jaguar_____Land_____Rover  = 11,
        ecommandlist_12_____04_____00_Jaguar_____Land_____Rover  = 12,
        ecommandlist_12_____04_____05___12_____04_____A0_Jaguar_____Land_____Rover  = 13,
        ecommandlist_19_____04_____00_Jaguar_____Land_____Rover  = 14,
        ecommandlist_00_Jaguar_____Land_____Rover  = 15,
        ecommandlist_1A_____9A___1A_____9B___1A_____9C___1A_____9D___1A_____87_Jaguar_____Land_____Rover  = 16,
    
    }enumCommandlist_Jaguar_____Land_____Rover;
    
    
    typedef enum _enumEcuinfotype_Jaguar_____Land_____Rover{
        eecuinfotype_UNKNOWN_Jaguar_____Land_____Rover   = 0,
    
    }enumEcuinfotype_Jaguar_____Land_____Rover;
    
    
    typedef enum _enumDtcreadtype_Jaguar_____Land_____Rover{
        edtcreadtype_UNKNOWN_Jaguar_____Land_____Rover   = 0,
        edtcreadtype_ReadDTCType_ID0001_Jaguar_____Land_____Rover  = 1,
    
    }enumDtcreadtype_Jaguar_____Land_____Rover;
    
    
    typedef enum _enumLookuptable_Jaguar_____Land_____Rover{
        elookuptable_UNKNOWN_Jaguar_____Land_____Rover   = 0,
    
    }enumLookuptable_Jaguar_____Land_____Rover;
    
    
    typedef enum _enumMessageid_Jaguar_____Land_____Rover{
        emessageid_UNKNOWN_Jaguar_____Land_____Rover   = 0,
        emessageid_LangJag_RLM_Can_001_Jaguar_____Land_____Rover  = 1,
        emessageid_LangJag_AAM_Can_001_Jaguar_____Land_____Rover  = 2,
        emessageid_LangJag_AAM_Can_002_Jaguar_____Land_____Rover  = 3,
        emessageid_LangJag_ABS_Can_001_Jaguar_____Land_____Rover  = 4,
        emessageid_LangJag_ACM_Can_001_Jaguar_____Land_____Rover  = 5,
        emessageid_LangJag_ACM_Can_002_Jaguar_____Land_____Rover  = 6,
        emessageid_LangJag_AHCM_Can_001_Jaguar_____Land_____Rover  = 7,
        emessageid_LangJag_AHCM_Can_002_Jaguar_____Land_____Rover  = 8,
        emessageid_LangJag_AHU_Can_001_Jaguar_____Land_____Rover  = 9,
        emessageid_LangJag_APIM_Can_001_Jaguar_____Land_____Rover  = 10,
        emessageid_LangJag_APIM_Can_002_Jaguar_____Land_____Rover  = 11,
        emessageid_LangJag_ARCM_Can_001_Jaguar_____Land_____Rover  = 12,
        emessageid_LangJag_ARCM_Can_002_Jaguar_____Land_____Rover  = 13,
        emessageid_LangJag_ATCM_Can_001_Jaguar_____Land_____Rover  = 14,
        emessageid_LangJag_ATCM_Can_002_Jaguar_____Land_____Rover  = 15,
        emessageid_LangJag_AUCM_Can_001_Jaguar_____Land_____Rover  = 16,
        emessageid_LangJag_AUCM_Can_002_Jaguar_____Land_____Rover  = 17,
        emessageid_LangJag_AWDCM_Can_001_Jaguar_____Land_____Rover  = 18,
        emessageid_LangJag_BCM_Can_001_Jaguar_____Land_____Rover  = 19,
        emessageid_LangJag_BCM_Can_002_Jaguar_____Land_____Rover  = 20,
        emessageid_LangJag_BCM_Can_003_Jaguar_____Land_____Rover  = 21,
        emessageid_LangJag_BCMB_Can_001_Jaguar_____Land_____Rover  = 22,
        emessageid_LangJag_BPM_Can_001_Jaguar_____Land_____Rover  = 23,
        emessageid_LangJag_CAV_Can_001_Jaguar_____Land_____Rover  = 24,
        emessageid_LangJag_CCM_Can_001_Jaguar_____Land_____Rover  = 25,
        emessageid_LangJag_CCM_Can_002_Jaguar_____Land_____Rover  = 26,
        emessageid_LangJag_CDP_Can_001_Jaguar_____Land_____Rover  = 27,
        emessageid_LangJag_CDP_Can_002_Jaguar_____Land_____Rover  = 28,
        emessageid_LangJag_CHCM_Can_001_Jaguar_____Land_____Rover  = 29,
        emessageid_LangJag_CHCMB_Can_001_Jaguar_____Land_____Rover  = 30,
        emessageid_LangJag_DABM_Can_001_Jaguar_____Land_____Rover  = 31,
        emessageid_LangJag_DABM_Can_002_Jaguar_____Land_____Rover  = 32,
        emessageid_LangJag_DACMC_Can_001_Jaguar_____Land_____Rover  = 33,
        emessageid_LangJag_DACMC_Can_002_Jaguar_____Land_____Rover  = 34,
        emessageid_LangJag_DCSM_Can_001_Jaguar_____Land_____Rover  = 35,
        emessageid_LangJag_DCSM_Can_002_Jaguar_____Land_____Rover  = 36,
        emessageid_LangJag_DDM_Can_001_Jaguar_____Land_____Rover  = 37,
        emessageid_LangJag_DSM_Can_001_Jaguar_____Land_____Rover  = 38,
        emessageid_LangJag_DSM_Can_002_Jaguar_____Land_____Rover  = 39,
        emessageid_LangJag_FACP_Can_001_Jaguar_____Land_____Rover  = 40,
        emessageid_LangJag_FCDIM_Can_001_Jaguar_____Land_____Rover  = 41,
        emessageid_LangJag_FCDIM_Can_002_Jaguar_____Land_____Rover  = 42,
        emessageid_LangJag_FCIM_Can_001_Jaguar_____Land_____Rover  = 43,
        emessageid_LangJag_FCIMB_Can_001_Jaguar_____Land_____Rover  = 44,
        emessageid_LangJag_FCIMC_Can_001_Jaguar_____Land_____Rover  = 45,
        emessageid_LangJag_FEM_Can_001_Jaguar_____Land_____Rover  = 46,
        emessageid_LangJag_FEM_Can_002_Jaguar_____Land_____Rover  = 47,
        emessageid_LangJag_FEM_Can_003_Jaguar_____Land_____Rover  = 48,
        emessageid_LangJag_FLM_Can_001_Jaguar_____Land_____Rover  = 49,
        emessageid_LangJag_FTCM_Can_001_Jaguar_____Land_____Rover  = 50,
        emessageid_LangJag_FTCM_Can_002_Jaguar_____Land_____Rover  = 51,
        emessageid_LangJag_FTCMB_Can_001_Jaguar_____Land_____Rover  = 52,
        emessageid_LangJag_GPSM_Can_001_Jaguar_____Land_____Rover  = 53,
        emessageid_LangJag_GSM_Can_001_Jaguar_____Land_____Rover  = 54,
        emessageid_LangJag_GSMB_Can_001_Jaguar_____Land_____Rover  = 55,
        emessageid_LangJag_GWM_Can_001_Jaguar_____Land_____Rover  = 56,
        emessageid_LangJag_GWM_Can_002_Jaguar_____Land_____Rover  = 57,
        emessageid_LangJag_HCM_Can_001_Jaguar_____Land_____Rover  = 58,
        emessageid_LangJag_HCMB_Can_001_Jaguar_____Land_____Rover  = 59,
        emessageid_LangJag_HUD_Can_001_Jaguar_____Land_____Rover  = 60,
        emessageid_LangJag_HVAC_Can_001_Jaguar_____Land_____Rover  = 61,
        emessageid_LangJag_HVAC_Can_002_Jaguar_____Land_____Rover  = 62,
        emessageid_LangJag_ICM_Can_001_Jaguar_____Land_____Rover  = 63,
        emessageid_LangJag_ICM_Can_002_Jaguar_____Land_____Rover  = 64,
        emessageid_LangJag_ICS_Can_001_Jaguar_____Land_____Rover  = 65,
        emessageid_LangJag_IPC_Can_001_Jaguar_____Land_____Rover  = 66,
        emessageid_LangJag_IPC_Can_002_Jaguar_____Land_____Rover  = 67,
        emessageid_LangJag_IPC_Can_003_Jaguar_____Land_____Rover  = 68,
        emessageid_LangJag_IPC_Can_004_Jaguar_____Land_____Rover  = 69,
        emessageid_LangJag_IPMB_Can_001_Jaguar_____Land_____Rover  = 70,
        emessageid_LangJag_NCM_Can_001_Jaguar_____Land_____Rover  = 71,
        emessageid_LangJag_NCM_Can_002_Jaguar_____Land_____Rover  = 72,
        emessageid_LangJag_NCM_Can_003_Jaguar_____Land_____Rover  = 73,
        emessageid_LangJag_OCS_Can_001_Jaguar_____Land_____Rover  = 74,
        emessageid_LangJag_OCS_Can_002_Jaguar_____Land_____Rover  = 75,
        emessageid_LangJag_PAM_Can_001_Jaguar_____Land_____Rover  = 76,
        emessageid_LangJag_PAM_Can_002_Jaguar_____Land_____Rover  = 77,
        emessageid_LangJag_PAM_Can_003_Jaguar_____Land_____Rover  = 78,
        emessageid_LangJag_PBM_Can_001_Jaguar_____Land_____Rover  = 79,
        emessageid_LangJag_PBM_Can_002_Jaguar_____Land_____Rover  = 80,
        emessageid_LangJag_PBM_Can_003_Jaguar_____Land_____Rover  = 81,
        emessageid_LangJag_PCM_Can_001_Jaguar_____Land_____Rover  = 82,
        emessageid_LangJag_PCM_Can_002_Jaguar_____Land_____Rover  = 83,
        emessageid_LangJag_PDM_Can_001_Jaguar_____Land_____Rover  = 84,
        emessageid_LangJag_PSCM_Can_001_Jaguar_____Land_____Rover  = 85,
        emessageid_LangJag_PSM_Can_001_Jaguar_____Land_____Rover  = 86,
        emessageid_LangJag_PSM_Can_002_Jaguar_____Land_____Rover  = 87,
        emessageid_LangJag_RBM_Can_001_Jaguar_____Land_____Rover  = 88,
        emessageid_LangJag_RBM_Can_002_Jaguar_____Land_____Rover  = 89,
        emessageid_LangJag_RCM_Can_001_Jaguar_____Land_____Rover  = 90,
        emessageid_LangJag_RCM_Can_002_Jaguar_____Land_____Rover  = 91,
        emessageid_LangJag_RDCM_Can_001_Jaguar_____Land_____Rover  = 92,
        emessageid_LangJag_RDCM_Can_002_Jaguar_____Land_____Rover  = 93,
        emessageid_LangJag_RDUM_Can_001_Jaguar_____Land_____Rover  = 94,
        emessageid_LangJag_RDUM_Can_002_Jaguar_____Land_____Rover  = 95,
        emessageid_LangJag_REM_Can_001_Jaguar_____Land_____Rover  = 96,
        emessageid_LangJag_REM_Can_002_Jaguar_____Land_____Rover  = 97,
        emessageid_LangJag_RFA_Can_001_Jaguar_____Land_____Rover  = 98,
        emessageid_LangJag_RGTM_Can_001_Jaguar_____Land_____Rover  = 99,
        emessageid_LangJag_RGTMB_Can_001_Jaguar_____Land_____Rover  = 100,
        emessageid_LangJag_RHVAC_Can_001_Jaguar_____Land_____Rover  = 101,
        emessageid_LangJag_RHVAC_Can_002_Jaguar_____Land_____Rover  = 102,
        emessageid_LangJag_RLSM_Can_001_Jaguar_____Land_____Rover  = 103,
        emessageid_LangJag_RRSM_Can_001_Jaguar_____Land_____Rover  = 104,
        emessageid_LangJag_SARM_Can_001_Jaguar_____Land_____Rover  = 105,
        emessageid_LangJag_SASM_Can_001_Jaguar_____Land_____Rover  = 106,
        emessageid_LangJag_SASM_Can_002_Jaguar_____Land_____Rover  = 107,
        emessageid_LangJag_SCME_Can_001_Jaguar_____Land_____Rover  = 108,
        emessageid_LangJag_SCMF_Can_001_Jaguar_____Land_____Rover  = 109,
        emessageid_LangJag_SODL_Can_001_Jaguar_____Land_____Rover  = 110,
        emessageid_LangJag_SODR_Can_001_Jaguar_____Land_____Rover  = 111,
        emessageid_LangJag_SPMA_Can_001_Jaguar_____Land_____Rover  = 112,
        emessageid_LangJag_SPMB_Can_001_Jaguar_____Land_____Rover  = 113,
        emessageid_LangJag_SPRM_Can_001_Jaguar_____Land_____Rover  = 114,
        emessageid_LangJag_SRM_Can_001_Jaguar_____Land_____Rover  = 115,
        emessageid_LangJag_SRM_Can_002_Jaguar_____Land_____Rover  = 116,
        emessageid_LangJag_SUMB_Can_001_Jaguar_____Land_____Rover  = 117,
        emessageid_LangJag_TCCM_Can_001_Jaguar_____Land_____Rover  = 118,
        emessageid_LangJag_TCCM_Can_002_Jaguar_____Land_____Rover  = 119,
        emessageid_LangJag_TCM_Can_001_Jaguar_____Land_____Rover  = 120,
        emessageid_LangJag_TCM_Can_002_Jaguar_____Land_____Rover  = 121,
        emessageid_LangJag_TCU_Can_001_Jaguar_____Land_____Rover  = 122,
        emessageid_LangJag_TEL_Can_001_Jaguar_____Land_____Rover  = 123,
        emessageid_LangJag_TEL_Can_002_Jaguar_____Land_____Rover  = 124,
        emessageid_LangJag_TMC_Can_001_Jaguar_____Land_____Rover  = 125,
        emessageid_LangJag_TPM_Can_001_Jaguar_____Land_____Rover  = 126,
        emessageid_LangJag_TPM_Can_002_Jaguar_____Land_____Rover  = 127,
        emessageid_LangJag_TPM_Can_003_Jaguar_____Land_____Rover  = 128,
        emessageid_LangJag_TRM_Can_001_Jaguar_____Land_____Rover  = 129,
        emessageid_LangJag_TVM_Can_001_Jaguar_____Land_____Rover  = 130,
        emessageid_LangJag_TVM_Can_002_Jaguar_____Land_____Rover  = 131,
        emessageid_LangJag_VDM_Can_001_Jaguar_____Land_____Rover  = 132,
        emessageid_LangJag_VIM_Can_001_Jaguar_____Land_____Rover  = 133,
        emessageid_LangJag_VIM_Can_002_Jaguar_____Land_____Rover  = 134,
        emessageid_LangJag_TCM_BOSCH_001_Jaguar_____Land_____Rover  = 135,
        emessageid_LangJag_PCM_KW2000_001_Jaguar_____Land_____Rover  = 136,
        emessageid_LangJag_ABS_KW2000_001_Jaguar_____Land_____Rover  = 137,
        emessageid_LangJag_ABS_KW2000_002_Jaguar_____Land_____Rover  = 138,
        emessageid_LangJag_ACC_KW2000_001_Jaguar_____Land_____Rover  = 139,
        emessageid_LangJag_ARM_KW2000_001_Jaguar_____Land_____Rover  = 140,
        emessageid_LangJag_BPM_KW2000_001_Jaguar_____Land_____Rover  = 141,
        emessageid_LangJag_PCM_KW2000_002_Jaguar_____Land_____Rover  = 142,
        emessageid_LangJag_PCM_KW2000_003_Jaguar_____Land_____Rover  = 143,
        emessageid_LangJag_IP_KW2000_001_Jaguar_____Land_____Rover  = 144,
        emessageid_LangJag_TCM_KW2000_001_Jaguar_____Land_____Rover  = 145,
        emessageid_LangJag_ABS_DS2_001_Jaguar_____Land_____Rover  = 146,
        emessageid_LangJag_ADHLS_DS2_001_Jaguar_____Land_____Rover  = 147,
        emessageid_LangJag_ARM_DS2_001_Jaguar_____Land_____Rover  = 148,
        emessageid_LangJag_ASU_DS2_001_Jaguar_____Land_____Rover  = 149,
        emessageid_LangJag_ATC_DS2_001_Jaguar_____Land_____Rover  = 150,
        emessageid_LangJag_BPM_DS2_001_Jaguar_____Land_____Rover  = 151,
        emessageid_LangJag_CPM_DS2_001_Jaguar_____Land_____Rover  = 152,
        emessageid_LangJag_DISP_DS2_001_Jaguar_____Land_____Rover  = 153,
        emessageid_LangJag_DSM_DS2_001_Jaguar_____Land_____Rover  = 154,
        emessageid_LangJag_DSP_DS2_001_Jaguar_____Land_____Rover  = 155,
        emessageid_LangJag_FETM_DS2_001_Jaguar_____Land_____Rover  = 156,
        emessageid_LangJag_HID_DS2_001_Jaguar_____Land_____Rover  = 157,
        emessageid_LangJag_HID_DS2_002_Jaguar_____Land_____Rover  = 158,
        emessageid_LangJag_IP_DS2_001_Jaguar_____Land_____Rover  = 159,
        emessageid_LangJag_LCM_DS2_001_Jaguar_____Land_____Rover  = 160,
        emessageid_LangJag_MFD_DS2_001_Jaguar_____Land_____Rover  = 161,
        emessageid_LangJag_MFSW_DS2_001_Jaguar_____Land_____Rover  = 162,
        emessageid_LangJag_NAV_DS2_001_Jaguar_____Land_____Rover  = 163,
        emessageid_LangJag_NAV_DS2_002_Jaguar_____Land_____Rover  = 164,
        emessageid_LangJag_PAM_DS2_001_Jaguar_____Land_____Rover  = 165,
        emessageid_LangJag_PATS_DS2_001_Jaguar_____Land_____Rover  = 166,
        emessageid_LangJag_PATS_DS2_002_Jaguar_____Land_____Rover  = 167,
        emessageid_LangJag_PCM_DS2_001_Jaguar_____Land_____Rover  = 168,
        emessageid_LangJag_RAIN_DS2_001_Jaguar_____Land_____Rover  = 169,
        emessageid_LangJag_SASM_DS2_001_Jaguar_____Land_____Rover  = 170,
        emessageid_LangJag_SCLM_DS2_001_Jaguar_____Land_____Rover  = 171,
        emessageid_LangJag_TBOX_DS2_001_Jaguar_____Land_____Rover  = 172,
        emessageid_LangJag_TCM_DS2_001_Jaguar_____Land_____Rover  = 173,
        emessageid_LangJag_TCM_DS2_002_Jaguar_____Land_____Rover  = 174,
        emessageid_LangJag_TPM_DS2_001_Jaguar_____Land_____Rover  = 175,
        emessageid_LangJag_VACM_DS2_001_Jaguar_____Land_____Rover  = 176,
        emessageid_LangJag_VIDEO_DS2_001_Jaguar_____Land_____Rover  = 177,
        emessageid_LangJag_LCM_L_DS2_Def_001_Jaguar_____Land_____Rover  = 178,
        emessageid_LangJag_LCM_R_DS2_Def_001_Jaguar_____Land_____Rover  = 179,
        emessageid_LangJag_BPM_DS2_Def_001_Jaguar_____Land_____Rover  = 180,
        emessageid_LangJag_DSM_DS2_Def_001_Jaguar_____Land_____Rover  = 181,
        emessageid_LangJag_HVAC_DS2_Def_001_Jaguar_____Land_____Rover  = 182,
        emessageid_LangJag_LCM_DS2_Def_001_Jaguar_____Land_____Rover  = 183,
        emessageid_LangJag_MFSW_DS2_Def_001_Jaguar_____Land_____Rover  = 184,
        emessageid_LangJag_PAM_DS2_Def_001_Jaguar_____Land_____Rover  = 185,
        emessageid_LangJag_SCLM_DS2_Def_001_Jaguar_____Land_____Rover  = 186,
        emessageid_LangJag_RCM_DS2_Def_001_Jaguar_____Land_____Rover  = 187,
        emessageid_LangJag_RAIN_DS2_Def_001_Jaguar_____Land_____Rover  = 188,
        emessageid_LangJag_PCM_KW2000_004_Jaguar_____Land_____Rover  = 189,
    
    }enumMessageid_Jaguar_____Land_____Rover;
    
    
    typedef enum _enumSystem_Jaguar_____Land_____Rover{
        esystem_UNKNOWN_Jaguar_____Land_____Rover   = 0,
        esystem_PCM_Jaguar_____Land_____Rover  = 1,
        esystem_TCM_Jaguar_____Land_____Rover  = 2,
        esystem_ABS_Jaguar_____Land_____Rover  = 3,
        esystem_ACC_Jaguar_____Land_____Rover  = 4,
        esystem_ARM_Jaguar_____Land_____Rover  = 5,
        esystem_BPM_Jaguar_____Land_____Rover  = 6,
        esystem_IP_Jaguar_____Land_____Rover  = 7,
        esystem_PATS_Jaguar_____Land_____Rover  = 8,
        esystem_ADHLS_Jaguar_____Land_____Rover  = 9,
        esystem_ASU_Jaguar_____Land_____Rover  = 10,
        esystem_ATC_Jaguar_____Land_____Rover  = 11,
        esystem_CPM_Jaguar_____Land_____Rover  = 12,
        esystem_DISP_Jaguar_____Land_____Rover  = 13,
        esystem_DSM_Jaguar_____Land_____Rover  = 14,
        esystem_DSP_Jaguar_____Land_____Rover  = 15,
        esystem_FETM_Jaguar_____Land_____Rover  = 16,
        esystem_HID_Jaguar_____Land_____Rover  = 17,
        esystem_LCM_Jaguar_____Land_____Rover  = 18,
        esystem_MFD_Jaguar_____Land_____Rover  = 19,
        esystem_MFSW_Jaguar_____Land_____Rover  = 20,
        esystem_NAV_Jaguar_____Land_____Rover  = 21,
        esystem_PAM_Jaguar_____Land_____Rover  = 22,
        esystem_RAIN_Jaguar_____Land_____Rover  = 23,
        esystem_SASM_Jaguar_____Land_____Rover  = 24,
        esystem_SCLM_Jaguar_____Land_____Rover  = 25,
        esystem_TBOX_Jaguar_____Land_____Rover  = 26,
        esystem_TPM_Jaguar_____Land_____Rover  = 27,
        esystem_VACM_Jaguar_____Land_____Rover  = 28,
        esystem_VIDEO_Jaguar_____Land_____Rover  = 29,
        esystem_RLM_Jaguar_____Land_____Rover  = 30,
        esystem_BCM_Jaguar_____Land_____Rover  = 31,
        esystem_HVAC_Jaguar_____Land_____Rover  = 32,
        esystem_IPC_Jaguar_____Land_____Rover  = 33,
        esystem_PBM_Jaguar_____Land_____Rover  = 34,
        esystem_TCCM_Jaguar_____Land_____Rover  = 35,
        esystem_VDM_Jaguar_____Land_____Rover  = 36,
        esystem_RCM_Jaguar_____Land_____Rover  = 37,
        esystem_AAM_Jaguar_____Land_____Rover  = 38,
        esystem_ACM_Jaguar_____Land_____Rover  = 39,
        esystem_TEL_Jaguar_____Land_____Rover  = 40,
        esystem_FEM_Jaguar_____Land_____Rover  = 41,
        esystem_DACMC_Jaguar_____Land_____Rover  = 42,
        esystem_FLM_Jaguar_____Land_____Rover  = 43,
        esystem_RDCM_Jaguar_____Land_____Rover  = 44,
        esystem_REM_Jaguar_____Land_____Rover  = 45,
        esystem_SRM_Jaguar_____Land_____Rover  = 46,
        esystem_CCM_Jaguar_____Land_____Rover  = 47,
        esystem_ATCM_Jaguar_____Land_____Rover  = 48,
        esystem_TMC_Jaguar_____Land_____Rover  = 49,
        esystem_TVM_Jaguar_____Land_____Rover  = 50,
        esystem_DDM_Jaguar_____Land_____Rover  = 51,
        esystem_HCM_Jaguar_____Land_____Rover  = 52,
        esystem_PDM_Jaguar_____Land_____Rover  = 53,
        esystem_FCDIM_Jaguar_____Land_____Rover  = 54,
        esystem_ICM_Jaguar_____Land_____Rover  = 55,
        esystem_DABM_Jaguar_____Land_____Rover  = 56,
        esystem_NCM_Jaguar_____Land_____Rover  = 57,
        esystem_OCS_Jaguar_____Land_____Rover  = 58,
        esystem_TRM_Jaguar_____Land_____Rover  = 59,
        esystem_CDP_Jaguar_____Land_____Rover  = 60,
        esystem_GWM_Jaguar_____Land_____Rover  = 61,
        esystem_LCM_L_Jaguar_____Land_____Rover  = 62,
        esystem_LCM_R_Jaguar_____Land_____Rover  = 63,
        esystem_VIM_Jaguar_____Land_____Rover  = 64,
        esystem_RDUM_Jaguar_____Land_____Rover  = 65,
        esystem_RHVAC_Jaguar_____Land_____Rover  = 66,
        esystem_DCSM_Jaguar_____Land_____Rover  = 67,
        esystem_RBM_Jaguar_____Land_____Rover  = 68,
        esystem_ARCM_Jaguar_____Land_____Rover  = 69,
        esystem_SUMB_Jaguar_____Land_____Rover  = 70,
        esystem_GSM_Jaguar_____Land_____Rover  = 71,
        esystem_FACP_Jaguar_____Land_____Rover  = 72,
        esystem_RFA_Jaguar_____Land_____Rover  = 73,
        esystem_BCMB_Jaguar_____Land_____Rover  = 74,
        esystem_SCME_Jaguar_____Land_____Rover  = 75,
        esystem_APIM_Jaguar_____Land_____Rover  = 76,
        esystem_ICS_Jaguar_____Land_____Rover  = 77,
        esystem_SARM_Jaguar_____Land_____Rover  = 78,
        esystem_SODL_Jaguar_____Land_____Rover  = 79,
        esystem_SODR_Jaguar_____Land_____Rover  = 80,
        esystem_PSM_Jaguar_____Land_____Rover  = 81,
        esystem_FTCM_Jaguar_____Land_____Rover  = 82,
        esystem_HCMB_Jaguar_____Land_____Rover  = 83,
        esystem_IPMB_Jaguar_____Land_____Rover  = 84,
        esystem_SCMF_Jaguar_____Land_____Rover  = 85,
        esystem_FCIM_Jaguar_____Land_____Rover  = 86,
        esystem_FCIMB_Jaguar_____Land_____Rover  = 87,
        esystem_SPRM_Jaguar_____Land_____Rover  = 88,
        esystem_AHCM_Jaguar_____Land_____Rover  = 89,
        esystem_RGTM_Jaguar_____Land_____Rover  = 90,
        esystem_SPMA_Jaguar_____Land_____Rover  = 91,
        esystem_SPMB_Jaguar_____Land_____Rover  = 92,
        esystem_RLSM_Jaguar_____Land_____Rover  = 93,
        esystem_RRSM_Jaguar_____Land_____Rover  = 94,
        esystem_AHU_Jaguar_____Land_____Rover  = 95,
        esystem_PSCM_Jaguar_____Land_____Rover  = 96,
        esystem_GSMB_Jaguar_____Land_____Rover  = 97,
        esystem_CHCM_Jaguar_____Land_____Rover  = 98,
        esystem_FTCMB_Jaguar_____Land_____Rover  = 99,
        esystem_CHCMB_Jaguar_____Land_____Rover  = 100,
        esystem_FCIMC_Jaguar_____Land_____Rover  = 101,
        esystem_RGTMB_Jaguar_____Land_____Rover  = 102,
        esystem_TCU_Jaguar_____Land_____Rover  = 103,
        esystem_CAV_Jaguar_____Land_____Rover  = 104,
        esystem_AWDCM_Jaguar_____Land_____Rover  = 105,
        esystem_GPSM_Jaguar_____Land_____Rover  = 106,
        esystem_AUCM_Jaguar_____Land_____Rover  = 107,
        esystem_HUD_Jaguar_____Land_____Rover  = 108,
        esystem_KVM_Jaguar_____Land_____Rover  = 109,
        esystem_ACE_Jaguar_____Land_____Rover  = 110,
        esystem_RDCSM_Jaguar_____Land_____Rover  = 111,
        esystem_ADCM_Jaguar_____Land_____Rover  = 112,
        esystem_EPB_Jaguar_____Land_____Rover  = 113,
        esystem_GEM_Jaguar_____Land_____Rover  = 114,
        esystem_ADS_Jaguar_____Land_____Rover  = 115,
        esystem_ADRC_Jaguar_____Land_____Rover  = 116,
        esystem_IPK_Jaguar_____Land_____Rover  = 117,
        esystem_MCC_Jaguar_____Land_____Rover  = 118,
        esystem_ICE_Jaguar_____Land_____Rover  = 119,
        esystem_AMP_Jaguar_____Land_____Rover  = 120,
        esystem_ISM_Jaguar_____Land_____Rover  = 121,
        esystem_FSJB_Jaguar_____Land_____Rover  = 122,
        esystem_RSJB_Jaguar_____Land_____Rover  = 123,
        esystem_ICP_Jaguar_____Land_____Rover  = 124,
        esystem_CMM_Jaguar_____Land_____Rover  = 125,
        esystem_RATC_Jaguar_____Land_____Rover  = 126,
        esystem_RETM_Jaguar_____Land_____Rover  = 127,
        esystem_ADHLS_L_Jaguar_____Land_____Rover  = 128,
        esystem_ADHLS_R_Jaguar_____Land_____Rover  = 129,
        esystem_RSM_Jaguar_____Land_____Rover  = 130,
        esystem_TCMMB_Jaguar_____Land_____Rover  = 131,
        esystem_TCMZF_Jaguar_____Land_____Rover  = 132,
        esystem_SBC_Jaguar_____Land_____Rover  = 133,
        esystem_DHM_Jaguar_____Land_____Rover  = 134,
        esystem_PHM_Jaguar_____Land_____Rover  = 135,
        esystem_SLM_Jaguar_____Land_____Rover  = 136,
        esystem_SRS_Jaguar_____Land_____Rover  = 137,
    
    }enumSystem_Jaguar_____Land_____Rover;
    
    
    typedef enum _enumSubsystem_Jaguar_____Land_____Rover{
        esubsystem_UNKNOWN_Jaguar_____Land_____Rover   = 0,
        esubsystem_CPM_____Combustion_____Preheater_____Module_Jaguar_____Land_____Rover  = 1,
    
    }enumSubsystem_Jaguar_____Land_____Rover;
    
    
    typedef enum _enumTiming_Jaguar_____Land_____Rover{
        etiming_UNKNOWN_Jaguar_____Land_____Rover   = 0,
        etiming_Twup_Honda_BOSCH_Jaguar_____Land_____Rover  = 1,
        etiming_TimingP_Honda_BOSCH_Jaguar_____Land_____Rover  = 2,
        etiming_TimingW_Honda_BOSCH_Jaguar_____Land_____Rover  = 3,
        etiming_Kw1281Default_Jaguar_____Land_____Rover  = 4,
        etiming_TwupGeneral_Jaguar_____Land_____Rover  = 5,
        etiming_TimingP_Normal_Jaguar_____Land_____Rover  = 6,
        etiming_TimingW_Normal_Jaguar_____Land_____Rover  = 7,
        etiming_Twup_BMW_KW_Jaguar_____Land_____Rover  = 8,
        etiming_TimingP_BMW_KW_Jaguar_____Land_____Rover  = 9,
        etiming_TimingW_BMW_KW_Jaguar_____Land_____Rover  = 10,
        etiming_Twup_BMW_DS2_Jaguar_____Land_____Rover  = 11,
        etiming_TimingP_BMW_DS2_Jaguar_____Land_____Rover  = 12,
        etiming_TimingW_BMW_DS2_Jaguar_____Land_____Rover  = 13,
        etiming_TimingP_Chrysler_CAN_Jaguar_____Land_____Rover  = 14,
        etiming_TimingP_Chrysler_CAN_C_UDS_Jaguar_____Land_____Rover  = 15,
        etiming_TimingP_Chrysler_CAN_I_UDS_Jaguar_____Land_____Rover  = 16,
        etiming_TimingP_Chrysler_CCD_Jaguar_____Land_____Rover  = 17,
        etiming_TimingP_Chrysler_CCD2_Jaguar_____Land_____Rover  = 18,
        etiming_TimingP_Chrysler_KW2000_Jaguar_____Land_____Rover  = 19,
        etiming_TimingP_Chrysler_KWFB_Jaguar_____Land_____Rover  = 20,
        etiming_TimingP_Chrysler_MB_ISO_Jaguar_____Land_____Rover  = 21,
        etiming_TimingP_Chrysler_MUT_Jaguar_____Land_____Rover  = 22,
        etiming_TimingP_Chrysler_SCI_Jaguar_____Land_____Rover  = 23,
        etiming_TimingP_Chrysler_VPW_Jaguar_____Land_____Rover  = 24,
        etiming_TimingP_Ford_CAN_Jaguar_____Land_____Rover  = 25,
        etiming_TimingP_Ford_CAN_UDS_Jaguar_____Land_____Rover  = 26,
        etiming_TimingP_Ford_ISO9141_Jaguar_____Land_____Rover  = 27,
        etiming_TimingP_Ford_MCAN_Jaguar_____Land_____Rover  = 28,
        etiming_TimingP_Ford_MCAN_____UDS_Jaguar_____Land_____Rover  = 29,
        etiming_TimingP_Ford_PWM_Jaguar_____Land_____Rover  = 30,
        etiming_TimingP_Ford_UBP_Jaguar_____Land_____Rover  = 31,
        etiming_TimingP_GM_ALDL_Jaguar_____Land_____Rover  = 32,
        etiming_TimingP_GM_CAN_Jaguar_____Land_____Rover  = 33,
        etiming_TimingP_GM_GMLAN_Jaguar_____Land_____Rover  = 34,
        etiming_TimingP_GM_KW_Jaguar_____Land_____Rover  = 35,
        etiming_TimingP_GM_SDL_Jaguar_____Land_____Rover  = 36,
        etiming_TimingP_GM_SWCAN_Jaguar_____Land_____Rover  = 37,
        etiming_TimingP_GM_VPW_Jaguar_____Land_____Rover  = 38,
        etiming_TimingP_Honda_92HM_Jaguar_____Land_____Rover  = 39,
        etiming_TimingP_Honda_95HM_Jaguar_____Land_____Rover  = 40,
        etiming_TimingP_Honda_CAN_Jaguar_____Land_____Rover  = 41,
        etiming_TimingP_Honda_H99B_Jaguar_____Land_____Rover  = 42,
        etiming_TimingP_Honda_KW2000_Jaguar_____Land_____Rover  = 43,
        etiming_TimingP_Toyota_CAN_Jaguar_____Land_____Rover  = 44,
        etiming_TimingP_Toyota_ISO9141_Jaguar_____Land_____Rover  = 45,
        etiming_TimingP_Toyota_KW2000_Jaguar_____Land_____Rover  = 46,
        etiming_TimingP_Toyota_VPW_Jaguar_____Land_____Rover  = 47,
        etiming_TimingW_Chrysler_MB_ISO_Jaguar_____Land_____Rover  = 48,
        etiming_TimingW_Chrysler_MUT_Jaguar_____Land_____Rover  = 49,
        etiming_TimingW_Ford_ISO9141_Jaguar_____Land_____Rover  = 50,
        etiming_TimingW_GM_KW_Jaguar_____Land_____Rover  = 51,
        etiming_TimingW_Toyota_ISO9141_Jaguar_____Land_____Rover  = 52,
        etiming_Twup_Chrysler_KW2000_Jaguar_____Land_____Rover  = 53,
        etiming_Twup_Chrysler_KWFB_Jaguar_____Land_____Rover  = 54,
        etiming_Twup_Ford_UBP_Jaguar_____Land_____Rover  = 55,
        etiming_Twup_GM_KW_Jaguar_____Land_____Rover  = 56,
        etiming_Twup_Honda_92HM_Jaguar_____Land_____Rover  = 57,
        etiming_Twup_Honda_95HM_Jaguar_____Land_____Rover  = 58,
        etiming_Twup_Honda_H99B_Jaguar_____Land_____Rover  = 59,
        etiming_Twup_Honda_KW2000_Jaguar_____Land_____Rover  = 60,
        etiming_Twup_Toyota_KW2000_10400_Jaguar_____Land_____Rover  = 61,
        etiming_Twup_Toyota_KW2000_9600_Jaguar_____Land_____Rover  = 62,
        etiming_TwupHonda_00_Jaguar_____Land_____Rover  = 63,
        etiming_TimingP_CANNormal_Jaguar_____Land_____Rover  = 64,
        etiming_Twup_GM_KW9600_Jaguar_____Land_____Rover  = 65,
        etiming_TimingP_Volvo_D2_Jaguar_____Land_____Rover  = 66,
        etiming_TimingP_Volvo_GGD_Jaguar_____Land_____Rover  = 67,
        etiming_TimingP_Volvo_KW_Jaguar_____Land_____Rover  = 68,
        etiming_TimingW_Volvo_D2_Jaguar_____Land_____Rover  = 69,
        etiming_Twup_Volvo_KW_Jaguar_____Land_____Rover  = 70,
        etiming_Twup_Volvo_GGD_Jaguar_____Land_____Rover  = 71,
        etiming_Twup_Volvo_D2_Jaguar_____Land_____Rover  = 72,
        etiming_TimingW_Volvo_GGD_Jaguar_____Land_____Rover  = 73,
        etiming_TimingW_Volvo_KW_Jaguar_____Land_____Rover  = 74,
        etiming_TimingP_BMW_KW2000_Jaguar_____Land_____Rover  = 75,
        etiming_TimingP_Mercedes_Benz_CAN_Jaguar_____Land_____Rover  = 76,
        etiming_TimingP_Mercedes_Benz_CAN_UDS_Jaguar_____Land_____Rover  = 77,
        etiming_TimingP_Nissan_DDL1_Jaguar_____Land_____Rover  = 78,
    
    }enumTiming_Jaguar_____Land_____Rover;
    
    
    typedef enum _enumErasetype_Jaguar_____Land_____Rover{
        eerasetype_UNKNOWN_Jaguar_____Land_____Rover   = 0,
        eerasetype_EraseType_ID0002_Jaguar_____Land_____Rover  = 1,
    
    }enumErasetype_Jaguar_____Land_____Rover;
    
    
    typedef enum _enumModel_Jaguar_____Land_____Rover{
        emodel_UNKNOWN_Jaguar_____Land_____Rover   = 0,
        emodel_Range_____Rover______38A__Jaguar_____Land_____Rover  = 1,
        emodel_Defender_Jaguar_____Land_____Rover  = 2,
        emodel_Discovery_____I_Jaguar_____Land_____Rover  = 3,
        emodel_Discovery_____II_Jaguar_____Land_____Rover  = 4,
        emodel_Freelander_Jaguar_____Land_____Rover  = 5,
        emodel_Range_____Rover_____New_Jaguar_____Land_____Rover  = 6,
        emodel_LR3_Jaguar_____Land_____Rover  = 7,
        emodel_LR2_Jaguar_____Land_____Rover  = 8,
        emodel_Range_____Rover_____Sport_Jaguar_____Land_____Rover  = 9,
        emodel_S_Type_Jaguar_____Land_____Rover  = 10,
        emodel_XF_Jaguar_____Land_____Rover  = 11,
        emodel_XJ_____Series_____New_Jaguar_____Land_____Rover  = 12,
        emodel_XK_____Series_____New_Jaguar_____Land_____Rover  = 13,
        emodel_X_Type_Jaguar_____Land_____Rover  = 14,
        emodel_LR4_Jaguar_____Land_____Rover  = 15,
        emodel_Range_____Rover_____Evoque_Jaguar_____Land_____Rover  = 16,
        emodel_F_Type_Jaguar_____Land_____Rover  = 17,
        emodel_Range_____Rover_____All_____New_Jaguar_____Land_____Rover  = 18,
        emodel_Range_____Rover_Jaguar_____Land_____Rover  = 19,
        emodel_Discovery_Jaguar_____Land_____Rover  = 20,
        emodel_XK_Jaguar_____Land_____Rover  = 21,
        emodel_XJ_____Series_Jaguar_____Land_____Rover  = 22,
        emodel_XKR_Jaguar_____Land_____Rover  = 23,
        emodel_XKR_S_Jaguar_____Land_____Rover  = 24,
        emodel_XJ_____Portfolio_Jaguar_____Land_____Rover  = 25,
        emodel_XJ8_Jaguar_____Land_____Rover  = 26,
        emodel_XJR_Jaguar_____Land_____Rover  = 27,
        emodel_XKR_____Portfolio_Jaguar_____Land_____Rover  = 28,
        emodel_XK8_Jaguar_____Land_____Rover  = 29,
        emodel_XJ_____Sport_Jaguar_____Land_____Rover  = 30,
        emodel_XJ_Jaguar_____Land_____Rover  = 31,
        emodel_XJ6_Jaguar_____Land_____Rover  = 32,
        emodel_XJS_Jaguar_____Land_____Rover  = 33,
        emodel_XJ12_Jaguar_____Land_____Rover  = 34,
        emodel_Range_____Rover_____Classic_Jaguar_____Land_____Rover  = 35,
        emodel_XJ_____Series___________XJ6_____Sedan_Jaguar_____Land_____Rover  = 36,
        emodel_XJ_____Series___________XJ8_Jaguar_____Land_____Rover  = 37,
        emodel_XK_____Series___________XK8_Jaguar_____Land_____Rover  = 38,
        emodel_XK_____Series___________XKR_Jaguar_____Land_____Rover  = 39,
    
    }enumModel_Jaguar_____Land_____Rover;
    
    
    typedef enum _enumEngine_Jaguar_____Land_____Rover{
        eengine_UNKNOWN_Jaguar_____Land_____Rover   = 0,
        eengine_V8______4_2L_Jaguar_____Land_____Rover  = 1,
        eengine_V6______3_0L_Jaguar_____Land_____Rover  = 2,
        eengine_V8______5_0L_Jaguar_____Land_____Rover  = 3,
        eengine_L4______2_0L_Jaguar_____Land_____Rover  = 4,
        eengine_L6______3_2L_Jaguar_____Land_____Rover  = 5,
        eengine_V6______4_0L_Jaguar_____Land_____Rover  = 6,
        eengine_V8______4_4L_Jaguar_____Land_____Rover  = 7,
        eengine_V6______2_5L_Jaguar_____Land_____Rover  = 8,
        eengine_V8______4_6L_Jaguar_____Land_____Rover  = 9,
        eengine_V8______4_0L_Jaguar_____Land_____Rover  = 10,
        eengine_L6______4_0L_Jaguar_____Land_____Rover  = 11,
        eengine_V12______6_0L_Jaguar_____Land_____Rover  = 12,
    
    }enumEngine_Jaguar_____Land_____Rover;
    

#endif