/******************************************************************************************************************
* Engineer    : automatic generated
* Date        : 10/14/2015
* Version   : V01.00.01
********************************************************************************************************************/


#ifndef __ENUMS_H__
#define __ENUMS_H__

#include "enums_Global.h"
#include "enums_GlobalTruck.h"
#include "enums_BMW.h"
#include "enums_BYD.h"
#include "enums_Chery.h"
#include "enums_Chrysler.h"
#include "enums_Daewoo.h"
#include "enums_Daihatsu.h"
#include "enums_Faw.h"
#include "enums_Fiat.h"
#include "enums_Ford.h"
#include "enums_GM.h"
#include "enums_Honda.h"
#include "enums_Hyundai.h"
#include "enums_Isuzu.h"
#include "enums_Jaguar_____Land_____Rover.h"
#include "enums_Mazda.h"
#include "enums_Mercedes_Benz.h"
#include "enums_MG.h"
#include "enums_Mitsubishi.h"
#include "enums_Nissan.h"
#include "enums_Opel.h"
#include "enums_Peugeot.h"
#include "enums_Porsche.h"
#include "enums_Ssangyong.h"
#include "enums_Subaru.h"
#include "enums_Suzuki.h"
#include "enums_Toyota.h"
#include "enums_Renault.h"
#include "enums_Volkswagen.h"
#include "enums_Volvo.h"




typedef enum _enumYear{
    eyear_UNKNOWN   = 0,
    eyear_1996  = 16,
    eyear_1997  = 17,
    eyear_1998  = 18,
    eyear_1999  = 19,
    eyear_2000  = 20,
    eyear_2001  = 21,
    eyear_2002  = 22,
    eyear_2003  = 23,
    eyear_2004  = 24,
    eyear_2005  = 25,
    eyear_2006  = 26,
    eyear_2007  = 27,
    eyear_2008  = 28,
    eyear_2009  = 29,
    eyear_2010  = 30,
    eyear_2011  = 31,
    eyear_2012  = 32,
    eyear_2013  = 33,
    eyear_2014  = 34,
    eyear_2015  = 35,
    eyear_Others  = 65534,
    eyear_MAX  = 65535,
    eyear_2016  = 36,
}enumYear;


typedef enum _enumManufacturer{
    emanufacturer_UNKNOWN   = 0,
    emanufacturer_BMW  = 1,
    emanufacturer_Chrysler  = 2,
    emanufacturer_Ford  = 3,
    emanufacturer_GM  = 4,
    emanufacturer_Honda  = 5,
    emanufacturer_Hyundai  = 6,
    emanufacturer_Mazda  = 10,
    emanufacturer_Mercedes_Benz  = 11,
    emanufacturer_Nissan  = 12,
    emanufacturer_Toyota  = 13,
    emanufacturer_Volkswagen  = 14,
    emanufacturer_Volvo  = 15,
    emanufacturer_Isuzu  = 16,
    emanufacturer_Mitsubishi  = 17,
    emanufacturer_Subaru  = 18,
    emanufacturer_Suzuki  = 19,
    emanufacturer_Porsche  = 20,
    emanufacturer_Others  = 65534,
    emanufacturer_MAX  = 65535,
    emanufacturer_Generic  = 65535,
    emanufacturer_Jaguar_____Land_____Rover  = 21,
    emanufacturer_BYD  = 22,
    emanufacturer_Chery  = 23,
    emanufacturer_Daihatsu  = 24,
    emanufacturer_Ssangyong  = 25,
    emanufacturer_Rover_____Group  = 26,
    emanufacturer_SAIC  = 27,
    emanufacturer_Fiat  = 28,
    emanufacturer_Peugeot  = 29,
    emanufacturer_Daewoo  = 30,
    emanufacturer_Lifan  = 31,
    emanufacturer_Faw  = 32,
    emanufacturer_MG  = 33,
    emanufacturer_Opel  = 34,
    emanufacturer_Renault  = 35,
    emanufacturer_GlobalTruck  = 65533,
}enumManufacturer;


typedef enum _enumMake{
    emake_UNKNOWN   = 0,
    emake_Acura  = 1,
    emake_AM_____General  = 2,
    emake_Audi  = 3,
    emake_BMW  = 4,
    emake_Buick  = 5,
    emake_Cadillac  = 6,
    emake_Chevrolet  = 7,
    emake_Chrysler  = 8,
    emake_Daewoo  = 9,
    emake_Dodge  = 10,
    emake_Eagle  = 11,
    emake_Ford  = 12,
    emake_Geo  = 13,
    emake_GMC  = 14,
    emake_Honda  = 15,
    emake_Hummer  = 16,
    emake_Hyundai  = 17,
    emake_Infiniti  = 18,
    emake_Jaguar  = 19,
    emake_Jeep  = 20,
    emake_Kia  = 21,
    emake_Land_____Rover  = 22,
    emake_Lexus  = 23,
    emake_Lincoln  = 24,
    emake_Mazda  = 25,
    emake_Mercedes_Benz  = 26,
    emake_Mercury  = 27,
    emake_Mini  = 28,
    emake_Nissan  = 29,
    emake_Oldsmobile  = 30,
    emake_Plymouth  = 31,
    emake_Pontiac  = 32,
    emake_Ram  = 33,
    emake_Saab  = 34,
    emake_Saturn  = 35,
    emake_Scion  = 36,
    emake_SRT  = 37,
    emake_Toyota  = 38,
    emake_Volkswagen  = 39,
    emake_Volvo  = 40,
    emake_Fiat  = 41,
    emake_Isuzu  = 42,
    emake_Mitsubishi  = 43,
    emake_Porsche  = 44,
    emake_Smart  = 45,
    emake_Subaru  = 46,
    emake_Suzuki  = 47,
    emake_Others  = 65534,
    emake_MAX  = 65535,
    emake_BYD  = 48,
    emake_Chery  = 49,
    emake_Daihatsu  = 50,
    emake_Ssangyong  = 51,
    emake_MG  = 52,
    emake_Peugeot  = 53,
    emake_Seat  = 54,
    emake_Bentley  = 55,
    emake_Alfa_____Romeo  = 56,
    emake_Citro_n  = 57,
    emake_Lifan  = 58,
    emake_Faw  = 59,
    emake_GM  = 60,
    emake_Opel  = 61,
    emake_Fiat_FCA_  = 62,
    emake_Renault  = 63,
}enumMake;


typedef enum _enumField{
    efield_UNKNOWN   = 0,
    efield_year  = 1,
    efield_manufacturer  = 2,
    efield_make  = 3,
    efield_model  = 4,
    efield_engine  = 5,
    efield_trim  = 6,
    efield_transmission  = 7,
    efield_bodycode  = 8,
    efield_vin10toyear  = 9,
    efield_protocol  = 10,
    efield_dlc  = 11,
    efield_dlcvoltage  = 12,
    efield_pd_reLap Dangor  = 13,
    efield_reLap Dangor  = 14,
    efield_vref  = 15,
    efield_uartdata  = 16,
    efield_checksum  = 17,
    efield_inittype  = 18,
    efield_connector  = 19,
    efield_dtcstatuse  = 20,
    efield_buffername  = 21,
    efield_dtcdisplaytype  = 22,
    efield_innovagroup  = 23,
    efield_bmwvariantformula  = 24,
    efield_variant  = 25,
    efield_step  = 26,
    efield_bmwreaddtctype  = 27,
    efield_bmwerasedtctype  = 28,
    efield_bmwparserdtctype  = 29,
    efield_command  = 30,
    efield_bmwvariantdecode  = 31,
    efield_readdtccommandlist  = 32,
    efield_commandlist  = 33,
    efield_ecuinfotype  = 34,
    efield_dtcreadtype  = 35,
    efield_lookuptable  = 36,
    efield_messageid  = 37,
    efield_system  = 38,
    efield_timing  = 39,
    efield_erasetype  = 40,
    efield_subsystem  = 41,
    efield_programid  = 42,
    efield_unitinforesult  = 43,
    efield_displayvisible  = 44,
    efield_hondaoption  = 45,
    efield_ecutype  = 46,
    efield_ecupartnumber  = 47,
    efield_parsertype  = 48,
    efield_formula  = 49,
    efield_convertunit  = 50,
    efield_mercedes_supplier  = 51,
    efield_mercedes_qualifier  = 52,
    efield_modeltype  = 53,
    efield_bm  = 54,
    efield_ecuid  = 55,
    efield_type  = 56,
}enumField;


typedef enum _enumVin10toyear{
    evin10toyear_UNKNOWN   = 0,
    evin10toyear_T  = 16,
    evin10toyear_V  = 17,
    evin10toyear_W  = 18,
    evin10toyear_X  = 19,
    evin10toyear_Y  = 20,
    evin10toyear_1  = 21,
    evin10toyear_2  = 22,
    evin10toyear_3  = 23,
    evin10toyear_4  = 24,
    evin10toyear_5  = 25,
    evin10toyear_6  = 26,
    evin10toyear_7  = 27,
    evin10toyear_8  = 28,
    evin10toyear_9  = 29,
    evin10toyear_A  = 30,
    evin10toyear_B  = 31,
    evin10toyear_C  = 32,
    evin10toyear_D  = 33,
    evin10toyear_E  = 34,
    evin10toyear_F  = 35,
    evin10toyear_G  = 36,
    evin10toyear_H  = 37,
    evin10toyear_J  = 38,
    evin10toyear_K  = 39,
    evin10toyear_L  = 40,
    evin10toyear_M  = 41,
    evin10toyear_N  = 42,
    evin10toyear_P  = 43,
    evin10toyear_R  = 44,
    evin10toyear_S  = 45,
}enumVin10toyear;


typedef enum _enumProtocol{
    eprotocol_UNKNOWN   = 0,
    eprotocol_PROTOCOL_NO  = 0,
    eprotocol_PROTOCOL_VPW  = 1,
    eprotocol_PROTOCOL_PWM  = 2,
    eprotocol_PROTOCOL_ISO9141  = 3,
    eprotocol_PROTOCOL_KW2000  = 4,
    eprotocol_PROTOCOL_CAN500KBAUD  = 5,
    eprotocol_PROTOCOL_XCAN500KBAUD  = 6,
    eprotocol_PROTOCOL_CAN250KBAUD  = 7,
    eprotocol_PROTOCOL_XCAN250KBAUD  = 8,
    eprotocol_PROTOCOL_BOSCH  = 9,
    eprotocol_PROTOCOL_RESERVE_10  = 10,
    eprotocol_PROTOCOL_RESERVE_11  = 11,
    eprotocol_PROTOCOL_RESERVE_12  = 12,
    eprotocol_PROTOCOL_RESERVE_13  = 13,
    eprotocol_PROTOCOL_RESERVE_14  = 14,
    eprotocol_PROTOCOL_KW  = 15,
    eprotocol_PROTOCOL_KW1281  = 16,
    eprotocol_PROTOCOL_MUT  = 17,
    eprotocol_PROTOCOL_CAN_C_UDS  = 18,
    eprotocol_PROTOCOL_CAN_I_UDS  = 19,
    eprotocol_PROTOCOL_RESERVE_20  = 20,
    eprotocol_PROTOCOL_CCD2  = 21,
    eprotocol_PROTOCOL_SDL  = 22,
    eprotocol_PROTOCOL_UBP  = 23,
    eprotocol_PROTOCOL_MCAN  = 24,
    eprotocol_PROTOCOL_MCAN_____UDS  = 25,
    eprotocol_PROTOCOL_H99B  = 26,
    eprotocol_PROTOCOL_95HM  = 27,
    eprotocol_PROTOCOL_92HM  = 28,
    eprotocol_PROTOCOL_CAN  = 29,
    eprotocol_PROTOCOL_RESERVE_30  = 30,
    eprotocol_PROTOCOL_RESERVE_31  = 31,
    eprotocol_PROTOCOL_CCD  = 32,
    eprotocol_PROTOCOL_SCI  = 33,
    eprotocol_PROTOCOL_RESERVE_34  = 34,
    eprotocol_PROTOCOL_RESERVE_35  = 35,
    eprotocol_PROTOCOL_RESERVE_36  = 36,
    eprotocol_PROTOCOL_RESERVE_37  = 37,
    eprotocol_PROTOCOL_RESERVE_38  = 38,
    eprotocol_PROTOCOL_RESERVE_39  = 39,
    eprotocol_PROTOCOL_RESERVE_40  = 40,
    eprotocol_PROTOCOL_RESERVE_41  = 41,
    eprotocol_PROTOCOL_OBD1  = 42,
    eprotocol_PROTOCOL_RESERVE_43  = 43,
    eprotocol_PROTOCOL_RESERVE_44  = 44,
    eprotocol_PROTOCOL_RESERVE_45  = 45,
    eprotocol_PROTOCOL_RESERVE_46  = 46,
    eprotocol_PROTOCOL_RESERVE_47  = 47,
    eprotocol_PROTOCOL_DDL1  = 48,
    eprotocol_PROTOCOL_SWCAN  = 49,
    eprotocol_PROTOCOL_RESERVE_50  = 50,
    eprotocol_PROTOCOL_MB_ISO  = 51,
    eprotocol_PROTOCOL_KWFB  = 52,
    eprotocol_PROTOCOL_BMW_CAN  = 53,
    eprotocol_PROTOCOL_TPCAN_2_0  = 54,
    eprotocol_PROTOCOL_TPCAN_1_6_KW1281  = 55,
    eprotocol_PROTOCOL_TPCAN_1_6_KW2000  = 56,
    eprotocol_PROTOCOL_KWSSM  = 57,
    eprotocol_PROTOCOL_DDL2  = 58,
    eprotocol_PROTOCOL_DS2  = 59,
    eprotocol_PROTOCOL_CAN_UDS  = 60,
    eprotocol_PROTOCOL_CANUDS  = 60,
    eprotocol_PROTOCOL_CAN_D2  = 61,
    eprotocol_PROTOCOL_CAN_GGD  = 62,
    eprotocol_PROTOCOL_ALDL  = 63,
    eprotocol_PROTOCOL_GMLAN  = 64,
    eprotocol_PROTOCOL_MAX  = 65535,
    eprotocol_PROTOCOL_CAN_C  = 65,
    eprotocol_PROTOCOL_TCAN  = 66,
    eprotocol_PROTOCOL_DS1  = 70,
    eprotocol_PROTOCOL_DS2_MID  = 71,
    eprotocol_PROTOCOL_D2  = 73,
    eprotocol_PROTOCOL_GGD  = 74,
    eprotocol_Suzuki_SDL  = 75,
    eprotocol_PROTOCOL_SUBARU_KWP_4800  = 76,
    eprotocol_PROTOCOL_SUBARU_FHICAN  = 77,
    eprotocol_PROTOCOL_SUBARU_TMC  = 78,
    eprotocol_PROTOCOL_SUBARU_KWP_10400  = 79,
    eprotocol_PROTOCOL_SUBARU_KWP_1953  = 80,
    eprotocol_PROTOCOL_J1708  = 81,
    eprotocol_PROTOCOL_J1939  = 82,
}enumProtocol;


typedef enum _enumDlc{
    edlc_UNKNOWN   = 0,
    edlc_PIN1  = 2,
    edlc_PIN1_INV  = 3,
    edlc_PIN2  = 4,
    edlc_PIN2_INV  = 5,
    edlc_PIN3  = 6,
    edlc_PIN3_INV  = 7,
    edlc_PIN4  = 8,
    edlc_PIN4_INV  = 9,
    edlc_PIN5  = 10,
    edlc_PIN5_INV  = 11,
    edlc_PIN6  = 12,
    edlc_PIN6_INV  = 13,
    edlc_PIN7  = 14,
    edlc_PIN7_INV  = 15,
    edlc_PIN8  = 16,
    edlc_PIN8_INV  = 17,
    edlc_PIN9  = 18,
    edlc_PIN9_INV  = 19,
    edlc_PIN10  = 20,
    edlc_PIN10_INV  = 21,
    edlc_PIN11  = 22,
    edlc_PIN11_INV  = 23,
    edlc_PIN12  = 24,
    edlc_PIN12_INV  = 25,
    edlc_PIN13  = 26,
    edlc_PIN13_INV  = 27,
    edlc_PIN14  = 28,
    edlc_PIN14_INV  = 29,
    edlc_PIN15  = 30,
    edlc_PIN15_INV  = 31,
    edlc_PIN3_INV_OBD1  = 32,
    edlc_PIN7_OBD1  = 33,
    edlc_PIN15_OBD1  = 34,
    edlc_CCD_3_11  = 35,
    edlc_PIN_NA  = 255,
    edlc_PIN16  = 32,
    edlc_PIN20  = 33,
    edlc_PIN22  = 34,
    edlc_PIN23  = 35,
    edlc_PIN24  = 36,
    edlc_PIN25  = 37,
    edlc_PIN28  = 38,
    edlc_PIN30  = 39,
    edlc_PIN32  = 40,
    edlc_PIN33  = 41,
    edlc_PIN34  = 42,
    edlc_PIN35  = 43,
    edlc_PIN36  = 44,
    edlc_PIN17  = 45,
    edlc_PIN15_INV_OBD1  = 46,
    edlc_PIN9_OBD1  = 47,
    edlc_PIN2_OBD1  = 48,
    edlc_PIN8_OBD1  = 49,
    edlc_PIN14_OBD1  = 50,
    edlc_PIN11_OBD1  = 51,
    edlc_PIN6_OBD1  = 52,
}enumDlc;


typedef enum _enumDlcvoltage{
    edlcvoltage_UNKNOWN   = 0,
    edlcvoltage_LEVEL_FLOAT  = 1,
    edlcvoltage_LEVEL_5V  = 2,
    edlcvoltage_LEVEL_8V  = 3,
    edlcvoltage_LEVEL_12V  = 4,
    edlcvoltage_LEVEL_24V  = 5,
    edlcvoltage_LEVEL_36V  = 6,
}enumDlcvoltage;


typedef enum _enumPd_ReLap Dangor{
    epd_reLap Dangor_UNKNOWN   = 0,
    epd_reLap Dangor_PD_NONE  = 0,
    epd_reLap Dangor_PD_OPEN  = 1,
    epd_reLap Dangor_PD_2K8  = 2,
    epd_reLap Dangor_PD_3K9  = 3,
    epd_reLap Dangor_PD_10K  = 4,
}enumPd_ReLap Dangor;


typedef enum _enumReLap Dangor{
    ereLap Dangor_UNKNOWN   = 0,
    ereLap Dangor_PU_NONE  = 0,
    ereLap Dangor_PU_511  = 1,
    ereLap Dangor_PU_2K7  = 2,
    ereLap Dangor_PU_4K7  = 4,
    ereLap Dangor_PU_1K  = 8,
    ereLap Dangor_PU_2K  = 16,
}enumReLap Dangor;


typedef enum _enumVref{
    evref_UNKNOWN   = 0,
    evref_VREF_NA  = 0,
    evref_VREF_AUTO  = 1,
    evref_VREF_1V5  = 2,
    evref_VREF_2V5  = 3,
}enumVref;


typedef enum _enumUartdata{
    euartdata_UNKNOWN   = 0,
    euartdata_DATA8BIT_NO_PARITY  = 0,
    euartdata_DATA8BIT_EVEN_PARITY  = 1,
    euartdata_DATA8BIT_ODD_PARIRY  = 2,
}enumUartdata;


typedef enum _enumChecksum{
    echecksum_UNKNOWN   = 0,
    echecksum_CS_NONE  = 0,
    echecksum_CS_NORMAL_1BYTE  = 1,
    echecksum_CS_INVERT_1BYTE  = 2,
    echecksum_CS_NORMAL_2BYTE  = 3,
    echecksum_CS_CRC_1D  = 4,
    echecksum_CS_CRC_01  = 5,
}enumChecksum;


typedef enum _enumInittype{
    einittype_UNKNOWN   = 0,
    einittype_INIT_NONE  = 0,
    einittype_INIT_FIVEBAUDS  = 1,
    einittype_INIT_FASTBAUDS  = 2,
    einittype_INIT_MAX  = 3,
}enumInittype;


typedef enum _enumConnector{
    econnector_UNKNOWN   = 0,
    econnector_NONE  = 0,
    econnector_OBDII  = 1,
    econnector_GM_OBD1  = 2,
    econnector_FORD_OBD1  = 3,
    econnector_CHRYSLER_OBD1  = 4,
    econnector_TOYOTA_OBD1  = 5,
    econnector_HONDA_OBD1  = 6,
    econnector_KIA_20_PINS  = 7,
    econnector_TOYOTA_17_PINS  = 8,
    econnector_TOYOTA_22_PINS  = 9,
    econnector_BMW_20_PINS  = 10,
    econnector_NISSAN_14_PINS  = 11,
    econnector_BMW_16_PINS  = 12,
    econnector_BENZ_38_PINS  = 13,
    econnector_CHRYSLER_16_PINS  = 14,
    econnector_BENZ_14PIN_PINS  = 15,
    econnector_MAZDA_17_PINS  = 16,
    econnector_MIT_12_16_PINS  = 17,
    econnector_NISSAN_14_TSURU  = 18,
    econnector_MAX  = 65535,
    econnector_OEM  = 19,
    econnector_Hyundai_12  = 20,
    econnector_Kia_20  = 21,
    econnector_NISSAN_14  = 22,
    econnector_TOYOTA_17_22  = 23,
    econnector_BMW_OEM_20  = 24,
    econnector_BENZ_14  = 25,
    econnector_BMW_20  = 26,
    econnector_BENZ_38  = 27,
}enumConnector;


typedef enum _enumDtcstatuse{
    edtcstatuse_UNKNOWN   = 0,
    edtcstatuse_Type_Dtc_Status_NA  = 0,
    edtcstatuse_Type_Dtc_Status_General  = 1,
    edtcstatuse_Type_Dtc_Status_Chrysler_CAN  = 2,
    edtcstatuse_Type_Dtc_Status_Chrysler_CAN_UDS  = 3,
    edtcstatuse_Type_Dtc_Status_GM_GMLAN_DOC  = 4,
    edtcstatuse_Type_Dtc_Status_HondaBody_KW  = 5,
    edtcstatuse_Type_Dtc_Status_Hyundai_1  = 6,
    edtcstatuse_Type_Dtc_Status_Hyundai_2  = 7,
    edtcstatuse_Type_Dtc_Status_VAG_0  = 8,
    edtcstatuse_Type_Dtc_Status_VAG_1  = 9,
    edtcstatuse_Type_Dtc_Status_VAG_2  = 10,
    edtcstatuse_Type_Dtc_Status_VAG_3  = 11,
    edtcstatuse_Type_Dtc_Status_VAG_4  = 12,
    edtcstatuse_Type_Dtc_Status_VAG_5  = 13,
    edtcstatuse_Type_Dtc_Status_VAG_6  = 14,
    edtcstatuse_Type_Dtc_Status_VAG_7  = 15,
    edtcstatuse_Type_Dtc_Status_Volvo_1  = 16,
    edtcstatuse_Type_Dtc_Status_Mercedes_CANUDS  = 17,
    edtcstatuse_Type_Dtc_Status_Mercedes_KW2000_CAN  = 18,
    edtcstatuse_Type_Dtc_Status_Mercedes_KWFB  = 19,
    edtcstatuse_Type_Dtc_Status_Volvo_2  = 20,
    edtcstatuse_Type_Dtc_Status_Nissan_Byte  = 21,
    edtcstatuse_Type_Dtc_Status_Nissan_Bit  = 22,
    edtcstatuse_Type_Dtc_Status_Hyundai_SRS_0207  = 23,
    edtcstatuse_Type_Dtc_Status_Opel_1  = 24,
    edtcstatuse_Type_Dtc_Status_Opel_2  = 25,
    edtcstatuse_Type_Dtc_Status_Subaru_1  = 26,
    edtcstatuse_Type_Dtc_Status_Suzuki_1  = 27,
    edtcstatuse_Type_Dtc_Status_Subaru_2  = 28,
}enumDtcstatuse;


typedef enum _enumBuffername{
    ebuffername_UNKNOWN   = 0,
    ebuffername_NONE  = 0,
    ebuffername_HISTORY  = 1,
    ebuffername_HISTORICAL  = 2,
    ebuffername_CURRENT  = 3,
    ebuffername_STORED  = 4,
    ebuffername_PENDING  = 5,
    ebuffername_MIL  = 6,
    ebuffername_READINESS  = 7,
    ebuffername_PERMANENT  = 8,
    ebuffername_TEMPORARY  = 9,
    ebuffername_FAIL_SINCE_CLEAR  = 10,
    ebuffername_KOEO  = 11,
    ebuffername_KOER  = 12,
    ebuffername_CONTINUOUS  = 13,
    ebuffername_PAST  = 14,
    ebuffername_PRESENT  = 15,
    ebuffername_CONFIRMED  = 16,
    ebuffername_CM  = 17,
    ebuffername_DCHECK  = 18,
    ebuffername_NOTPRESENT  = 19,
    ebuffername_ACTIVE  = 20,
    ebuffername_MEMORY  = 21,
    ebuffername_INTERMITTENT  = 22,
    ebuffername_INVALID  = 23,
    ebuffername_STATIC  = 24,
    ebuffername_ON_DEMAND  = 25,
    ebuffername_CURRENT_DTC_SINCE_POWER_UP  = 26,
    ebuffername_DTC_SUPPORTED_BY_CALIBRATION  = 27,
    ebuffername_TEST_NOT_PASSED_SINCE_CURRENT_POWER_UP  = 28,
    ebuffername_TEST_NOT_PASSED_SINCE_DTC_CLEARED  = 29,
    ebuffername_KOEO_INJECTOR  = 30,
    ebuffername_KOER_GLOWPLUG  = 31,
    ebuffername_MAX  = 255,
    ebuffername_LATCHED  = 32,
    ebuffername_NOT_____ACTIVE  = 33,
    ebuffername_Test_____not_____Pass_____Since_____Code_____Cleared  = 34,
    ebuffername_Failed_____Since_____Clear  = 35,
    ebuffername_MIL_History  = 36,
    ebuffername_Last_____Test_____Failed  = 37,
    ebuffername_Current_History  = 38,
    ebuffername_Record  = 39,
    ebuffername_Storage  = 40,
    ebuffername_Chassis  = 41,
    ebuffername_Region  = 42,
    ebuffername_Current_____DTC  = 43,
    ebuffername_History_____DTC  = 44,
    ebuffername_Chassi_____DTC  = 45,
    ebuffername_Region_____DTC  = 46,
    ebuffername_Provisional  = 47,
    ebuffername_MIL_____ON  = 48,
    ebuffername_Warning_____Indicator  = 49,
    ebuffername_Not_____Completed_____Operation_____Cycle  = 50,
    ebuffername_Not_____Passed_____SC  = 51,
    ebuffername_Not_____Completed_____SC  = 52,
    ebuffername_Failed_____Operation_____Cycle  = 53,
    ebuffername_Failed  = 54,
}enumBuffername;


typedef enum _enumDtcdisplaytype{
    edtcdisplaytype_UNKNOWN   = 0,
    edtcdisplaytype_DTC_1BYTE_HB_LB  = 1,
    edtcdisplaytype_DTC_DEC  = 2,
    edtcdisplaytype_DTC_DEC_2DIGIT  = 3,
    edtcdisplaytype_DTC_DEC_3DIGIT  = 4,
    edtcdisplaytype_DTC_DEC_4DIGIT  = 5,
    edtcdisplaytype_DTC_DEC_5DIGIT  = 6,
    edtcdisplaytype_DTC_HEX  = 7,
    edtcdisplaytype_DTC_HEX_2DIGIT  = 8,
    edtcdisplaytype_DTC_HEX_3DIGIT  = 9,
    edtcdisplaytype_DTC_HEX_4DIGIT  = 10,
    edtcdisplaytype_DTC_HEX_5DIGIT  = 11,
    edtcdisplaytype_DTC_HEX_6DIGIT  = 12,
    edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_DEC  = 13,
    edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_DEC_2  = 14,
    edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_DEC_3  = 15,
    edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_HEX  = 16,
    edtcdisplaytype_DTC_MAIN_DEC_SUB_1BYTE_HEX_NO_TRIM  = 17,
    edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_DEC  = 18,
    edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_DEC_2  = 19,
    edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_DEC_3  = 20,
    edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_HEX  = 21,
    edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_HEX_NO_TRIM  = 22,
    edtcdisplaytype_DTC_MAIN_SAE_SUB_1BYTE_DEC  = 23,
    edtcdisplaytype_DTC_MAIN_SAE_SUB_1BYTE_DEC_NO_TRIM  = 24,
    edtcdisplaytype_DTC_MAIN_SAE_SUB_1BYTE_HEX  = 25,
    edtcdisplaytype_DTC_MAIN_SAE_SUB_1BYTE_HEX_NO_TRIM  = 26,
    edtcdisplaytype_DTC_OEM_SPECIAL  = 27,
    edtcdisplaytype_DTC_SAE  = 28,
    edtcdisplaytype_DTC_HONDA_HEX_1BYTE  = 29,
    edtcdisplaytype_DTC_MAIN_DEC_5DIGIT_SUB_DEC_3  = 30,
    edtcdisplaytype_DTC_HONDA_MAIN_SUB_HEX  = 31,
    edtcdisplaytype_DTC_MAIN_HEX_SUB_1BYTE_DEC_NO_TRIM  = 32,
    edtcdisplaytype_DTC_TRUCK_J1708  = 33,
    edtcdisplaytype_DTC_TRUCK_J1939  = 34,
    edtcdisplaytype_DTC_ASCII=35,
}enumDtcdisplaytype;


typedef enum _enumInnovagroup{
    einnovagroup_UNKNOWN   = 0,
    einnovagroup_GROUP_OBDII  = 1,
    einnovagroup_GROUP_ABS  = 2,
    einnovagroup_GROUP_SRS  = 4,
    einnovagroup_GROUP_ENH_TCM  = 8,
    einnovagroup_GROUP_ENH_ECM  = 16,
    einnovagroup_GROUP_ENH_PCM  = 16,
    einnovagroup_GROUP_OBDI  = 32,
    einnovagroup_INNOVA_GROUP_UNKNOW  = 255,
}enumInnovagroup;


#endif